### ISSUE TITLE
Code Copied Without Preservation of Copyright and License Notices

### ISSUE THREAD

**Issue by orcaman** [nacos-group/nacos-sdk-go#103]
Hi guys,

It looks like the code for your concurrent map [here](https://github.com/nacos-group/nacos-sdk-go/blob/master/clients/cache/concurrent_map.go) is a direct copy/paste of our implementation (including stuff that we commented out and everything). 

Do feel free to use the code (it's MIT-licensed) and I hope you find it useful, but it would be great if you could follow the license requirement, requiring preservation of copyright and license notices.

Thanks

**Comment by lzp0412** [comment]
Sorry,it's my fault.I will fix it soon.
