### ISSUE TITLE
为什么打印日志要使用系统自带的log(新手一枚)

### ISSUE THREAD

**Issue by yeyudekuangxiang** [nacos-group/nacos-sdk-go#107]
![image](https://user-images.githubusercontent.com/35440854/90586114-fe29f600-e208-11ea-94b4-7ec6d498c383.png)
这样我在其他地方使用log打印的时候 日志都会记录在acm配置的日志文件

**Comment by lzp0412** [comment]
@yeyudekuangxiang 你可以用v1.0.0版本， 日志库已经改成zap。

**Comment by yeyudekuangxiang** [comment]
@lzp0412 谢谢 了解拉
