### ISSUE TITLE
监听一个不存在的nacos配置，会导致客户端死循环不停的获取配置。

### ISSUE THREAD

**Issue by polarrwl** [nacos-group/nacos-sdk-go#114]
调用config_client.IConfigClient的ListenConfig方法监听一个不存在的Nacos配置会导致循环不断到服务器获取配置（1s钟会发送几十次请求），给客户端和Nacos服务器造成很大压力，试了Java客户端没有这个问题。
这个能不能改进一下？

**Comment by sanxun0325** [comment]
@polarrwl 可以提供一下相关日志，以及nacos 服务端，客户端的版本信息。

**Comment by polarrwl** [comment]
Sorry, i forget to see the message, i'm using Nacos Client 1.0.0 and Nacos Server 1.3.0.
Now, I pull the new master branch, it's ok, thx.
