### ISSUE TITLE
无限打印config changed:

### ISSUE THREAD

**Issue by xiaoshanlin000** [nacos-group/nacos-sdk-go#117]
使用版本: master
复现方法: 用的是gatling压测本地服务
每10毫秒打印一次 config changed: 
调用栈发现 config_client.go 中 listenConfigExecutor ()  if taskCount > currentTaskCoun 一直进入

**Comment by sanxun0325** [comment]
@xiaoshanlin000 压测场景可以描述一下，进入taskCount> currentTaskCount 说明配置监听数量再不断的增加。

**Comment by xiaoshanlin000** [comment]
这个问题挺难复现的. 
使用场景:
入口服务: 注册nacos, 监听配置变化, 启动HTTP转发服务.
api服务: 注册nacos, 监听配置变化,启动api服务
请求到入口服务器,通过配置(缓存到内存,配置变化后更新)里面获取URL对应的服务名字, 使用SelectOneHealthyInstance找到对应的实例, 然后HTTP转发到实例.

**Comment by sanxun0325** [comment]
@xiaoshanlin000 你这个场景，配置修改的频繁么？

**Comment by xiaoshanlin000** [comment]
配置就服务启动的时候更新的, 测试途中没有修改配置.

**Comment by sanxun0325** [comment]
暂时无法复现，已沟通，先将issues关闭。
