### ISSUE TITLE
ConfigParam.Content 字符串中带有 & 无法推送到 nacos

### ISSUE THREAD

**Issue by gitligl** [nacos-group/nacos-sdk-go#119]
在 PublishConfig 的时候，字符串中带有 & 的怎么处理呢？& 字符串后面的内容全部被丢弃了

**Comment by mark4z** [comment]
@i will fix it @

**Comment by sanxun0325** [comment]
@mark4z Contributions are welcomed

**Comment by sanxun0325** [comment]
@gitligl 由于调用nacos server openapi 配置内容是通过http params传递的，所以你可以对&做一些编码处理， 当读取配置内容时做解码。

**Comment by gitligl** [comment]
> @gitligl 由于调用nacos server openapi 配置内容是通过http params传递的，所以你可以对&做一些编码处理， 当读取配置内容时做解码。
实现方式是与python-sdk不同啊，python的可以推上去…
