### ISSUE TITLE
After the configuration is removed, Listen continually returns the previous value

### ISSUE THREAD

**Issue by mahuaibo** [nacos-group/nacos-sdk-go#12]
It might have something to do with this（https://github.com/nacos-group/nacos-sdk-go/issues/9）

```
https://nacos.io/en-us/docs/open-api.html
Listen for configurations
Description
This API is used to listen for configurations in Nacos to capture configuration changes. In case of any configuration changes, you can use the Get Configurations API to obtain the latest value of the configuration and dynamically refresh the local cache.

A listener is registered using an asynchronous servlet. The nature of registering a listener is to compare the configuration value and the MD5 value of it with that of the backend. If the values differ, the inconsistent configuration is returned immediately. Otherwise, an empty string is returned after 30 seconds.
```

```
success, _ := client.PublishConfig(vo.ConfigParam{
		DataId:  "com.hello",
		Group:   "marx",
		Content: "hello world",
	})
	fmt.Println("Publish Content: ", "hello world, result", success)
	time.Sleep(10 * time.Second)

	success, _ = client.PublishConfig(vo.ConfigParam{
		DataId:  "com.hello",
		Group:   "marx",
		Content: "hello ma",
	})
	fmt.Println("Publish Content: ", "hello ma, result", success)
	time.Sleep(10 * time.Second)

	success, _ = client.PublishConfig(vo.ConfigParam{
		DataId:  "com.hello",
		Group:   "marx",
		Content: "hello max",
	})
	fmt.Println("Publish Content: ", "hello marx, result", success)
	time.Sleep(10 * time.Second)

	success, _ = client.DeleteConfig(vo.ConfigParam{
		DataId: "com.hello",
		Group:  "marx",
	})
	fmt.Println("Delete Content: ", "hello marx, result", success)

	time.Sleep(2 * time.Minute)
```
out:
2019/07/02 14:44:03 [INFO] logDir:<data/nacos/log>   cacheDir:</private/var/folders/w4/d_d_m03523j12lnn4ypdq90m0000gp/T/cache>
Publish Content:  hello world, result true
group:marx, dataId:com.hello, data:hello world
Publish Content:  hello ma, result true
group:marx, dataId:com.hello, data:hello ma
Publish Content:  hello marx, result true
group:marx, dataId:com.hello, data:hello max
Delete Content:  hello marx, result true
group:marx, dataId:com.hello, data:hello max
group:marx, dataId:com.hello, data:hello max
group:marx, dataId:com.hello, data:hello max
group:marx, dataId:com.hello, data:hello max
... ...
group:marx, dataId:com.hello, data:hello max
... ...

**Comment by IanCao** [comment]
could u provider ur dingding ID, i add u to get more info to solve those issues

**Comment by mahuaibo** [comment]
dingding ID: mahuaibo

**Comment by mahuaibo** [comment]
> could u provider ur dingding ID, i add u to get more info to solve those issues

dingding ID: mahuaibo

**Comment by zscboy** [comment]
@IanCao 这个问题改了没，master上还存在这个问题

**Comment by lzp0412** [comment]
@zscboy 你这边遇到的问题是，config被删除后仍然会推送变化？我用上面的代码跑一下，没发现这个问题。你这边能给出复现的例子吗？如果方便，可以加入23191211这个钉钉群，详细聊下。

**Comment by zscboy** [comment]
谢谢哈，现在没问题了，是1.2.1客户端md5和服务器md5不匹配导致的
