### ISSUE TITLE
如果我想指定一个服务注册 该怎么写配置文件

### ISSUE THREAD

**Issue by milerL** [nacos-group/nacos-sdk-go#124]
例如 nacos 的 dev命名空间里有个 user-test 服务
该服务有多个server端
例如 UserService、UserGroupService

然后client端  我想向 user-test这个服务 的其中的UserService 注册

我该怎么写配置文件
我看了一下好像没有 能指定服务名的参数

**Comment by milerL** [comment]
因为java的 springcloud dubbo
配置
spring:
   application:
       name: "user-test"

这样就可以做到，所以我比较好奇 go的该怎么配置

**Comment by sanxun0325** [comment]
不太懂你的问题，你可以参考服务注册相关demo  https://github.com/nacos-group/nacos-sdk-go/blob/master/example/service/main.go
通过 vo.RegisterInstanceParam的ServiceName设置服务名

**Comment by milerL** [comment]
就是说  java 提供方 springboot 向nacos注册时 通过配置文件可以修改服务名 
spring:
  application:
    # 服务名
    name: service-provider
这样 服务名就变成了 service-provider 

go 版本的 是如何修改服务名的？
