### ISSUE TITLE
nacos 服务名相关问题

### ISSUE THREAD

**Issue by milerL** [nacos-group/nacos-sdk-go#134]
我是go client端
对方是 java server端 是spring cloud

对方向nacos注册服务 并修改注册的服务名为 userProviders
在nacos页面中展示出来的服务名也就是 userProviders

但是我只接触过
providers:com.test.module.service.UserService:1.0.0
这种

如果服务名只是userProviders
我该怎么配置？
serviceName 也改成 userProviders吗？

**Comment by sanxun0325** [comment]
@milerL 是的，serviceName=userProviders

**Comment by milerL** [comment]
> @milerL是的，serviceName = userProviders
serviceName = userProviders 
这不是说明起的 消费者名字是 userProviders吗

我的意思是 对方是服务提供方  在nacos里服务名叫做 userProviders  
我该怎么配置  才能让我的消费者服务 在nacos里能找到 userProviders服务提供方

**Comment by sanxun0325** [comment]
@milerL 看一下example ,这里面有很清楚的样例。https://github.com/nacos-group/nacos-sdk-go/blob/master/example/service/service_client_example.go
```
	//SelectAllInstance
	//ClusterName=DEFAULT
	ExampleServiceClient_SelectAllInstances(client, vo.SelectAllInstancesParam{
		ServiceName: "demo.go",
		GroupName:   "group-a",
	})

	//SelectInstances only return the instances of healthy=${HealthyOnly},enable=true and weight>0
	//ClusterName=DEFAULT,GroupName=DEFAULT_GROUP
	ExampleServiceClient_SelectInstances(client, vo.SelectInstancesParam{
		ServiceName: "demo.go",
	})

	//SelectOneHealthyInstance return one instance by WRR strategy for load balance
	//And the instance should be health=true,enable=true and weight>0
	//ClusterName=DEFAULT,GroupName=DEFAULT_GROUP
	ExampleServiceClient_SelectOneHealthyInstance(client, vo.SelectOneHealthInstanceParam{
		ServiceName: "demo.go",
	})
```
