### ISSUE TITLE
自己新建的用户无法监听配置文件的改变,提示没有权限

### ISSUE THREAD

**Issue by siyue8899** [nacos-group/nacos-sdk-go#135]
```
result:<{"timestamp":"2020-10-12T09:57:02.151+0000","status":403,"error":"Forbidden","message":"authorization failed!","path":"/nacos/v1/cs/configs/listener"}
```

用超级管理员 nacos 来登录就可以监听到命名空间 test 配置的改变,自己新建的命名空间test 和用户 test 无法监听,但是可以创建和查询.
请问这是什么原因

再次测试之后 给 test 绑定的新角色 TEST_ADMIN 赋予 public 资源的读写权限就能监听到配置的改变,这是为什么呢......我test 用户对应的 test 命名空间 权限已经给了为什么还要 public ?

**Comment by sanxun0325** [comment]
@siyue8899 你是不是创建configclient的namespaceId 填错了，我使用example的代码测试你说的场景是好用的。

**Comment by siyue8899** [comment]
> @siyue8899 你是不是创建configclient的namespaceId 填错了，我使用example的代码测试你说的场景是好用的。

nacos1.3.2
require github.com/nacos-group/nacos-sdk-go v1.0.0

没错啊....如果错了我肯定不能创建配置啊....

创建一个命名空间 test
创建一个用户 test
创建一个角色 TEST_ADMIN 绑定 test 用户
角色 TEST_ADMIN 和 test 资源绑定,动作是读写
然后开启鉴权
填的是 test 的账号和密码
可以读写配置,但是无法 ListenConfig 返回403

**Comment by sanxun0325** [comment]
@siyue8899 问题已修复.

**Comment by siyue8899** [comment]
> @siyue8899 发现问题了，已提交pr，等待merge.

OK麻烦了

**Comment by sanxun0325** [comment]
@siyue8899 代码已合并到master，可以再试试最新的代码。有问题随时交流，钉钉群：23191211
