### ISSUE TITLE
ConfigItem unmarshal error

### ISSUE THREAD

**Issue by yexm** [nacos-group/nacos-sdk-go#143]
用SearchConfig 方法时报错：json: cannot unmarshal number into Go struct field ConfigItem.PageItems.Id of type string
调试发现时 model/config.go内ConfigItem结构体定义有问题。
version =1.0.1的定义
type ConfigItem struct {
	Id      string `param:"id"`
	DataId  string `param:"dataId"`
	Group   string `param:"group"`
	Content string `param:"content"`
	Md5     string `param:"md5"`
	Tenant  string `param:"tenant"`
	Appname string `param:"appname"`
}

实际应该是
type ConfigItem struct {
	Id      int `param:"id"`
	DataId  string `param:"dataId"`
	Group   string `param:"group"`
	Content string `param:"content"`
	Md5     string `param:"md5"`
	Tenant  string `param:"tenant"`
	Appname string `param:"appname"`
}

Id      string `param:"id"`  => Id      int `param:"id"`

**Comment by sanxun0325** [comment]
@yexm nacos server版本是多少？你可以尝试用example 测试一下https://github.com/nacos-group/nacos-sdk-go/blob/master/example/config/main.go

**Comment by yexm** [comment]
> @yexm nacos server版本是多少？你可以尝试用example 测试一下https://github.com/nacos-group/nacos-sdk-go/blob/master/example/config/main.go

用的是阿里云的微服务引擎MSE中的配置中心，nacos server版本1.2.1 需要升级么

**Comment by sanxun0325** [comment]
@yexm 是的需要升级一下nacos server， nacos server返回的ConfigItem.PageItems.id是字符类型。
