### ISSUE TITLE
Create multiple clients and the logger will be overwritten

### ISSUE THREAD

**Issue by sanxun0325** [nacos-group/nacos-sdk-go#148]
Create multiple clients, each with a different logging parameter, and the global logger takes effect with the last client setting。

We need to discuss whether it is better to set up the global logger only once, or if each client has a different logger？

```
func InitLogger(config Config) (err error) {
	logLevel := getLogLevel(config.Level)
	encoder := getEncoder()
	writer, err := getWriter(config.OutputPath, config.RotationTime, config.MaxAge)
	if err != nil {
		return
	}
	core := zapcore.NewCore(zapcore.NewConsoleEncoder(encoder), zapcore.AddSync(writer), logLevel)
	zaplogger := zap.New(core, zap.AddCallerSkip(1))
	logger = &NacosLogger{zaplogger.Sugar()}
	return
}
```

**Comment by mark4z** [comment]
I read the source code of Slf4j(java), i found that logger will be created for every object. so, maybe we could create logger for every one.

**Comment by sanxun0325** [comment]
In the nacos java client, multiple clients share a single logback instance.it is singleton, global configuration.

**Comment by Anthony-Dong** [comment]
以 -race 编译启动，每次都会出现大量的 data race 现象，希望官方解决一下

**Comment by sanxun0325** [comment]
> 以 -race 编译启动，每次都会出现大量的 data race 现象，希望官方解决一下

嗯嗯，目前来看主要是日志这里会出现data race， 会解决掉的。

**Comment by legenove** [comment]
> > 以 -race 编译启动，每次都会出现大量的 data race 现象，希望官方解决一下
> 
> 嗯嗯，目前来看主要是日志这里会出现data race， 会解决掉的。

一个是data race问题，另一个是用户自主设置logger的时候，会在新建client时候覆盖.

**Comment by legenove** [comment]
优先解决data race问题。
其他问题解决方案：
1、全局单例：考虑到历史用户使用，如果修改会影响历史用户使用，建议后续大版本改动。
2、每个client持有logger，改动太大，建议后续大版本改动。
