### ISSUE TITLE
生成读取配置的url时，未使用传入的scheme配置，导致无法使用https协议

### ISSUE THREAD

**Issue by xiangbodengdd01** [nacos-group/nacos-sdk-go#149]
生成读取配置的url时，未使用传入的scheme配置，导致无法使用https协议
https://github.com/nacos-group/nacos-sdk-go/blob/fb45465888781748568f906fe55137f718a31af7/common/nacos_server/nacos_server.go#L315

**Comment by mark4z** [comment]
i will fix it.
