### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by ainilili** [nacos-group/nacos-sdk-go#155]
## 客户端sdk和服务端版本:
- nacos-sdk-go: v1.0.1
- nacos-server: v1.4.0

## 报错信息：
```
api</v1/ns/instance>,method:<POST>, params:<{"clusterName":"DEFAULT","enable":"true","ephemeral":"true","groupName":"DEFAULT_GROUP","healthy":"true","ip":"172.18.0.9","metadata":"{}","namespaceId":"public","port":"15001","serviceName":"DEFAULT_GROUP@@usercenter","weight":"1"}>, call domain error:<Post "http://nacos-crm2.bjx.cloud:8848/nacos/v1/ns/instance": context deadline exceeded (Client.Timeout exceeded while awaiting headers)> , result:<>
```

## 更多描述：
golang服务和nacos server均使用docker部署在同一个机器上，验证nacos server是没问题的，golang服务在docker容器内部连接nacos server一直报如上错误，但是在容器外直接通过go run起来是正常的，请问下导致这个问题的可能原因有哪些？

补充：根据报错信息里的接口和参数，使用curl在golang 服务docker容器内是能够返回OK的
2020-12-02补充：代码里将nacos-crm2.bjx.cloud换成具体的ip就没问题的，但是很奇怪，容器里命名是可以ping通的，为什么代码里配置域名就不行

**Comment by sanxun0325** [comment]
@ainilili 使用域名端口号应该不是8848了。可以检查一下代码中的端口设置。

**Comment by ainilili** [comment]
好的，我再排查下！

**Comment by ainilili** [comment]
找到问题了，由于域名配在了宿主机的/etc/hosts中，而cgo未开启时，放到容器内运行则会出现无法解析域名，所以导致time out.
