### ISSUE TITLE
v1.0.3会报错，读不到配置

### ISSUE THREAD

**Issue by hsxy0820** [nacos-group/nacos-sdk-go#169]
代码如下(隐藏了部分认证信息),同样的代码，当把go.mod里引用1.0.3的时候就取不到配置(require github.com/nacos-group/nacos-sdk-go v1.0.3), 1.0.1版本就能够读到配置， 是不是哪里的用法不对，麻烦帮忙看一下

`package main

import (
	"fmt"
	"github.com/nacos-group/nacos-sdk-go/clients"
	"github.com/nacos-group/nacos-sdk-go/common/constant"
	"github.com/nacos-group/nacos-sdk-go/vo"
)

func main() {
	// 从控制台命名空间管理的"命名空间详情"中拷贝 End Point、命名空间 ID
	var endpoint = "addr-hz-internal.edas.aliyun.com"
	var namespaceId = "xxxxxxx-xxxx-xxxx-xxxx-xxxxxx"

	// 推荐使用 RAM 用户的 accessKey、secretKey
	var accessKey = "Ssdfsadafdsf"
	var secretKey = "XXXXXXXXXXXXXX"

	clientConfig := constant.ClientConfig{
		//
		Endpoint:       endpoint + ":8080",
		NamespaceId:    namespaceId,
		AccessKey:      accessKey,
		SecretKey:      secretKey,
		TimeoutMs:      5 * 1000,
	}

	configClient, err := clients.CreateConfigClient(map[string]interface{}{
		"clientConfig": clientConfig,
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	var dataId = "test"
	var group = "test"

	// 获取配置
	content, err := configClient.GetConfig(vo.ConfigParam{
		DataId: dataId,
		Group:  group})

	if err!=nil{
		fmt.Println("get config error ",err)
	}

	fmt.Println("Get config：" + content)
}`

**Comment by sanxun0325** [comment]
@hsxy0820 endpoint 里配置的ip列表，可以提供一下。

**Comment by hsxy0820** [comment]
应该怎么找这个ip列表，我是在阿里云控制台上看的，没找到ip
![image](https://user-images.githubusercontent.com/38240102/103045210-93c20180-45be-11eb-8b31-419ca8ae323d.png)

**Comment by sanxun0325** [comment]
错误信息提供一下吧。 然后请求一下 http://addr-hz-internal.edas.aliyun.com:8080/nacos/serverlist 看看是否可以得到结果。

**Comment by hsxy0820** [comment]
错误信息
-------------------------------------------
2020/12/24 08:59:17 [INFO] logDir:<C:\Users\admin\AppData\Local\Temp\log>   cacheDir:<C:\Users\admin\AppData\Local\Temp\cache>
get config error  read config from both server and cache fail
Get config：
----------------------------------------------
请求后ip地址如下
100.100.45.175
100.100.45.174
100.100.45.190
100.100.17.91
100.100.19.55

**Comment by sanxun0325** [comment]
> 错误信息
> `2020/12/24 08:59:17 [INFO] logDir:<C:\Users\admin\AppData\Local\Temp\log> cacheDir:<C:\Users\admin\AppData\Local\Temp\cache> get config error read config from both server and cache fail Get config：`
> 请求后ip地址如下
> 100.100.45.175
> 100.100.45.174
> 100.100.45.190
> 100.100.17.91
> 100.100.19.55

endpoint 没有问题，日志信息提供的再全一些吧。主要看一下和nacos 交互时返回的错误。类似于这样的`api<%s>,method:<%s>, params:<%s>, call domain error:<%+v> , result:<%s>`

**Comment by hsxy0820** [comment]
看看这些信息够不够？

2020-12-24T14:43:53.248+0800	[34mINFO[0m	http nacos server list: <>
2020-12-24T14:43:53.248+0800	[31mERROR[0m	[ERROR] api</v1/cs/configs>,method:<GET>, params:<{"dataId":"ops-test","group":"ops-test","tenant":"b91788bd-57bc-4da5-9d53-d042e5cd7728"}>, call domain error:<parse "://100.100.45.174:8848/nacos/v1/cs/configs?group=ops-test&tenant=b91788bd-57bc-4da5-9d53-d042e5cd7728&dataId=ops-test": missing protocol scheme> , result:<>

**Comment by sanxun0325** [comment]
@hsxy0820 这个错误是因为1.0.3版本上使用endpoint 有一个bug，默认没有设置scheme。  最新的master已经修复了,这是相关PR：https://github.com/nacos-group/nacos-sdk-go/pull/163/files

**Comment by hsxy0820** [comment]
能不能把tag 1.0.3也更新下，这样我在go mod直接引用1.0.3就没有问题了。

**Comment by sanxun0325** [comment]
> 能不能把tag 1.0.3也更新下，这样我在go mod直接引用1.0.3就没有问题了。

release是有计划的哈，这个会在1.0.4 版本中包含，预计下个月发布

**Comment by coolyrat** [comment]
@sanxun0325 如果可以，希望这种情况还是走hotfix版本。
之前的项目一直用这个库连阿里云acm。今天有个新项目使用，折腾了一个多小时才发现是库的问题。对比了之前代码和阿里云的样例代码都没有问题才会想是库的问题，毕竟之前都没有问题~

试了一下，1.0.2（11月30日的tag）也是同样的问题。这个问题影响还是比较大，毕竟大家默认都是直接拉取最新的tag。

**Comment by sanxun0325** [comment]
> @sanxun0325 如果可以，希望这种情况还是走hotfix版本。
> 之前的项目一直用这个库连阿里云acm。今天有个新项目使用，折腾了一个多小时才发现是库的问题。对比了之前代码和阿里云的样例代码都没有问题才会想是库的问题，毕竟之前都没有问题~
> 
> 试了一下，1.0.2（11月30日的tag）也是同样的问题。这个问题影响还是比较大，毕竟大家默认都是直接拉取最新的tag。

因为这个已经关闭了，建议可以创建一个单独的issue，详细描述下问题的相关信息。
