### ISSUE TITLE
When multiple versions are running test at the same time, the test fails due to conflicts in file config_client_test.go 

### ISSUE THREAD

**Issue by legenove** [nacos-group/nacos-sdk-go#172]
When multiple versions are running at the same time, the test fails due to conflicts in file config_client_test.go 

在ci自动化测试的时候。
config_client_test.go 中的测试用例，如果在go13 和go14 同时跑到该条用例的时候，会出现偶现的 测试不通过。
因为集群是同一个，dataid也是同一个，如果同时跑到这一条用例，会2个进程同时修改集群的dataid的value，会导致某个环境下预期的结果不同。导致测试用例失败。

**Comment by liangyuanpeng** [comment]
这种情况似乎应该串行 而不是同一时间执行? 亦或者是不同go版本跑不同的集群数据CI?
