### ISSUE TITLE
使用sdk获取ACM加密配置时，发现不支持kms-128加密的配置，而监听解密配置时，有配置变更没有自动解密，返回的是密文

### ISSUE THREAD

**Issue by lidaoyang** [nacos-group/nacos-sdk-go#174]
使用sdk获取ACM加密配置时，发现不支持kms-128加密的配置，而监听解密配置时，有配置变更没有自动解密，返回的是密文
查看sdk发现应该是没有对content进行解密client.decrypt(param.DataId, content)
![image](https://user-images.githubusercontent.com/26211950/103523737-4ba4b800-4eb7-11eb-9e88-7dfbadeb21c4.png)

**Comment by yearm** [comment]
自己写一个
https://github.com/yearm/nacos-sdk-go/commit/580c57ef66cfc526fdc2a18677ee4671c9379ef6

**Comment by lidaoyang** [comment]
> 自己写一个 [yearm@580c57e](https://github.com/yearm/nacos-sdk-go/commit/580c57ef66cfc526fdc2a18677ee4671c9379ef6)

没有合并到主分支吗？

**Comment by yearm** [comment]
> > 自己写一个 [yearm@580c57e](https://github.com/yearm/nacos-sdk-go/commit/580c57ef66cfc526fdc2a18677ee4671c9379ef6)
> 
> 没有合并到主分支吗？

没提pr，fork下来改的，有时间再提个pr

**Comment by sanxun0325** [comment]
阿里云相关问题建议到阿里云咨询
