### ISSUE TITLE
通过ECS实例RAM角色访问ACM的参数设置问题

### ISSUE THREAD

**Issue by ye-ds** [nacos-group/nacos-sdk-go#177]
你好,我是用[通过ECS实例RAM角色访问ACM](https://www.alibabacloud.com/help/zh/doc-detail/72013.htm?spm=a2c63.p38356.b99.29.36eb64a6jJ0XVQ)做访问控制的,

文档中的[步骤三：将RAM角色名称告知ACM SDK并访问配置],在`go sdk`中,要怎么设置`ECS实例的RAM角色名称`这个参数啊?

**Comment by sanxun0325** [comment]
@ye-ds 目前go-sdk 暂不支持这种方式，如果感兴趣，欢迎参与贡献

**Comment by dskyu** [comment]
顶起来

**Comment by sanxun0325** [comment]
@yearm 可以提交pr 贡献你改动的代码～
