### ISSUE TITLE
v1.0.2和v1.0.3不能读取配置，希望尽快有hotfix版本

### ISSUE THREAD

**Issue by coolyrat** [nacos-group/nacos-sdk-go#179]
目前v1.0.2和v1.0.3不能正常拉取配置，根据#169 描述，这个bug已经修复，希望可以尽快提供一个hotfix版本。因为大家新项目都会拉取最新tag，一时间会很迷惑是哪里出了问题。

**Comment by sanxun0325** [comment]
@coolyrat 我们会在近期release 一个1.0.4, 如果感兴趣 也可以确认相关pr是否可以解决你的问题。 https://github.com/nacos-group/nacos-sdk-go/pull/163/files

**Comment by coolyrat** [comment]
是这个问题，加了schema。

**Comment by chester-go** [comment]
什么时候release 1.0.4？ @sanxun0325

**Comment by coolyrat** [comment]
其实这种严重的bug，是不是不应该跟正常版本走？毕竟大家用这个库拉配置，连server都连不上了。还等了1个多月。。。

**Comment by sanxun0325** [comment]
> 其实这种严重的bug，是不是不应该跟正常版本走？毕竟大家用这个库拉配置，连server都连不上了。还等了1个多月。。。

你们是使用endpoint的方式，endpoint里面可以在ip前直接配置schema。有试过这样吗？

**Comment by sanxun0325** [comment]
> 什么时候release 1.0.4？ @sanxun0325

这周应该可以release的。

**Comment by coolyrat** [comment]
> > 其实这种严重的bug，是不是不应该跟正常版本走？毕竟大家用这个库拉配置，连server都连不上了。还等了1个多月。。。
> 
> 你们是使用endpoint的方式，endpoint里面可以在ip前直接配置schema。有试过这样吗？

我试试，理论上是可以这样。因为之前版本加schema是不行的

**Comment by sanxun0325** [comment]
v1.0.4 https://github.com/nacos-group/nacos-sdk-go/releases/tag/v1.0.4 发布了，有问题欢迎随时交流。
