### ISSUE TITLE
config client init method has goroutine leak

### ISSUE THREAD

**Issue by ZoeShaw101** [nacos-group/nacos-sdk-go#190]
![截屏2021-02-23 下午2 27 26](https://user-images.githubusercontent.com/13792102/108809211-50e2d100-75e3-11eb-86dc-9f4682ab6c1c.png)

In /github.com/nacos-group/nacos-sdk-go/clients/config_client/config_client.go, starts a goroutine in init method, this leads to our CI Test job fail. 

It seems the goroutine does not exit when our TestSuite done. 

Our testing framework extends  `testify` testing framework, and  we check goroutine leak per 50ms until no unexpect goroutine exist in 1s during each TestSuite.

**Comment by sanxun0325** [comment]
Starting goroutines in init is not a problem, you can try to find the reason from TestProvisionTabletStore func

**Comment by ZoeShaw101** [comment]
> Starting goroutines in init is not a problem, you can try to find the reason from TestProvisionTabletStore func

Just wonder if there's go routine leak during program running.  If just in CI test case above, we can ignore the leak to pass CI Jobs.

**Comment by sanxun0325** [comment]
> > Starting goroutines in init is not a problem, you can try to find the reason from TestProvisionTabletStore func
> 
> Just wonder if there's go routine leak during program running. If just in CI test case above, we can ignore the leak to pass CI Jobs.

I think in init func only a goroutine is enabled to implement the timing task，It closes along with the test so it doesn't leak out
