### ISSUE TITLE
可以出一份详尽的教程或配置文档

### ISSUE THREAD

**Issue by aabc1123** [nacos-group/nacos-sdk-go#206]
作为初学者刚把go web 最基础的知识点学完，现在引入注册中心的时候选择了nacos，使用 nacos-sdk-go 过程中参考样例配置，暂时困惑比较多，希望有更多的学习资料提供，这也能帮助nacos 在 go 服务中的地位和影响力，谢谢！

**Comment by sanxun0325** [comment]
README.md中的说明以及example 包下的demo样例都可以作为参考的资料进行入手。也欢迎加入钉钉群23191211，一起交流
