### ISSUE TITLE
create a client with username and password, we got faild~

### ISSUE THREAD

**Issue by legenove** [nacos-group/nacos-sdk-go#210]
If Nacos server is down.
we create a client without username and password, we return success.
but we creating a client with username and password, we got fail.

**Comment by sanxun0325** [comment]
Login occurs when the client is created, an error is returned when the server is down.  https://github.com/nacos-group/nacos-sdk-go/blob/c9952e6dde21b58812a72c02cd79cb243a02f7a7/common/nacos_server/nacos_server.go#L72

**Comment by legenove** [comment]
是的，这里做了一次兼容，你看看是否合理？

**Comment by sanxun0325** [comment]
@legenove thank you for contribution
