### ISSUE TITLE
nacos 版本问题  

### ISSUE THREAD

**Issue by cwww3** [nacos-group/nacos-sdk-go#218]
场景  nacos从本地服务迁移到acm上

v1.0.1    调用 nacos.GetConfig  正常获取

v1.0.2    调用 nacos.GetConfig  获取失败 报错 read config from both server and cache fail
log日志      get config from server error:parse "://139.196.135.144:8848/nacos/v1/cs/configs?group=group&tenant=00566c00-b74e-42ec-a922-35e4abb3980f&dataId=dataId": missing protocol scheme 

升级skd到v1.0.7 回复正常

**Comment by sanxun0325** [comment]
@cwww3 是的，1.0.2版本这个scheme处理有点问题，后来版本修复了
