### ISSUE TITLE
The Client Address is in ipv6 address.

### ISSUE THREAD

**Issue by brotherlu-xcq** [nacos-group/nacos-sdk-go#220]
The Client Address is in ipv6 address.
![image](https://user-images.githubusercontent.com/25661357/116032336-10aad800-a692-11eb-8f95-6b60994b6830.png)

**Comment by Penglq** [comment]
nacos server read http header, X-Forwarded-For or X-Real-IP, but when the client requests it, it does not carry it. You can look at the intermediate forwarding link. Where is the header added
