### ISSUE TITLE
请问nacos-sdk-go 2.0版本，目前支持长链接功能吗

### ISSUE THREAD

**Issue by MrZhangisGood** [nacos-group/nacos-sdk-go#223]
您好，Nacos管理人员：

请问，目前nacos-sdk-go 2.0分支，支持长链接功能吗。我在本地环境测试的结论是：目前2.0版本的go sdk，还不支持长链接功能，go应用结束后，nacos注册中心依然有节点数据。

注册节点，调用的代码如下：
```
	namingClient.RegisterInstance(vo.RegisterInstanceParam{
		Ip:          "127.0.0.1",
		Port:        809,
		ServiceName: "demo.go",
		Weight:      10,
		Enable:      true,
		Healthy:     true,
		Ephemeral:   true,
		Metadata:    map[string]string{"idc":"shanghai"},
		ClusterName: "DEFAULT",
		GroupName:   "DEFAULT_GROUP",
	})
```

**Comment by sanxun0325** [comment]
@MrZhangisGood 2.0.0分支还在开发中，这是2.0.0的pr。https://github.com/nacos-group/nacos-sdk-go/pull/203

**Comment by MrZhangisGood** [comment]
> @MrZhangisGood 2.0.0分支还在开发中，这是2.0.0的pr。#203

嗯，好的

**Comment by MrZhangisGood** [comment]
> @MrZhangisGood 2.0.0分支还在开发中，这是2.0.0的pr。#203

您好，请问目前，2.0.0分支有个大概的完成时间节点吗

**Comment by sanxun0325** [comment]
> > @MrZhangisGood 2.0.0分支还在开发中，这是2.0.0的pr。#203
> 
> 您好，请问目前，2.0.0分支有个大概的完成时间节点吗

预计5月份会有一个版本发布。毕竟是开源项目，需要社区多多贡献力量。如果感兴趣，欢迎贡献。

**Comment by MrZhangisGood** [comment]
> > > @MrZhangisGood 2.0.0分支还在开发中，这是2.0.0的pr。#203
> > 
> > 
> > 您好，请问目前，2.0.0分支有个大概的完成时间节点吗
> 
> 预计5月份会有一个版本发布。毕竟是开源项目，需要社区多多贡献力量。如果感兴趣，欢迎贡献。

嗯，好的。

**Comment by sanxun0325** [comment]
> > > > @MrZhangisGood 2.0.0分支还在开发中，这是2.0.0的pr。#203
> > > 
> > > 
> > > 您好，请问目前，2.0.0分支有个大概的完成时间节点吗
> > 
> > 
> > 预计5月份会有一个版本发布。毕竟是开源项目，需要社区多多贡献力量。如果感兴趣，欢迎贡献。
> 
> 嗯，好的。
已经发布了2.0.0-Alpha版本.
