### ISSUE TITLE
GRPC requests to build the accessKey/secretKey

### ISSUE THREAD

**Issue by sanxun0325** [nacos-group/nacos-sdk-go#230]
naming_grpc_proxy 中的requestToServer 构建ak/sk，参考java client AbstractNamingClientProxy.getSpasHeaders()

**Comment by GMoliang** [comment]
hello,截止目前nacos-go-sdk是不是还未支持与server端的grpc通信

**Comment by sanxun0325** [comment]
> 

sdk 的 grpc 21年就支持了～ 现在的2.0.0正式版也发布了，可以使用
