### ISSUE TITLE
fix readme or code for typo？

### ISSUE THREAD

**Issue by xushuhui** [nacos-group/nacos-sdk-go#237]
### Is your feature request related to a problem?

I found a typo in struct name . I want fix it. 
this struct is reference in a few go file and readme as example.
 It is a trouble to  old version user when this  repo upgrade if I fix it in code.
But it not solve real problem If I only  fix it  in  readme.
how I do it?  thanks

**Comment by sanxun0325** [comment]
Reference contribution manual: https://github.com/nacos-group/nacos-sdk-go/blob/master/CONTRIBUTING.md
