### ISSUE TITLE
a panic i found

### ISSUE THREAD

**Issue by lppklm** [nacos-group/nacos-sdk-go#239]
hello, 

there is a panic!

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9ed8f]

goroutine 10626879 [running]:
api/vendor/github.com/nacos-group/nacos-sdk-go/clients/naming_client.(*PushReceiver).startServer.func1(0x0, 0xc003e379e0)
    src/api/vendor/github.com/nacos-group/nacos-sdk-go/clients/naming_client/push_receiver.go:94 +0x2f
created by api/vendor/github.com/nacos-group/nacos-sdk-go/clients/naming_client.(*PushReceiver).startServer
    src/api/vendor/github.com/nacos-group/nacos-sdk-go/clients/naming_client/push_receiver.go:93 +0x27d

i found a question in this function below:

```
func (us *PushReceiver) startServer() {
    var conn *net.UDPConn

    for i := 0; i < 3; i++ {
        r := rand.New(rand.NewSource(time.Now().UnixNano()))
        port := r.Intn(1000) + 54951
        us.port = port
        conn1, ok := us.tryListen()

        if ok {
            conn = conn1
            logger.Infof("udp server start, port: " + strconv.Itoa(port))
            break
        }

        if !ok && i == 2 {
            logger.Errorf("failed to start udp server after trying 3 times.")
        }
    }

    go func() {
        defer conn.Close()
        for {
            us.handleClient(conn)
        }
    }()
}
```

after retry 3 times,if the "conn" isn`t  assign a value, the panic will happened immediately~

i think the sdk can make it more friendly,  and you? thanks!

**Comment by sanxun0325** [comment]
Yes, it can be optimized here.

after retry 3 times,if the "conn" isn`t assign a value,conn will be judged in handClient func , if it is nil then TryListen

**Comment by himsngh** [comment]
Hey I would like to work on this issue.

**Comment by sanxun0325** [comment]
@himsngh Looking forward to your PR

**Comment by himsngh** [comment]
@sanxun0325 I did handle the panic as you mentioned although I have one minor doubt as to why we are doing it in the handle client instead we should have returned the function from the start-server only if it is nil even after the 3 iterations.
PS: I am new to all this so please do bear with me and do let me know if there is something else to this I will make the changes.

**Comment by sanxun0325** [comment]
> @sanxun0325 I did handle the panic as you mentioned although I have one minor doubt as to why we are doing it in the handle client instead we should have returned the function from the start-server only if it is nil even after the 3 iterations.
> PS: I am new to all this so please do bear with me and do let me know if there is something else to this I will make the changes.

Creating a udp connection is not a necessary step, it is mainly used to receive the service data sent by the server。
