### ISSUE TITLE
Configure saving snapshot

### ISSUE THREAD

**Issue by sanxun0325** [nacos-group/nacos-sdk-go#240]
对比golang当前cache.WriteConfigToFile和java 的LocalConfigInfoProcessor.saveSnapshot 区别，分析是否有必要按照java client LocalConfigInfoProcessor.saveSnapshot存配置的快照

**Comment by li-xiao-shuang** [comment]
这个需不需要搞下？

**Comment by sanxun0325** [comment]
@li-xiao-shuang 有空 可以帮忙搞一下
