### ISSUE TITLE
Nacos 2.x SubscribeService.Vaild always false

### ISSUE THREAD

**Issue by win5do** [nacos-group/nacos-sdk-go#244]
https://github.com/nacos-group/nacos-sdk-go/blob/84fad6d923d74b0f10eb890ba6d61f43ccd67140/clients/naming_client/subscribe_callback.go#L81

`$.hosts[*].valid` field is gone  in response of Nacos 2.x API `http://127.0.0.1:8848/nacos/v1/ns/instance/list`.

**Comment by sanxun0325** [comment]
reference：https://github.com/nacos-group/nacos-sdk-go/issues/219
