### ISSUE TITLE
初始化客户端的配置参数为什么是指针

### ISSUE THREAD

**Issue by zhaoyunxing92** [nacos-group/nacos-sdk-go#252]
> 文件路径 ：vo/client_param.go

```go
type NacosClientParam struct {
	ClientConfig  *constant.ClientConfig  // optional
	ServerConfigs []constant.ServerConfig // optional
}
```
`ClientConfig`这里使用指针的好处是什么

**Comment by sanxun0325** [comment]
@zhaoyunxing92 Pointers are needed when creating with optional parameters.

**Comment by zhaoyunxing92** [comment]
> @zhaoyunxing92 Pointers are needed when creating with optional parameters.

但是我感觉这里不应该使用指针，optional这样写也是不对的吧

**Comment by sanxun0325** [comment]
> > @zhaoyunxing92 Pointers are needed when creating with optional parameters.
> 
> 但是我感觉这里不应该使用指针，optional这样写也是不对的吧

可以说一下你的想法，也欢迎提交pr.

**Comment by zhaoyunxing92** [comment]
> > > @zhaoyunxing92 Pointers are needed when creating with optional parameters.
> > 
> > 
> > 但是我感觉这里不应该使用指针，optional这样写也是不对的吧
> 
> 可以说一下你的想法，也欢迎提交pr.

抱歉是我理解错了，我看了几个仓库好像都是指针传的
