### ISSUE TITLE
client loadbalance problem

### ISSUE THREAD

**Issue by Lovnx** [nacos-group/nacos-sdk-go#257]
my golang project1,2 integrated nacos-sdk-go. if project 1 request 2, how to handle loadbalance like Ribbon?

**Comment by sanxun0325** [comment]
SelectoneHealthyInstance func is load-balanced against the weight ratio columns.
referenced:https://github.com/nacos-group/nacos-sdk-go/blob/56cb33f77aaeaa4ce2fbab54f461785feaaecb28/example/service/main.go#L217

**Comment by sanxun0325** [comment]
You can get all instances with selectallInstances func and then do whatever you want with the full list of instances

**Comment by Lovnx** [comment]
ok

**Comment by Lovnx** [comment]
ok
