### ISSUE TITLE
nacos日志是否可以添加一个参数来配置？

### ISSUE THREAD

**Issue by x-lambda** [nacos-group/nacos-sdk-go#260]
nacos sdk会调用标准库输出一行日志，但是是非json格式的，
```golang
log.Printf("[INFO] logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
```
这会导致我们的日志收集报错，是否可以添加一个配置参数来选择是否打印这行日志呢？

**Comment by sanxun0325** [comment]
> nacos sdk会调用标准库输出一行日志，但是是非json格式的，
> 
> ```go
> log.Printf("[INFO] logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
> ```
> 
> 这会导致我们的日志收集报错，是否可以添加一个配置参数来选择是否打印这行日志呢？

这里可以修改一下，改成使用`logger.Info`

**Comment by x-lambda** [comment]
请问大概什么时候会变更呢？

**Comment by x-lambda** [comment]
> > nacos sdk会调用标准库输出一行日志，但是是非json格式的，
> > ```go
> > log.Printf("[INFO] logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这会导致我们的日志收集报错，是否可以添加一个配置参数来选择是否打印这行日志呢？
> 
> 这里可以修改一下，改成使用`logger.Info`

请问大概什么时候会变更呢？

**Comment by sanxun0325** [comment]
> > > nacos sdk会调用标准库输出一行日志，但是是非json格式的，
> > > ```go
> > > log.Printf("[INFO] logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这会导致我们的日志收集报错，是否可以添加一个配置参数来选择是否打印这行日志呢？
> > 
> > 
> > 这里可以修改一下，改成使用`logger.Info`
> 
> 请问大概什么时候会变更呢？

如果你感兴趣，可以来一个pr.

**Comment by x-lambda** [comment]
> > > > nacos sdk会调用标准库输出一行日志，但是是非json格式的，
> > > > ```go
> > > > log.Printf("[INFO] logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这会导致我们的日志收集报错，是否可以添加一个配置参数来选择是否打印这行日志呢？
> > > 
> > > 
> > > 这里可以修改一下，改成使用`logger.Info`
> > 
> > 
> > 请问大概什么时候会变更呢？
> 
> 如果你感兴趣，可以来一个pr.

Hi，pr来了！ https://github.com/nacos-group/nacos-sdk-go/pull/261
