### ISSUE TITLE
v2.0.0-Alpha.1 version cannot download mod

### ISSUE THREAD

**Issue by MrZhangisGood** [nacos-group/nacos-sdk-go#264]
When i use " github.com/nacos-group/nacos-sdk-go v2.0.0-Alpha.1 ",cannot download mod.
Error message is ### **“ require github.com/nacos-group/nacos-sdk-go: version "v2.0.0-Alpha.1" invalid: should be v0 or v1, not v2”**

And then, i use " github.com/nacos-group/nacos-sdk-go/v2 v2.0.0-Alpha.1 ", also cannot download mod too.
Error message is ### **“ go: github.com/nacos-group/nacos-sdk-go/v2@v2.0.0-Alpha.1: go.mod has non-.../v2 module path "github.com/nacos-group/nacos-sdk-go" (and .../v2/go.mod does not exist) at revision v2.0.0-Alpha.1 ”**

**Comment by sanxun0325** [comment]
go.mod  try to use `github.com/nacos-group/nacos-sdk-go/v2 v2.0.0-Alpha.1`

**Comment by MrZhangisGood** [comment]
> republish v2.0.0-Alpha.1 , go.mod try to use `github.com/nacos-group/nacos-sdk-go/v2 v2.0.0-Alpha.1`

ok, thanks
