### ISSUE TITLE
有时出现网络错误后nacos会打印大量日志，能不能限制单位时间内日志的输出数量？

### ISSUE THREAD

**Issue by Gitforxuyang** [nacos-group/nacos-sdk-go#266]
最近我们线上出现了某些节点出现网络故障，然后nacos打印了大量的日志（十几个G），看了一下，nacos现在默认使用的是zap，但是没有用它的采集率配置（Sampling），是不是可以开放更多的配置？
1. 可以配置zap的Sampling？
2.可以设置输出结果到标准输出流？对于我们使用阿里云的日志服务来说，更期望能直接输出到标准输出流。

**Comment by sanxun0325** [comment]
1：Sampling 需要支持一下,如果你感兴趣欢迎提交pr.
2：希望使用标准库的log打印日志嘛？为什么?

**Comment by Gitforxuyang** [comment]
1. 好的，我改天提交一下PR。
2. 我们直接在阿里云的K8s里，直接通过标准输出流把日志输出到阿里云的日志服务里了，这样也方便后续排查。  不然专门为了nacos的日志，我们还得弄一套日志采集方案。

**Comment by sanxun0325** [comment]
> 1. 好的，我改天提交一下PR。
> 2. 我们直接在阿里云的K8s里，直接通过标准输出流把日志输出到阿里云的日志服务里了，这样也方便后续排查。  不然专门为了nacos的日志，我们还得弄一套日志采集方案。

第二点是想说 如果使用标准输出流可以不用写到日志文件里，而是直接采集到阿里云的日志服务里面吗？

**Comment by sanxun0325** [comment]
@Gitforxuyang  有什么进展么？
