### ISSUE TITLE
Service struct has no Metadata information

### ISSUE THREAD

**Issue by Zhaoyu1123** [nacos-group/nacos-sdk-go#268]
type Service struct {
	        CacheMillis              uint64     `json:"cacheMillis"`
	        Hosts                    []Instance `json:"hosts"`
	        Checksum                 string     `json:"checksum"`
	        LastRefTime              uint64     `json:"lastRefTime"`
	        Clusters                 string     `json:"clusters"`
	        Name                     string     `json:"name"`
	        GroupName                string     `json:"groupName"`
	        Valid                    bool       `json:"valid"`
	        AllIPs                   bool       `json:"allIPs"`
	        ReachProtectionThreshold bool       `json:"reachProtectionThreshold"`
        }

The web background has, but the interface does not return metadata.

**Comment by sanxun0325** [comment]
Service metadata is server  and console specific ,is not available to clients.
