### ISSUE TITLE
v2.0.0-Alpha cocurrent map panic

### ISSUE THREAD

**Issue by Kotodian** [nacos-group/nacos-sdk-go#273]
![image](https://user-images.githubusercontent.com/22030659/123216460-26a31080-d4fc-11eb-8b9d-19968fac9804.png)

**Comment by sanxun0325** [comment]
reference:https://github.com/nacos-group/nacos-sdk-go/issues/267 or provide the code to create the client

**Comment by Kotodian** [comment]
> reference:#267 or provide the code to create the client

我知道问题了,想问下这个版本和nacos的版本有关吗,我用v2的创建服务没有报错 但是nacos上没看到服务

**Comment by sanxun0325** [comment]
> > reference:#267 or provide the code to create the client
> 
> 我知道问题了,想问下这个版本和nacos的版本有关吗,我用v2的创建服务没有报错 但是nacos上没看到服务

nacos server是2.x版本就可以
