### ISSUE TITLE
why not add cmap into go mod

### ISSUE THREAD

**Issue by DFSOrange** [nacos-group/nacos-sdk-go#275]
I can see the source code exactly same with the opensource code.
Maybe come discuss why not add it into go mod.

https://github.com/orcaman/concurrent-map/blob/master/concurrent_map.go

https://github.com/nacos-group/nacos-sdk-go/blob/master/clients/cache/concurrent_map.go

**Comment by sanxun0325** [comment]
Because at first wanted to make some modifications,subsequent can be introduced through dependencies.
