### ISSUE TITLE
Naming client still updates the configuration after service unsubscribe

### ISSUE THREAD

**Issue by Sharember** [nacos-group/nacos-sdk-go#280]
when invoke unsubscribe(service)， HostReactor.asyncUpdateService still send request for this service。

maybe need do `sc.hostReactor.cleanMap(service)`  in unsubscribe func.

cleanMap func will remove the key of service from hostReactor.serviceInfoMap

**Comment by sanxun0325** [comment]
Are you using the 1.x version? this will happen in 1.x version. this does not affect functionality,  will only result in a small waste of resources.because the server has unsubscribed.

**Comment by Sharember** [comment]
yes ,I use 1.x.   2.0 version fix this issue？

In fact, I will unsub a service and then re-sub it again. Because of this problem, the sub will not execute callback. like:

```go
client.sub(service)

client.unSub(service)
client.sub(service)
```

The second sub doesn't execute callback.


set notLoadCacheAtStart=true solves this problem, but it doesn't feel like the most logical way...

**Comment by sanxun0325** [comment]
@Sharember What is the version of SDK used? everything is fine when I use 1.0.8
