### ISSUE TITLE
服务关闭后，还能在控制台的服务列表中看到

### ISSUE THREAD

**Issue by Adler15** [nacos-group/nacos-sdk-go#281]
写的测试代码测试将服务注册到nacos中，demo能注册到nacos里，但是当后台终止服务后，并不会像Java那样自己就消失在了服务列表中，只是那条服务的背景色变成了橘黄色，健康实例数变为0，请问需要手动的去取消注册后才会消失在服务列表里？现在是手动去删除的

**Comment by sanxun0325** [comment]
@Adler15 你用的是哪个版本SDK和Server，我测试过没有问题 server端删除服务是有延迟的。当服务里没有实例时nacos server端的定时任务(EmptyServiceAutoClean)会清理掉服务列表。

**Comment by Adler15** [comment]
SDK 是v1.0.8的，server我目前测试用到两个版本1.4.0和1.4.2的，当前1.4.2是我关闭服务后可以自动删除，1.4.0的就不行，问题就是问题描述那样，当前我们主流用的还是1.4.0的，所以找个算是版本的问题吗？

**Comment by sanxun0325** [comment]
> SDK 是v1.0.8的，server我目前测试用到两个版本1.4.0和1.4.2的，当前1.4.2是我关闭服务后可以自动删除，1.4.0的就不行，问题就是问题描述那样，当前我们主流用的还是1.4.0的，所以找个算是版本的问题吗？

我使用1.4.0 以及1.4.1都没有发现这样的问题, 建议在nacos server 中观察`services are automatically cleaned`这样的日志，看看是否有异常。
