### ISSUE TITLE
找不到v1.61.18版本的 alibaba-cloud-sdk-go

### ISSUE THREAD

**Issue by 471207225** [nacos-group/nacos-sdk-go#284]
github.com/aliyun/alibaba-cloud-sdk-go/go.mod at revision v1.61.18: unknown revision v1.61.18

**Comment by sanxun0325** [comment]
alibaba-cloud-sdk-go v1.61.18 existing. https://github.com/aliyun/alibaba-cloud-sdk-go/releases/tag/v1.61.18 
You can try checking your own GOPROXY
