### ISSUE TITLE
some question for namingClient asyncUpdateService

### ISSUE THREAD

**Issue by twogoods** [nacos-group/nacos-sdk-go#285]
1. call api `intances/list` per second will be make pressure for nacos server ？

2. in `ProcessServiceJson` function 
```
	if !ok || ok && !reflect.DeepEqual(service.Hosts, oldDomain.(model.Service).Hosts) {
		if !ok {
			logger.Info("service not found in cache " + cacheKey)
		} else {
			logger.Info("service key:%s was updated to:%s", cacheKey, util.ToJsonString(service))
		}
		cache.WriteServicesToFile(*service, hr.cacheDir)
		hr.subCallback.ServiceChanged(service)
	}
```
the `service.Hosts`  instance is same , but array order is not same , so the DeepEqual is false；I have 3 nodes in nacos cluster, api call will be loadbalancered by nginx

**Comment by sanxun0325** [comment]
1. call api intances/list per second will be make pressure for nacos server ？
The impact can be ignored because the instance needs to be monitored for updates and the server is the query cache efficiency is higher

2. the service.Hosts instance is same , but array order is not same , so the DeepEqual is false；I have 3 nodes in nacos cluster, api call will be loadbalancered by nginx
The order of instances is guaranteed by the nacos server, and the order of instances of each node is not different

**Comment by twogoods** [comment]
> 1. call api intances/list per second will be make pressure for nacos server ？
>    _The impact can be ignored because the instance needs to be monitored for updates and the server is the query cache efficiency is higher_
> 2. the service.Hosts instance is same , but array order is not same , so the DeepEqual is false；I have 3 nodes in nacos cluster, api _call will be loadbalancered by nginx
>    The order of instances is guaranteed by the nacos server, and the order of instances of each node is not different_

@sanxun0325  if the order of instances of each node is not different, when `namingClient.Subscribe`,I  will always get changedEvent，it's incorrect

**Comment by sanxun0325** [comment]
> > 1. call api intances/list per second will be make pressure for nacos server ？
> >    _The impact can be ignored because the instance needs to be monitored for updates and the server is the query cache efficiency is higher_
> > 2. the service.Hosts instance is same , but array order is not same , so the DeepEqual is false；I have 3 nodes in nacos cluster, api _call will be loadbalancered by nginx
> >    The order of instances is guaranteed by the nacos server, and the order of instances of each node is not different_
> 
> @sanxun0325 if the order of instances of each node is not different, when `namingClient.Subscribe`,I will always get changedEvent，it's incorrect

For robustness, the client should deprecate reflect.deepequal.
It will be optimized later, and contributions are welcome if you are interested
