### ISSUE TITLE
Add function UpdateInstance()

### ISSUE THREAD

**Issue by yangyanqing** [nacos-group/nacos-sdk-go#286]
Instance had RegisterInstance() and DeregisterInstance() currently. 
Function UpdateInstance() is useful for updating workload information, so client could choose the right instance.

**Comment by sanxun0325** [comment]
> Instance had RegisterInstance() and DeregisterInstance() currently.
> Function UpdateInstance() is useful for updating workload information, so client could choose the right instance.

RegisterInstance() can be registered instance and updated instance.

**Comment by yangyanqing** [comment]
> > Instance had RegisterInstance() and DeregisterInstance() currently.
> > Function UpdateInstance() is useful for updating workload information, so client could choose the right instance.
> 
> RegisterInstance() can be registered instance and updated instance.

https://nacos.io/zh-cn/docs/open-api.html#2.3
OpenAPI provide another interface `[PUT] /nacos/v1/ns/instance`, so I think it should be call while updating meta.

**Comment by sanxun0325** [comment]
@yangyanqing Openapi is suitable for users who don't use sdk.
Although it is not necessary to implement updateInstance in the sdk, adding it will make it clear to the user which function to use。

**Comment by yangyanqing** [comment]
> > Instance had RegisterInstance() and DeregisterInstance() currently.
> > Function UpdateInstance() is useful for updating workload information, so client could choose the right instance.
> 
> RegisterInstance() can be registered instance and updated instance.

Go routine for heart beat would be created for each calling RegisterInstance(), and would never be release until DeregisterInstance().

```go
func (sc *NamingClient) RegisterInstance(param vo.RegisterInstanceParam) (bool, error) {
   |-- sc.beatReactor.AddBeatInfo(util.GetGroupName(param.ServiceName, param.GroupName), beatInfo)
             |-- go br.sendInstanceBeat(k, &beatInfo)
```

I'm refacting the code as your wish.
