### ISSUE TITLE
添加心跳的表现与Java SDK不符

### ISSUE THREAD

**Issue by Xezeloh** [nacos-group/nacos-sdk-go#292]
https://github.com/nacos-group/nacos-sdk-go/blob/8e5874fb9faa6f64b1e0b74d7d1d133de8cde6e3/clients/naming_client/beat_reactor.go#L61
添加心跳任务时，表现与Java SDK不一致，不会将之前已经放到map里的key相同的心跳任务停掉，而是直接覆盖了原来的键值对。假如重复调用，则会启动多个心跳协程，带来性能压力。建议set到map里之前先检测一下当前key有没有注册心跳任务。

**Comment by sanxun0325** [comment]
参考：https://github.com/nacos-group/nacos-sdk-go/pull/288
后续会重新提交pr.
