### ISSUE TITLE
windows 平台使用做为服务发现时出错

### ISSUE THREAD

**Issue by saperliu** [nacos-group/nacos-sdk-go#293]
使用场景：

go-micro（v3）  +  nacos-plugins 

nacos 版本: nacos-server-2.0.1

服务注册成功，客户端在调用服务时报错，如下：

**failed to rotate: failed to create new symlink: symlink E:\testProject\test-client\log\nacos-sdk.log-202108130800 
E:\testProject\test-client\log\nacos-sdk.log-202108130800_symlink: Access is denied.**

详细错误显示 ：
`failed to rotate: failed to create new symlink: symlink E:\testProject\test-client\log\nacos-sdk.log-202108130800 
E:\testProject\test-client\log\nacos-sdk.log-202108130800_symlink: Access is denied.
c:/go/src/runtime/panic.go:969 +0x1c7 github.com/nacos-group/nacos-sdk-go/v2/clients/cache.ConcurrentMap.GetShard(...)
E:/work/dis/GOPATH/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.0-!alpha.1/clients/cache/concurrent_map.go:57  github.com/nacos-group/nacos-sdk-go/v2/clients/cache.ConcurrentMap.Get(0x0, 0x0, 0x0, 0xc0002b0f40, 0x1a, 0x1a4418a, 0xb, 0xc0002b0f40)
E:/work/dis/GOPATH/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.0-!alpha.1/clients/cache/concurrent_map.go:111 +0x165 github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_cache.(*ServiceInfoHolder).GetServiceInfo(0xc000300a20, 0x1a4418a, 0xb, 0x1a46500, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.0-!alpha.1/clients/naming_client/naming_cache/service_info_holder.go:99 +0xfa\ngithub.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*NamingClient).GetService(0xc0001bbb90, 0x0, 0x0, 0x0, 0x1a4418a, 0xb, 0x1a46500, 0xd, 0x0, 0x0, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.0-!alpha.1/clients/naming_client/naming_client.go:135 +0x12b github.com/asim/go-micro/plugins/registry/nacos/v3.(*nacosRegistry).GetService(0xc0004de3c0, 0x1a4418a, 0xb, 0x0, 0x0, 0x0, 0xc0002b1560, 0x7ae630, 0xc00029e5b0, 0xd0, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/plugins/registry/nacos/v3@v3.0.0-20210812172626-c7195aae9817/nacos.go:198 +0x149\ngithub.com/asim/go-micro/v3/registry/cache.(*cache).get.func1.1(0xd0, 0xd0, 0x193314e0108, 0xc00029e5b0)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/registry/cache/cache.go:139 +0x62\ngolang.org/x/sync/singleflight.(*Group).doCall.func2(0xc0002b158e, 0xc0004bdb00, 0xc0002b1698)\n\tE:/work/dis/GOPATH/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:193 +0x69\ngolang.org/x/sync/singleflight.(*Group).doCall(0xc000350968, 0xc0004bdb00, 0x1a4418a, 0xb, 0xc0002b1698)
E:/work/dis/GOPATH/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:195 +0xc5\ngolang.org/x/sync/singleflight.(*Group).Do(0xc000350968, 0x1a4418a, 0xb, 0xc0002b1698, 0xbc2411932b7cb5ab, 0xc0002b16b8, 0x7b562b, 0xa0, 0x19101c0)\n\tE:/work/dis/GOPATH/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108 +0x154\ngithub.com/asim/go-micro/v3/registry/cache.(*cache).get.func1(0x1a4418a, 0xb, 0x25a2040, 0x0, 0x0, 0x0, 0x0, 0xc0002b1700, 0x7ae630, 0xc0003d59b0)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/registry/cache/cache.go:138 +0xa5\ngithub.com/asim/go-micro/v3/registry/cache.(*cache).get(0xc000350900, 0x1a4418a, 0xb, 0x7aefff, 0x30, 0x18ea520, 0x899501, 0xc0003d59b0)\n\tE:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/registry/cache/cache.go:190 +0x2e2\ngithub.com/asim/go-micro/v3/registry/cache.(*cache).GetService(0xc000350900, 0x1a4418a, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaaa9b4ac61958b94, 0x3434393264303431, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/registry/cache/cache.go:436 +0x4a\ngithub.com/asim/go-micro/v3/selector.(*registrySelector).Select(0xc000067840, 0x1a4418a, 0xb, 0x0, 0x0, 0x0, 0xb, 0x0, 0x0)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/selector/default.go:52 +0x102\ngithub.com/asim/go-micro/v3/client.(*rpcClient).next(0xc00004f680, 0x1c22780, 0xc0001bce10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1aa49c8, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/client/rpc_client.go:349 +0x344\ngithub.com/asim/go-micro/v3/client.(*rpcClient).Call(0xc00004f680, 0x1c184e0, 0xc0003d5980, 0x1c22780, 0xc0001bce10, 0x198dbc0, 0xc0004bdaa0, 0x0, 0x0, 0x0, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/client/rpc_client.go:367 +0x1a5\ngithub.com/asim/go-micro/v3/util/wrapper.(*fromServiceWrapper).Call(0xc000005920, 0x1c184e0, 0xc0003d5920, 0x1c22780, 0xc0001bce10, 0x198dbc0, 0xc0004bdaa0, 0x0, 0x0, 0x0, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/util/wrapper/wrapper.go:33 +0xdb\ngithub.com/asim/go-micro/v3/util/wrapper.(*traceWrapper).Call(0xc0003d4c90, 0x1c18460, 0xc00003a030, 0x1c22780, 0xc0001bce10, 0x198dbc0, 0xc0004bdaa0, 0x0, 0x0, 0x0, ...)
E:/work/dis/GOPATH/pkg/mod/github.com/asim/go-micro/v3@v3.5.2/util/wrapper/wrapper.go:83 +0x1cb\nperfect-rule-server/input/gorpc/proto.(*ruleService).AddRule(0xc000005dc0, 0x1c18460, 0xc00003a030, 0xc000077ee0, 0x0, 0x0, 0x0, 0x149d186, 0x2549a20, 0x1a22640)
E:/work/dis/GOPATH/src/perfect-server/input/gorpc/proto/rule.pb.micro.go:58 +0x13f\nmain.mainRun()`

**Comment by saperliu** [comment]
使用最新的2.0.0的分支版本是可以的。

**Comment by sanxun0325** [comment]
在windows下应该是日志路径设置的问题，换一个路径使用反斜线\试试
