### ISSUE TITLE
Go Micro Nacos v3插件调用sdk的GetService panic

### ISSUE THREAD

**Issue by Jekinnnnnn** [nacos-group/nacos-sdk-go#299]
服务器Nacos版本2.0.3 Go客户端用的是Go Micro 3.6里面的Nacos插件(v3)
客户端已经成功连接上服务器，但是通过GetService获取特定服务节点信息为空，在控制台中节点健康状态正常，也没有触发保护
我们调试了一下插件见图1，发现在调用sdk的GetService出现panic，调用前有日志输出，调用后没有日志输出见图2，报错堆栈见图3
![图片](https://user-images.githubusercontent.com/11225229/131835308-cdc20327-6757-4b77-aa30-f3f29a2fe4f3.png)
![图片](https://user-images.githubusercontent.com/11225229/131835330-7b97c3ff-f0f4-4483-adf1-573714c27a0e.png)
![图片](https://user-images.githubusercontent.com/11225229/131936472-6c7c0329-3d98-450f-a46a-32093b8bcd13.png)

测试代码如下：
```golang
package main

import (
	"github.com/asim/go-micro/plugins/registry/nacos/v3"
	"github.com/asim/go-micro/v3"
)

func main() {
	registry := nacos.NewRegistry(nacos.WithAddress([]string{"addr"}))
	service := micro.NewService(
		micro.Name("go.micro.nacos.demo"),
		micro.Registry(registry),
	)
	fmt.Println(registry.GetService("my.micro.service"))
	service.Run()
}
```

**Comment by Jekinnnnnn** [comment]
原因是go micro当前上用sdk版本的代码有bug，在NewRegistry的时候如果notLoadCacheAtStart为false的时候，serviceInfoHolder.ServiceInfoMap没有初始化，在下面loadCacheFromDisk时对缓存赋值的时候越界了，当前master的代码已经修复了这个问题，我们现在先手动将notLoadCacheAtStart设置true规避这个问题；如果插件更新了sdk版本代码，麻烦回复一下，同时Close这个Issue
```golang
func NewServiceInfoHolder(namespace, cacheDir string, updateCacheWhenEmpty, notLoadCacheAtStart bool) *ServiceInfoHolder {
	cacheDir = cacheDir + string(os.PathSeparator) + "naming" + string(os.PathSeparator) + namespace
	serviceInfoHolder := &ServiceInfoHolder{
		updateCacheWhenEmpty: updateCacheWhenEmpty,
		notLoadCacheAtStart:  notLoadCacheAtStart,
		cacheDir:             cacheDir,
		subCallback:          NewSubscribeCallback(),
		UpdateTimeMap:        cache.NewConcurrentMap(),
	}
	if notLoadCacheAtStart {
		serviceInfoHolder.ServiceInfoMap = cache.NewConcurrentMap()
	} else {
		serviceInfoHolder.loadCacheFromDisk()
	}
	return serviceInfoHolder
}
```

**Comment by sanxun0325** [comment]
2.0.0近期也会发一个版本，升级完成后也会同步更新go-micro的依赖版本

**Comment by harry0703** [comment]
请问当前如何在代码里面处理？
怎么把该参数 notLoadCacheAtStart 传递进去呢？

registry := nacos.NewRegistry(nacos.WithAddress([]string{"addr"}))
	service := micro.NewService(
		micro.Name("go.micro.nacos.demo"),
		micro.Registry(registry),
	)

**Comment by Jekinnnnnn** [comment]
> 
> 
> 请问当前如何在代码里面处理？
> 怎么把该参数 notLoadCacheAtStart 传递进去呢？
> 
> ```go
> registry := nacos.NewRegistry(nacos.WithAddress([]string{"addr"}))
> 	service := micro.NewService(
> 		micro.Name("go.micro.nacos.demo"),
> 		micro.Registry(registry),
> 	)
> ```

```golang
	addr := []string{"192.168.1.1:110"}
	clientConfig := *constant.NewClientConfig(
		constant.WithNotLoadCacheAtStart(true),
	)
	registry := nacos.NewRegistry(nacos.WithClientConfig(clientConfig),nacos.WithAddress(addr))
```
大概是这样，具体可以看看sdk的README，写的很清楚，插件那边没有什么说明，根据说明的配置来初始化就好了，配置中心的设置也类似
