### ISSUE TITLE
getConfig  不要输出没用的info日志

### ISSUE THREAD

**Issue by otokaze** [nacos-group/nacos-sdk-go#306]
position: clients/nacos_client/nacos_client.go:87
content: logger.Infof("logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)

可以删掉或者选择性输出么？

**Comment by otokaze** [comment]
@lzp0412

**Comment by sanxun0325** [comment]
@otokaze 这个日志是为了提示日志和缓存的目录，特别是当用户没有设置日志和缓存目录的时候 可以知道默认存储在哪里。

**Comment by tigerxuz** [comment]
> @otokaze 这个日志是为了提示日志和缓存的目录，特别是当用户没有设置日志和缓存目录的时候 可以知道默认存储在哪里。

一般也不需要知道默认路径，需要的话可以查源码

**Comment by sanxun0325** [comment]
> > @otokaze 这个日志是为了提示日志和缓存的目录，特别是当用户没有设置日志和缓存目录的时候 可以知道默认存储在哪里。
> 
> 一般也不需要知道默认路径，需要的话可以查源码

查看源码也许不太友好。
