### ISSUE TITLE
go能否通过feign方式调用java服务

### ISSUE THREAD

**Issue by fafeidou** [nacos-group/nacos-sdk-go#31]

**Comment by excepts** [comment]
想地美，同问~。而且它只提供了API， 你得写模块在 合适的地方 进行 注册， 移除，renew等等操作，不像SpringCloud是有相应的Listenor做相应的事。
不过， golang 和 nodejs应该很好搞这个，我在弄，可以一起搞一套出来；
我还想问，咋3个月无更新了。

**Comment by Deathef** [comment]
为什么看起来没人维护的样子

**Comment by liangyuanpeng** [comment]
我想这个问题应该是问 通过HTTP的方式调用JAVA服务？ 毕竟Go是没有feign这个东西的.

**Comment by Deathef** [comment]
> 我想这个问题应该是问 通过HTTP的方式调用JAVA服务？ 毕竟Go是没有feign这个东西的.

我们可以基于HTTP REST API的方式去封装一个Feign工具，可以参考Spring Cloud Feign
