### ISSUE TITLE
2.0.0 日志报错：failed to read config cache file:./Nacos/cache//config/config.yaml@@dev@@3092ec95-173d-4be3-88d0-ae5439bb5b40,err:open ./Nacos/cache//config/config.yaml@@dev@@3092ec95-173d-4be3-88d0-ae5439bb5b40: no such file or directory 

### ISSUE THREAD

**Issue by LeonScript17** [nacos-group/nacos-sdk-go#316]
**查看log发现报错：**
failed to read config cache file:./Nacos/cache//config/config.yaml@@dev@@3092ec95-173d-4be3-88d0-ae5439bb5b40,err:open ./Nacos/cache//config/config.yaml@@dev@@3092ec95-173d-4be3-88d0-ae5439bb5b40: no such file or directory 

**在ClientConfig种配置了：**
LogDir:              "./Nacos/log/",
CacheDir:         "./Nacos/cache/",

**但是发现config_client.go中有一段代码：**
config.configCacheDir = clientConfig.CacheDir + string(os.PathSeparator) + "config"

这不就导致文件查找不到了吗？？？请大佬帮忙解惑

**Comment by sanxun0325** [comment]
设置log和cache路径时，最后不要加/就可以了

**Comment by LeonScript17** [comment]
> 设置log和cache路径时，最后不要加/就可以了

老哥你好，谢谢你的回复
去除/的话，报错还是在的～问题在于config_client.go文件中，会把我配置的CacheDir拼接上 “/config”，但是这个config文件夹并没有创建～所以导致报错了，为啥sdk中要拼接“/config”嘞？

**Comment by sanxun0325** [comment]
启动时 debug看一下logger.go文件中的InitNacosLogger func在getWriter中是否返回错误了。

**Comment by LeonScript17** [comment]
> 启动时 debug看一下logger.go文件中的InitNacosLogger func在getWriter中是否返回错误了。

你好，你说的方法并没有在启动时候报错，启动时候报错的是disk_cashe.go中ReadConfigFromFile方法中的ioutil.ReadFile(fileName)

**Comment by sanxun0325** [comment]
@LeonScript17 你这个是查询配置时出的错误吧，在初始化客户端的时候 NotLoadCacheAtStart没有设置为true,则代表如果远程读取不到配置则会使用本地缓存的配置。 但是你本地还没有自己去创建对应的文件夹报错是正常的。

**Comment by LeonScript17** [comment]
> @LeonScript17 你这个是查询配置时出的错误吧，在初始化客户端的时候 NotLoadCacheAtStart没有设置为true,则代表如果远程读取不到配置则会使用本地缓存的配置。 但是你本地还没有自己去创建对应的文件夹报错是正常的。

您好，谢谢回复～

**Comment by dcsunny** [comment]
应该是下面这段少了cache.WriteConfigToFile(cacheKey, client.configCacheDir, "")
```
func (client *ConfigClient) getConfigInner(param vo.ConfigParam) (content string, err error) {
	if len(param.DataId) <= 0 {
		err = errors.New("[client.GetConfig] param.dataId can not be empty")
		return "", err
	}
	if len(param.Group) <= 0 {
		param.Group = constant.DEFAULT_GROUP
	}
	//todo 优先使用本地配置
	//todo 获取容灾配置的 EncryptedDataKey LocalEncryptedDataKeyProcessor.getEncryptDataKeyFailover
	clientConfig, _ := client.GetClientConfig()
	cacheKey := util.GetConfigCacheKey(param.DataId, param.Group, clientConfig.NamespaceId)
	response, err := client.configProxy.queryConfig(param.DataId, param.Group, clientConfig.NamespaceId,
		clientConfig.TimeoutMs, false, client)
	if err != nil {
		logger.Infof("get config from server error:%+v ", err)
		content, err = cache.ReadConfigFromFile(cacheKey, client.configCacheDir)
		if err != nil {
			logger.Errorf("get config from cache  error:%+v ", err)
			return "", errors.New("read config from both server and cache fail")
		}
		return content, nil
	}
	return response.Content, nil
}
```

**Comment by Piwriw** [comment]
v2.2.2 还是出现了这个问题，
```go
	sc := []constant.ServerConfig{
		{
			IpAddr: global.NacosConf.Host,
			Port:   global.NacosConf.Port,
		},
	}

	cc := constant.ClientConfig{
		NamespaceId:         global.NacosConf.NameSpace, // 如果需要支持多namespace，我们可以场景多个client,它们有不同的NamespaceId
		TimeoutMs:           5000,
		NotLoadCacheAtStart: true,
		LogDir:              "./tmp/nacos/log",
		CacheDir:            "./tmp/nacos/cache",
		//RotateTime:          "1h",
		//MaxAge:              3,
		LogLevel: "debug",
	}

	configClient, err := clients.CreateConfigClient(map[string]interface{}{
		"serverConfigs": sc,
		"clientConfig":  cc,
	})
	if err != nil {
		return err
	}

	content, err := configClient.GetConfig(vo.ConfigParam{
		DataId: global.NacosConf.DataID,
		Group:  global.NacosConf.Group})
```

**Comment by EricJSanchez** [comment]
同遇此问题，2.2.2版本
get nacos err:read config from both server and cache fail, err=failed to read config cache file:/tmp/nacos/cache/config/go-notify.toml@@go-notify@@, cacheDir:/tmp/nacos/cache/config, err:open /tmp/nacos/cache/config/go-notify.toml@@go-notify@@: no such file or directory
<img width="1166" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/42372350/5687d1d7-7a5d-427b-a26d-91898ee0b596">
目录确保存在

**Comment by EricJSanchez** [comment]
2.2.2版本，同遇此问题
read config from both server and cache fail, err=failed to read config cache file:/tmp/nacos/cache/config/go-notify.toml@@go-notify@@, cacheDir:/tmp/nacos/cache/config, err:open /tmp/nacos/cache/config/go-notify.toml@@go-notify@@: no such file or directory ，dataId=go-notify.toml, group=go-notify, namespaceId=
<img width="1119" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/42372350/5c321f72-dfcf-4264-a092-d0f0e89c1d16">
目录确认是存在的，然后降了版本到1.0.9同样的代码不报错了。还是老老实实用老的吧

**Comment by lhf-k** [comment]
这个问题我也遇到了，debug了一下发现在调用 configClient.GetConfig方法的时候会访问grpc服务，nacos2添加了grpc通信方式，所以需要把grpc的端口也打开，但是搞不懂为啥用http协议不开grpc端口就会报错

**Comment by zyiuh** [comment]
需要开启grpc端口，默认是9848

**Comment by INGg** [comment]
docker启动的时候记得把9848和9849暴露出来，也就是把grpc打开
`docker run --name nacos-standalone -e MODE=standalone -e JVM_XMS=512m -e JVM_XMX=512m -e JVM_XMN=256m -p 8848:8848 -p 9848:9848 -p 9849:9849 -d nacos/nacos-server:latest --restart=always`

![image](https://github.com/nacos-group/nacos-sdk-go/assets/41495415/38f3c921-a03c-4453-b7ad-fc401cffbed5)

**Comment by luduoxin** [comment]
> 需要开启grpc端口，默认是9848

正解，我也遇到了这个问题，放出 9848 端口后成功解决问题
