### ISSUE TITLE
新建naming client部分参数含义不明

### ISSUE THREAD

**Issue by shuzhongling** [nacos-group/nacos-sdk-go#318]
## 使用版本说明

>客户端使用nacos-sdk-go v2.0.0-Beta.1  服务端使用的最新的nacos 2.0.3

## 问题现象

- 构建naming client时，需要提供ServerConfig的信息，但是通过试验发现，schema和ContextPath部分可以随便填写，好像都能注册到nacos服务器上。这两个参数的作用在文档描述没找到。

```
type ServerConfig struct {
	Scheme      string //the nacos server scheme
	ContextPath string //the nacos server contextpath
	IpAddr      string //the nacos server address
	Port        uint64 //the nacos server port
}
```
 - 利用构造好的naming client，调用其subscribe方法时，能够成功。但是在nacos服务端的控制台中，查看某个服务的订阅者时，会打开一个列表，可以显示的订阅者的ip和客户端版本，但是列表中的应用名显示为`unknown`。而且即使在构造naming client时，在 `ClientConfig` 中设置 `AppName` 属性，在nacos的控制台中，订阅者的应用名依然显示为`unknown`。 设置`ClentConfig`中的`AppName`似乎对控制台无效。
 

> 一个小疑问：
nacos 2.0以后，增加了grpc方式，默认nacos-sdk-go是使用grpc和nacos服务端交互吗？没看到提供有选择的参数。nacos官网文档提到nacos 2.0.0以后grpc的端口号为9848/9849， 在使用nacos-sdk-go时，需要注意什么？还是不用设置，nacos-sdk-go会默认会把端口号+1000并使用grpc方式和服务端通信？ 这个没看到有文档介绍

**Comment by sanxun0325** [comment]
1:sdk在2.x版本中schema和ContextPath在endpoint获取server list时候会使用，后续增加一些说明。
2:订阅应用名显示unknown,目前2.x没有做这部分处理 后续迭代优化一下
3:默认sdk会把端口号+1000 和官网一样，所以没有文档介绍。
以上部分如果 有感兴趣的也欢迎贡献～
