### ISSUE TITLE
sdk使用访问自签证书时报 x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by fuhao009** [nacos-group/nacos-sdk-go#320]
报错提示这个,请问有啥办法吗
PublishConfig err:[client.PublishConfig] publish config failed:Post "https://x.x.x.x:443/nacos/v1/cs/configs": x509: certificate signed by unknown authority

**Comment by sanxun0325** [comment]
参考:https://github.com/alibaba/nacos/issues/6870
