### ISSUE TITLE
nacos-sdk-go v2.0 在服务端重启时，客户端不能感知并重新注册服务

### ISSUE THREAD

**Issue by shuzhongling** [nacos-group/nacos-sdk-go#325]
`client version` :  `nacos-sdk-go v2.0.0-Beta.1`
`nacos server version` :  `v2.0.3`

启动nacos server，以单机模式启动.  
```shell 
startup.cmd -m standalone
```

启动客户端可以正常注册服务到nacos 服务上，在控制台上可以看到注册服务。

这时关掉nacos server， 并重启。此时在nacos服务端控制台上，看不到刚注册的客户端服务。

此时nacos naming_client无任何接口可感知服务端重启了.

以前用过java 版本的nacos 客户端，当服务端重启后，java版本的服务会自动重新注册到nacos服务器上。

建议：
1、能否在naming_client增加一个感知接口的回调。
2、或者在naming_client内部感知到与服务端重连时自动重新注册本客户端已经注册过的服务。

**Comment by sanxun0325** [comment]
1.0的可以基于http心跳都是可以的，2.0java和go都是grpc长连接，应该都不支持的

**Comment by shuzhongling** [comment]
2.0中也有这个机制，目前的sdk中已经实现了。但是和服务器配合有点问题。
当nacos服务器刚启动时，服务器收到请求会返回3xx，sdk中，收到3xx的包，处理上有点问题。
1、健康检查时，认为健康检查失败。
2、新连接到nacos server时，会认为连接失败。
正是因为以上两个原因，导致当nacos服务器刚启动时，客户端就连接上，马上就失败了。
代码我已修正，我自己再审查一下，过两天提交一个pull request

**Comment by sanxun0325** [comment]
@shuzhongling 欢迎贡献，期待你的pr
