### ISSUE TITLE
这个支持nacos2的grpc吗

### ISSUE THREAD

**Issue by dcsunny** [nacos-group/nacos-sdk-go#326]
这个支持nacos2的grpc吗？ 
支持的话，需要怎么使用，是否有例子提供？
目前不支持的话，大概会在什么时候支持呢？

**Comment by sanxun0325** [comment]
支持的，使用https://github.com/nacos-group/nacos-sdk-go/releases/tag/v2.0.0-Beta.1，demo 参考example
