### ISSUE TITLE
我的服务在正常运行过程中，服务名称与分组名称位置调换

### ISSUE THREAD

**Issue by lizazacn** [nacos-group/nacos-sdk-go#335]
我的服务在正常运行过程中，服务名称与分组名称位置调换
例如：
服务名       分组名称
service1     Group1

变为

服务名       分组名称
Group1      service1

**Comment by sanxun0325** [comment]
请提供更多的信息，例如客户端版本，服务端版本，日志等

**Comment by lizazacn** [comment]
nacos服务端版本为2.0.3，客户端版本为v2.0.0-Beta.1

**Comment by li-xiao-shuang** [comment]
> nacos服务端版本为2.0.3，客户端版本为v2.0.0-Beta.1

可不可以提供一下复现的步骤 或者截图？  是通过接口获取服务信息的时候发现变更了嘛？

**Comment by sanxun0325** [comment]
maybe this PR will solve it:https://github.com/nacos-group/nacos-sdk-go/pull/336
