### ISSUE TITLE
请问我用了subscribe，为什么每次要10s左右才会更新注销的服务器

### ISSUE THREAD

**Issue by dcsunny** [nacos-group/nacos-sdk-go#337]
请问我用了subscribe，为什么每次要10s左右才会更新注销的服务
订阅是这样用的吧？
```

	err := r.client.Subscribe(&vo.SubscribeParam{
		ServiceName: serviceName,
		GroupName:   r.opts.group,
		Clusters:    []string{r.opts.clusterName},
		SubscribeCallback: func(services []model.SubscribeService, err error) {
			fmt.Println(services)
		},
	})
```
还有一个问题，订阅者列表为什么是空的呢？
我使用的阿里的mse的NACOS2.0.1版本,sdk是v1.0.9

**Comment by dcsunny** [comment]
![image](https://user-images.githubusercontent.com/14797525/143565586-f96ca4c0-1f35-42b3-b478-3ea8e163a885.png)

**Comment by sanxun0325** [comment]
@dcsunny 订阅者列表在社区版本的nacos server控制台 需要输入服务名称查询

不是每次10s左右会更新，日志打印的时间是证明在这个时间点服务端实例有变化。

注销的服务器是什么意思？下线实例，还是删除服务？

**Comment by dcsunny** [comment]
是这样的，我是在测试，服务端实例变化，他的响应，所以我将一个服务不停的注销，注册。观察另一个服务要多久才能发现这个的变化，目前测试是10s左右，就是不是我想象中的1s内响应。。。

**Comment by dcsunny** [comment]
这样就导致，我服务被注销了或者注册了，他可能不能及时发现吧？

**Comment by sanxun0325** [comment]
服务的注销和注册是什么操作？ 只有注册实例(RegisterInstance)和注销实例(DeregisterInstance)。  注册实例和注销实例是服务端通过udp进行推送的，也不会有10s的时长。 可以贴一下 你的代码

**Comment by dcsunny** [comment]
嗯嗯，我是注册实例RegisterInstance，和取消实例DeregisterInstance。 我用的是kratos库做的整个服务搭建。我说的注销和注册，就是将应用关闭，开启这样来回操作，看实例是否正常的注册，注销，以及被其他服务去发现。 在这个过程中我看nacos日志，看到比较久。 还有订阅列表是空的是正常的吗？

**Comment by sanxun0325** [comment]
> 

订阅列表不应该为空。
正常情况下：
![Uploading image.png…]()

**Comment by dcsunny** [comment]
我切换使用sdk 2.x版本确实能够即使响应了。 不过订阅列表还是空的。。。
