### ISSUE TITLE
怎么配置nacos服务健康检查？

### ISSUE THREAD

**Issue by daniuEvan** [nacos-group/nacos-sdk-go#354]
你好， 首先非常感谢！
我现在注册了一个服务之后，不知道从哪里配置这个服务的健康检查？我该怎么办呢？

**Comment by sanxun0325** [comment]
1: 1.x的客户端会主动发送心跳，2.x的客户端会用grpc长连接保持心跳。 这是不需要使用方关注的
2: 服务端主动健康检查，需要使用方自己定义一个http接口
![image](https://user-images.githubusercontent.com/28588342/146745224-f21cfb10-25f2-4238-8031-8fe5440cb3f3.png)

大部分情况下用第一种就可以了

**Comment by daniuEvan** [comment]
我现在使用测试用例来注册我的服务（nacos 单节点本地启动，8080启动了http服务）：
`	success, err := namingClient.RegisterInstance(vo.RegisterInstanceParam{
		Ip:          "127.0.0.1",  // 我的服务ip
		Port:        8080,  // 我的服务端口
		ServiceName: "nacostest",
		Weight:      10,
		Enable:      true,
		Healthy:     true,
		Ephemeral:   true,
		Metadata:    map[string]string{"idc":"shanghai"},
		ClusterName: "dev", // 默认值DEFAULT
		GroupName:   "dev",   // 默认值DEFAULT_GROUP
	})
`
返回值是正确的， nacos中这个服务在几秒后变为不健康状态了。

**Comment by sanxun0325** [comment]
可以看一下日志，观察一下beat相关的内容

**Comment by daniuEvan** [comment]
非常感谢！我已经解决了！
