### ISSUE TITLE
nacos-sdk-go支持grpc-go的负载均衡吗？

### ISSUE THREAD

**Issue by daniuEvan** [nacos-group/nacos-sdk-go#357]
首先感谢开发者！
nacos-sdk-go目前支持grpc-go的负载均衡吗？
如果支持，我该怎么实现呢？
如果不支持，有什么好的建议作为指导吗？

**Comment by daniuEvan** [comment]
我能想到的方案：
1. 每次到来一个新请求，都使用 SelectOneHealthyInstance（SelectOneHealthInstanceParam加权轮询）获取一个健康的grpc 实例， 但是这样会是nacos服务的负载很大！
2. 在项目中一次性获取全部的健康实例，维护一个healthInstanceArr（周期刷新），然后自我实现负载均衡策略，这样虽然会变得灵活，但是会不会让事情复杂化？
我该怎么办呢？

**Comment by sanxun0325** [comment]
@daniuEvan nacos-sdk-go 自身的负载均衡和你说的第二种方式基本相同，每次筛选健康实例的时候 不会请求nacos server，而是从本地缓存中读取，然后进行权重随机筛选
