### ISSUE TITLE
nacos2.0 beta1，程序如果监听了SIGINT信号退出机制，使用2.0客户端注册服务后，服务下线时无法使用相同客户端取消注册

### ISSUE THREAD

**Issue by jianghuosiliuying** [nacos-group/nacos-sdk-go#359]
因为2.0的代码里rpcclient也监听了该信号，关闭了连接，但是关闭后，服务取消注册DeregisterInstance方法会报错，Client not connected,current status:4，如果取消注册重新创建新的客户端，虽然发送取消注册信号能成功，但是nacos界面上服务并没有被及时下线掉，直到程序直接没了，才会在界面中被剔除，目前临时解决方案是服务注册，取消注册使用v1版本，服务发现使用2.0版本，待测试

**Comment by sanxun0325** [comment]
这个流程是正常的监听到SIGINT信号 grpc连接关闭。 主程序应该也会退出吧。

**Comment by jianghuosiliuying** [comment]
>

**Comment by jianghuosiliuying** [comment]
> 这个流程是正常的监听到SIGINT信号 grpc连接关闭。 主程序应该也会退出吧。

正常是的，但是从优雅退出角度考虑的话，我需要一个完成的正常退出流程，先是取消注册，然后程序阻塞几秒处理收尾的工作，这时候如果nacos有延迟，还是会有流量进来，进来的流量需要正常被处理。但是问题在于，我程序收到term信号后才会去执行取消注册操作，但是nacos2.0的rpc也监听了这个信号，它自己提前把连接给关掉了，倒是我业务收到term信号，再拿注册服务的时候的客户端去取消注册，就会报错。但是如果新建一个客户端去取消注册，虽然不会报错，但是服务并没有被取消，而且整个程序完全结束才从nacos界面中被移除，这感觉很不合理

**Comment by jianghuosiliuying** [comment]
![image](https://user-images.githubusercontent.com/48816518/147194613-5f0007f7-db3a-467e-a2b3-c04183aaa958.png)
业务代码大概就是这么写，启动时创建nacos客户端，业务服务启动完成后，去注册nacos，框架会监听SIGINT和TERM信号，触发stop流程，这个时候会去执行业务取消nacos注册，此时nacos客户端内部也监听TERM信号，关闭了它自己的rpc客户端，但是会导致服务取消注册失败，优雅退出直接就没了

**Comment by sanxun0325** [comment]
pr:https://github.com/nacos-group/nacos-sdk-go/pull/361
