### ISSUE TITLE
你们自己的日志输出重定向，改了系统log是几个意思？

### ISSUE THREAD

**Issue by gpchow** [nacos-group/nacos-sdk-go#36]
如题，调半天，log. 方法在 CreateConfigClient 后无任何响应，纳了闷了，你们记日志就记日志吧，竟然还改系统的标准输出，这操作牛B

**Comment by xgfone** [comment]
这就是一个想起来就维护一下、想不起来就搁置的 demo 而已！而且，像马爸爸提出的口号，他们哪有时间搞这个，就算搞了，顶多也就是为了开源 KPI 而已，所以，没必要要求他们太多。

**Comment by paderlol** [comment]
首先谢谢大家指出这些问题，其次请大家在开源社区做到互相尊重，这个项目也是社区小伙伴贡献的，我们不可能面面俱到，有问题我们去改进，如果大家有更好的想法，欢迎提PR。解决问题总比吐槽问题更好对吗？

**Comment by gpchow** [comment]
是我着相了，fork了一份慢慢去改了

**Comment by HaojunRen** [comment]
大家需要体谅一下，很多Committer，为了情怀很多时候通宵为Nacos贡献代码，讨论问题
