### ISSUE TITLE
run a goroutine for update service, but dont care about err != nil

### ISSUE THREAD

**Issue by a372661369** [nacos-group/nacos-sdk-go#364]
https://github.com/nacos-group/nacos-sdk-go/blob/a4db9f2ed6e5a8cff35dd5b176a9f5b5c3e7526e/clients/naming_client/naming_client.go#L71

**Comment by a372661369** [comment]
whether it will cause some problems?

**Comment by sanxun0325** [comment]
What's the problem? Can you describe it in more detail
