### ISSUE TITLE
每次调用SelectOneHealthyInstance后, 都会新增一个订阅者, 并且连接关闭也没有取消订阅

### ISSUE THREAD

**Issue by herryup** [nacos-group/nacos-sdk-go#366]
go版本 1.17.2
nacos-sdk-go版本 1.0.9

情况描述
1. 启动服务时,注册到nacos
2. 调用SelectOneHealthyInstance获取一个健康实例. 调用grpc. 新增一个目标实例的订阅者.
3. 完成gprc调用后, 并未取消订阅. 

问题
多次调用SelectOneHealthyInstance后, 产生了很多未取消的订阅者

![1](https://user-images.githubusercontent.com/31437594/148171190-f18df686-1dbe-429f-97c3-4acd652a26af.png)
.

**Comment by sanxun0325** [comment]
nacos server什么版本，然后再贴一下日志

**Comment by herryup** [comment]
nacos server是 2.0.3版本.
根据测试, 使用全局的nacos INamingClient对象后, 没有这个问题了.
之前是没次掉SelectOneHealthyInstance接口都会创建一个INamingClient对象.
