### ISSUE TITLE
2.0 SDK 修改实例方法缺失

### ISSUE THREAD

**Issue by mxlxm** [nacos-group/nacos-sdk-go#369]
https://nacos.io/zh-cn/docs/open-api.html#2.3

**Comment by sanxun0325** [comment]
不是缺失，openapi的更新实例，在2.0 sdk中使用RegisterInstance就可以更新。 为了让接口语意更清晰，在sdk中也增加了UpdateInstance接口
Pr:https://github.com/nacos-group/nacos-sdk-go/pull/375
