### ISSUE TITLE
Feature request: support output logs to stdout

### ISSUE THREAD

**Issue by wangrzneu** [nacos-group/nacos-sdk-go#373]
Current SDK only support output log to files. Application deployed in Kubernetes or Docker environment usually output logs to stdout, and manage logs using other components. For example, https://docs.docker.com/config/containers/logging/

**Comment by sanxun0325** [comment]
Can you describe in detail what the current SDK logging does not meet the requirements

**Comment by wangrzneu** [comment]
@sanxun0325 I update the description and create a PR. Please help to review it.

**Comment by spacewander** [comment]
@binbin0325 
It seems this feature is not completed. Why close the issue?
