### ISSUE TITLE
Does sdk 1.x release support nacos 2.x?

### ISSUE THREAD

**Issue by YiuTerran** [nacos-group/nacos-sdk-go#376]
Hello, we are using nacos 2.0.x for java projects. Now we want to use it in a new golang project, but the SDK 2.x version is still in beta.

So, does sdk 1.x release support nacos 2.x? thanks.

你好，我们在java项目里面使用了nacos2.0.x，现在有一个新的golang项目想要复用nacos。但是我看到release里面2.0还是beta状态，不知道1.x的sdk是否支持2.x的nacos？

**Comment by believening** [comment]
我在他们[文档](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html)里看到2.x的server是支持1.x 的sdk的

![image](https://user-images.githubusercontent.com/20397579/150308134-46d6c256-e3bd-440a-abe0-e6e84c4de014.png)

**Comment by believening** [comment]
> 我在他们[文档](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html)里看到2.x的server是支持1.x 的sdk的

![image](https://user-images.githubusercontent.com/20397579/150308420-ab153acf-0d53-4d6e-9cb3-1f88f97bce81.png)

**Comment by believening** [comment]
> Hello, we are using nacos 2.0.x for java projects. Now we want to use it in a new golang project, but the SDK 2.x version is still in beta.
> 
> So, does sdk 1.x release support nacos 2.x? thanks.
> 
> 你好，我们在java项目里面使用了nacos2.0.x，现在有一个新的golang项目想要复用nacos。但是我看到release里面2.0还是beta状态，不知道1.x的sdk是否支持2.x的nacos？

我在他们[文档](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html)里看到2.x的server是支持1.x 的sdk的

![image](https://user-images.githubusercontent.com/20397579/150308420-ab153acf-0d53-4d6e-9cb3-1f88f97bce81.png)

**Comment by YiuTerran** [comment]
好的 感谢
