### ISSUE TITLE
why always return nil when subscribe service

### ISSUE THREAD

**Issue by believening** [nacos-group/nacos-sdk-go#386]
https://github.com/nacos-group/nacos-sdk-go/blob/04e738e4c3acc74f1805bd65abbf973a19662dbe/clients/naming_client/naming_client.go#L292-L300

**Comment by mofei1** [comment]
我遇到了同样的问题

`
var nameClient naming_client.INamingClient

func InitNameClient() {
	sc := []constant.ServerConfig{
		{
			IpAddr:      "192.168.1.8",
			Port:        8848,
			ContextPath: "/nacos",
			Scheme:      "http",
		},
	}
	clientConfig := constant.ClientConfig{
		TimeoutMs:           3000,
		NotLoadCacheAtStart: true,
		LogDir:              "\\tmp\\nacos\\log",
		CacheDir:            "\\tmp\\nacos\\cache",
		LogLevel:            "error",
		Username:            "nacos",
		Password:            "nacos",
		ContextPath:         "/nacos",
	}

	// a more graceful way to create naming client
	client, err := clients.NewNamingClient(
		vo.NacosClientParam{
			ClientConfig:  &clientConfig,
			ServerConfigs: sc,
		},
	)
	if err != nil {
		panic(err)
	}
	nameClient = client
}
func TestRegister(t *testing.T) {
	InitNameClient()
	success, err := nameClient.RegisterInstance(vo.RegisterInstanceParam{
		Ip:          "127.0.0.1",
		Port:        8848,
		ServiceName: "demo.go",
		Weight:      10,
		Enable:      true,
		Healthy:     true,
		Ephemeral:   true,
		Metadata:    map[string]string{"idc":"shanghai"},
		ClusterName: "cluster-a", // default value is DEFAULT
		GroupName:   "group-a",  // default value is DEFAULT_GROUP
	})
	if err != nil {
		log.Println(err)
	}
	if success {
		log.Println("register success")
	}
	select {

	}
}

func TestSub(t *testing.T) {
	InitNameClient()
	err := nameClient.Subscribe(&vo.SubscribeParam{
		ServiceName: "demo.go",
		GroupName:   "group-a",             // default value is DEFAULT_GROUP
		Clusters:    []string{"cluster-a"}, // default value is DEFAULT
		SubscribeCallback: func(services []model.Instance, err error) {
			log.Println("changed ")
			for _,v := range services {
				log.Println(v)
			}
		},
	})
	if err != nil {
		log.Println(err)
	}
	select {

	}
}
`

**Comment by mofei1** [comment]
```go
//我遇到了同样的问题  sdk	github.com/nacos-group/nacos-sdk-go/v2 v2.0.0-Beta.1  NACOS2.0.3
var nameClient naming_client.INamingClient

func InitNameClient() {
	sc := []constant.ServerConfig{
		{
			IpAddr:      "192.168.1.8",
			Port:        8848,
			ContextPath: "/nacos",
			Scheme:      "http",
		},
	}
	clientConfig := constant.ClientConfig{
		TimeoutMs:           3000,
		NotLoadCacheAtStart: true,
		LogDir:              "\\tmp\\nacos\\log",
		CacheDir:            "\\tmp\\nacos\\cache",
		LogLevel:            "error",
		Username:            "nacos",
		Password:            "nacos",
		ContextPath:         "/nacos",
	}

	// a more graceful way to create naming client
	client, err := clients.NewNamingClient(
		vo.NacosClientParam{
			ClientConfig:  &clientConfig,
			ServerConfigs: sc,
		},
	)
	if err != nil {
		panic(err)
	}
	nameClient = client
}
func TestRegister(t *testing.T) {
	InitNameClient()
	success, err := nameClient.RegisterInstance(vo.RegisterInstanceParam{
		Ip:          "127.0.0.1",
		Port:        8848,
		ServiceName: "demo.go",
		Weight:      10,
		Enable:      true,
		Healthy:     true,
		Ephemeral:   true,
		Metadata:    map[string]string{"idc":"shanghai"},
		ClusterName: "cluster-a", // default value is DEFAULT
		GroupName:   "group-a",  // default value is DEFAULT_GROUP
	})
	if err != nil {
		log.Println(err)
	}
	if success {
		log.Println("register success")
	}
	select {

	}
}

func TestSub(t *testing.T) {
	InitNameClient()
	err := nameClient.Subscribe(&vo.SubscribeParam{
		ServiceName: "demo.go",
		GroupName:   "group-a",             // default value is DEFAULT_GROUP
		Clusters:    []string{"cluster-a"}, // default value is DEFAULT
		SubscribeCallback: func(services []model.Instance, err error) {
			log.Println("changed ")
			for _,v := range services {
				log.Println(v)
			}
		},
	})
	if err != nil {
		log.Println(err)
	}
	select {

	}
}

```

**Comment by mofei1** [comment]
当移除GroupName Clusters 参数时可以获取到新上线的实例，不能获取下线的实例，而且当一个实例下线，再次以同样的参数注册，仍然无法获取到。

**Comment by mofei1** [comment]
测试在1.1版本下是正常的

**Comment by mofei1** [comment]
被订阅的服务要先启动才能被获取，当实例被获取后下线，再次以同样的参数注册，无法被获取。。。

**Comment by sanxun0325** [comment]
> 

你这两个UT 里面不用每次都创建client
