### ISSUE TITLE
现在的sdk算是生产可用的版本么，看官网文档现在go - IN PLAN

### ISSUE THREAD

**Issue by hi-wayne** [nacos-group/nacos-sdk-go#39]
现在的sdk算是生产可用的版本么，看官网文档现在go - IN PLAN

**Comment by xgfone** [comment]
看着这代码，我都不敢用。。。。。。更别谈上生产了。。。。。。我宁愿手工调用 HTTP API。

**Comment by ZZMarquis** [comment]
这个应该是这个作者个人的项目。nacos还没有官方的golang版本客户端。

**Comment by liyue201** [comment]
一堆的bug
