### ISSUE TITLE
[Proposal] Move to a compliant library for semaphore

### ISSUE THREAD

**Issue by shubham1172** [nacos-group/nacos-sdk-go#394]
Hi, in [clients/naming_client/beat_reactor.go](https://github.com/nacos-group/nacos-sdk-go/blob/master/clients/naming_client/beat_reactor.go), it is using https://github.com/toolkits/concurrent for semaphores. The package is not licensed, as a result of which it's not compliant with licensing requirements. 

This is a proposal to move to the sync package's implementation https://pkg.go.dev/golang.org/x/sync/semaphore which has a BSD-3 license.

**Comment by sanxun0325** [comment]
Good advice, I'll change it later

**Comment by shubham1172** [comment]
@sanxun0325 thanks! Let me know if you don't have bandwidth, I can also take a stab at it.

**Comment by shubham1172** [comment]
Thank you @sanxun0325 for the quick resolution!

**Comment by shubham1172** [comment]
@sanxun0325, when will you cut the next release for us being able to consume this change?
