### ISSUE TITLE
如何调整nacos日志格式

### ISSUE THREAD

**Issue by HabbyChen** [nacos-group/nacos-sdk-go#395]
为了保持日志格式的统一，方便日志的收集，请问如何调整sdk中日志的格式呢？
In order to keep the log format uniform and facilitate the collection of logs, how to adjust the log format in the sdk?

**Comment by sanxun0325** [comment]
sdk中的日志格式不支持调整，如果你有什么好的想法欢迎讨论

**Comment by habby-c** [comment]
> 

可不可以像gorm的日志形式一样，提供个接口什么的

**Comment by sanxun0325** [comment]
可以对getEncoder()设计为接口，但我觉得意义不大，提供一个json格式打印选项解决采集问题应该也可以

**Comment by habby-c** [comment]
> 可以对getEncoder()设计为接口，但我觉得意义不大，提供一个json格式打印选项解决采集问题应该也可以

我觉得都可以，其实主要就是，程序出现两个日志有点不那么优雅。

**Comment by sanxun0325** [comment]
> > 可以对getEncoder()设计为接口，但我觉得意义不大，提供一个json格式打印选项解决采集问题应该也可以
> 
> 我觉得都可以，其实主要就是，程序出现两个日志有点不那么优雅。

不同的日志文件是正常的，输出的目录你可以指定相同的文件夹， 提供json格式打印的开关 如果感兴趣可以贡献一下
