### ISSUE TITLE
config_client.IConfigClient.SearchConfig() 报json反序列化失败

### ISSUE THREAD

**Issue by zhouxinyu1cp** [nacos-group/nacos-sdk-go#401]
问题如title，debug后发现:

model.ConfigItem.Id字段声明为string，在上述接口执行时，json.Unmarshal() 报反序列化失败，失败原因是 int -> string 失败

环境：go version  go1.17.4  darwin/amd64

**Comment by sanxun0325** [comment]
client 和 server版本提供一下

**Comment by zhouxinyu1cp** [comment]
client: v1.0.7
server: 1.2.1

**Comment by sanxun0325** [comment]
refer:https://github.com/nacos-group/nacos-sdk-go/issues/459
