### ISSUE TITLE
关于vo.RegisterInstanceParam的Ephemeral疑问

### ISSUE THREAD

**Issue by zhu121** [nacos-group/nacos-sdk-go#407]
版本：v2.0.0
问题：
注册实例时Ephemeral值为true，之后改为false，会失败，错误信息是“Current service DEFAULT_GROUP@@xxx is ephemeral service, can't register persistent instance”

**Comment by sanxun0325** [comment]
先取消注册，在重新注册，直接修改是不可以的

**Comment by zhu121** [comment]
> 先取消注册，在重新注册，直接修改是不可以的

我的用法错了，谢谢
