### ISSUE TITLE
RegisterInstance()重复注册的问题

### ISSUE THREAD

**Issue by zhu121** [nacos-group/nacos-sdk-go#408]
**使用版本**
nacos: 2.0.4，bash startup.sh -m standalone
nacos-sdk-go: v2.0.0
golang: go version go1.17.5 linux/amd64
system: Linux 5.10.16.3-microsoft-standard-WSL2 x86_64

**示例代码**
```golang
ret, err := client.RegisterInstance(vo.RegisterInstanceParam{
 Ip:          "127.0.0.1",
 Port:        "50051",
 Weight:      1.0,
 Enable:      true,
 Healthy:     true,
 ServiceName: "test",
 Ephemeral:   true,
})
```

**问题描述**
启动不同的进程执行示例中的代码，重复注册时，RegisterInstance()返回值都是true, nil，而在nacos后台页面看到的实例数是1

**期望结果**
重复注册时会失败？或nacos服务端的实例数应该是多个？

**Comment by sanxun0325** [comment]
重复注册不会失败，因为instanceParam 实例的信息全部相同，相当于幂等处理，实例数应该是1.

**Comment by zhu121** [comment]
> 重复注册不会失败，因为instanceParam 实例的信息全部相同，相当于幂等处理，实例数应该是1.

原来是接口的幂等性问题，谢谢解答
另外，请问下在想要启动一个服务的多个实例，把服务的启动配置也在放在nacos的话，这样就只有1个实例了？和用配置中心来方便的对服务扩容好像有矛盾了，还没理解到位

**Comment by sanxun0325** [comment]
没太理解你的意思，可以举个例子么

**Comment by zhu121** [comment]
> 没太理解你的意思，可以举个例子么

比如有个登录服务，在两个机子上分别启动一个实例，登录服务的连接地址信息不同话，是不是就不能放在nacos配置中心了

**Comment by sanxun0325** [comment]
配置中心是两个配置文件就可以了。

**Comment by zhu121** [comment]
> 配置中心是两个配置文件就可以了。

感谢解答！
