### ISSUE TITLE
client无法进行重新连接

### ISSUE THREAD

**Issue by a372661369** [nacos-group/nacos-sdk-go#409]
如这个issue https://github.com/alibaba/nacos/issues/7219

**Comment by sanxun0325** [comment]
你用的什么版本客户端？相关pr:https://github.com/nacos-group/nacos-sdk-go/pull/327/files

**Comment by a372661369** [comment]
github.com/nacos-group/nacos-sdk-go/v2 v2.0.0-Beta.1

> 你用的什么版本客户端？相关pr:https://github.com/nacos-group/nacos-sdk-go/pull/327/files,https://github.com/nacos-group/nacos-sdk-go/pull/404

**Comment by sanxun0325** [comment]
@a372661369 使用v2.0.0 正式版再试试
