### ISSUE TITLE
搜索配置: SearchConfig 问题反馈

### ISSUE THREAD

**Issue by 89trillion-lvbin** [nacos-group/nacos-sdk-go#417]
nacos openApi中查询列表的接口中并没有返回md5等其他值，这些值很重要，但是被忽略了。在现有的方法中是否要循环去调用openApi的详情接口，取出相应的数据，然后封成SearchConfig方法

**Comment by sanxun0325** [comment]
nacos server 没有返回md5数据，去nacos 主仓库建立issue吧
