### ISSUE TITLE
更新到1.1.1后,程序启动后nacos在疯狂的输出日志.

### ISSUE THREAD

**Issue by ZhangHu1225** [nacos-group/nacos-sdk-go#418]
配置方式:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/37826977/157031531-46cfcb83-02f8-4490-88e8-c3239b77288b.png">

日志:
[log.txt](https://github.com/nacos-group/nacos-sdk-go/files/8197539/log.txt)

**Comment by sanxun0325** [comment]
清理下CacheDir目录，再试试

**Comment by sanxun0325** [comment]
NewNacosRegister func会被多次调用么，NamingClient,以及ConfigCLient 只需要创建一个全局唯一的即可。

**Comment by ZhangHu1225** [comment]
删了CacheDir目录还是会疯狂打日志,
NewNacosRegister func 这个方法只会在程序启动时调用一次.

**Comment by sanxun0325** [comment]
> 

提供一下创建ConfigClient的代码

**Comment by ZhangHu1225** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/37826977/157034303-5a1e847a-1ed1-4fab-9ec8-9e51a9ac4454.png">

**Comment by sanxun0325** [comment]
> 

没有什么问题，可以在排查一下。1:降低到1.0.9 or 1.1.0 尝试一下是否还有同样的问题。2:在listenConfig OnChange 中打印data ，看一下文件内容是否有发生变化？

**Comment by ZhangHu1225** [comment]
试了下1.1.0 正常

**Comment by sanxun0325** [comment]
> 试了下1.1.0 正常

使用1.1.1在自定义的onChange func中 有发现data内容变化嘛

**Comment by ZhangHu1225** [comment]
没有打印出来配置是否有变化
<img width="638" alt="image" src="https://user-images.githubusercontent.com/37826977/157159349-8926be63-a2ce-4155-8d15-c42c0c8a6451.png">

**Comment by huyuanxin** [comment]
我也遇到了同样的问题，定位到是package config_client下的config_client.go func (client *ConfigClient) longPulling(taskId int) func() error 这个函数一直被执行

**Comment by ZhangHu1225** [comment]
系统: window11
打了下断点: changedTmp 每次都是返回的服务名+group
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/37826977/157800296-9eac6388-2585-4700-8a57-aea9747c7abe.png">

**Comment by sanxun0325** [comment]
创建客户端时namespaceId 要写ID啊。如果是public默认为空就行了，不要写public!!!
