### ISSUE TITLE
请问nacos-sdk-go支持https访问nacos吗？

### ISSUE THREAD

**Issue by AirYang** [nacos-group/nacos-sdk-go#42]
我看到java版本的客户端可以支持https访问nacos注册中心，是否go语言版本的客户端支持https?

**Comment by MasterJoyHunan** [comment]
截止到 2020-08-14 还是没有支持 https

**Comment by lzp0412** [comment]
@MasterJoyHunan 
已经支持了

**Comment by MasterJoyHunan** [comment]
@lzp0412 可能暂时没有 relese , 1.0.0 版本源码里还是没有
```
module nacos-mini-serve

go 1.14

require (
	github.com/nacos-group/nacos-sdk-go v1.0.0
)
```

**Comment by lzp0412** [comment]
@MasterJoyHunan 嗯，我们在下一个小版本会发布，你可以先用master代码验证下

**Comment by ahululu** [comment]
> @MasterJoyHunan 嗯，我们在下一个小版本会发布，你可以先用master代码验证下

你好，请问https支持了么
