### ISSUE TITLE
request help：Why can't I get notified when I logout all instance from nacos although I have used the subscription interface

### ISSUE THREAD

**Issue by soulbird** [nacos-group/nacos-sdk-go#423]
When we logout all instances in nacos via api like:
```bash
curl -X DELETE 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=NACOS&ip=127.0.0.1&port=10000'
```
It seems that [nacos-sdk-go](https://github.com/nacos-group/nacos-sdk-go) will not notify us, although we use the subscription interface https://github.com/nacos-group/nacos-sdk-go/blob/master/clients/naming_client/naming_client.go#L313

Why can't I get notified when `hosts ` is empty?  Why is it designed this way

**Comment by sanxun0325** [comment]
UpdateCacheWhenEmpty enables the subscription callback to be triggered when the instance list is empty
see: https://github.com/nacos-group/nacos-sdk-go/blob/master/common/constant/config.go#L44
