### ISSUE TITLE
nacos管理界面一会可用一会不可用。

### ISSUE THREAD

**Issue by uther518** [nacos-group/nacos-sdk-go#426]
![1648556469(1)](https://user-images.githubusercontent.com/5262407/160610059-6810bcd6-6c32-476c-84ca-05d6f4031f0b.png)

启动有时报这个错，有时启动不报。
 ERROR   naming_client/host_reactor.go:87       do not have useful host, ignore it, name:DEFAULT_GROUP@@micro.rpc-service.api

**Comment by sanxun0325** [comment]
这个日志代表没有可用的实例，检查下实例是不是都下线了

**Comment by uther518** [comment]
缓存里面清理掉就不会报这个错了。

但是nacos管理界面那个健康实例数，会经常变成不健康，但实际是可用的。

**Comment by sanxun0325** [comment]
用的1.x sdk 还是2.x sdk， 1.x看下日志心跳是否正常发送，2.x看下日志 grpc连接是否有断开

**Comment by sanxun0325** [comment]
no reply

**Comment by sanxun0325** [comment]
no reply
