### ISSUE TITLE
nacos-go-sdk无法引用

### ISSUE THREAD

**Issue by wangwentao** [nacos-group/nacos-sdk-go#452]
各位好：在项目首页看到当前最新release版本是2.0.2，不过通过go get -u github.com/nacos-group/nacos-sdk-go 命令只能下载到1.1.1这个版本。不清楚问题原因是什么，到贵宝地请教。

**Comment by SpecialYang** [comment]
```
go get github.com/nacos-group/nacos-sdk-go/v2
```
