### ISSUE TITLE
The field type of Id in model.ConfigItem don't match the type of json used in function SearchConfigProxy

### ISSUE THREAD

**Issue by Kean9527** [nacos-group/nacos-sdk-go#459]
### What version of nacos-sdk-go are you using?
v1.0.9
### What version of nacos-sever are you using?
1.2.1.2
### What version of Go are you using (`go version`)?
1.17
### What operating system (Linux, Windows, …) and version?
ubuntu
### What did you do?
If possible, provide a recipe for reproducing the error.
when using the SearchConfig API
### What did you expect to see?
use type int instead of string in model.ConfigItem
### What did you see instead?
use type int instead of string in model.ConfigItem,like this:
Id      int    `param:"id"`

**Comment by sanxun0325** [comment]
升级下nacos server版本吧，我使用nacos server 1.4.3是没有问题的
