### ISSUE TITLE
How can I use nacos for grpc load balance? Rewrite the nacos-grpc resolver(grpc support) or use SelectOneHealthy API?

### ISSUE THREAD

**Issue by incrediblegenius** [nacos-group/nacos-sdk-go#465]
I cant find the official implements of nacos-grpc resolver, if I'd like to use grpc load balance.
Or I will create new connections every time my client need service when  using SelecOneHealth API.

**Comment by sanxun0325** [comment]
nacos client use GRPC interacts with the server，if you want to get an instance of calling a service, just use the SelectOneHealthy API, which already implements a weight-based load balancing algorithm

**Comment by incrediblegenius** [comment]
> 

I use golang grpc client and want to use load balance methord. But using this API results in more dial connections and less concurrency. If using GRPC resolver ,clients will create a conn pool which uses less resources to create conns. So, I just wanna know is there any official solution of GRPC resolver?

**Comment by sanxun0325** [comment]
nacos sdk only creates a grpc  link with the nacos server.
