### ISSUE TITLE
当dataId过长且含有中文时，获取到的值有几率不对

### ISSUE THREAD

**Issue by tonglin96** [nacos-group/nacos-sdk-go#467]
### What did you do?
If possible, provide a recipe for reproducing the error.
当通过sdk获取“guidance_config.ANALYTICS-年龄性别拿起小时数据源”的配置信息时，与nacos web上设置的值不符。
### What did you expect to see?
与nacos web上设置值不符

**Comment by sanxun0325** [comment]
信息补充一下，sdk版本，server版本

**Comment by binbin0325** [comment]
没有提供更多信息，时间太久，暂时关闭
