### ISSUE TITLE
sdk 2.0.3版本下必现panic异常

### ISSUE THREAD

**Issue by chuckie-cheng** [nacos-group/nacos-sdk-go#472]
启动监听服务状态

panic: reflect: call of reflect. Value. Type on zero Value (recovered]
panic: reflect: call of reflect.Value.Type on zero Value
goroutine 1287 [running]:
encoding/json. (*encodeState) . marshal. func1 (0xc000659a08)
/usr/local/go/src/encoding/json/encode.go:328+0x8d
panic(Oxfaece0, Oxc0002ea9a8)
/usr/local/go/src/runtime/panic.go:965+0x1b9
reflect.Value.Type(0x0, 0x0, 0x0, Oxc000f9bOel, 0x0)
/usr/local/go/src/reflect/value.go:1908+0x189
1
encoding/json.stringEncoder(0xc00122a200,0x0,0x0,0x0,0xc000f90100)
2
/usr/local/go/src/encoding/json/encode.go:620+0x46
13
encoding/json.mapEncoder-encode(0x123c888,0xc00122a200,0xfbd880,0xc0015daf68,0x195,0x100)
14
/usr/local/go/src/encoding/json/encode.go:813+0x366
15
encoding/json.structEncoder-encode(0xc000517b00, Oxd, 0x10, Oxc0001cda70, Oxc00122a200, 0x10c6860, Oxc0015daf10, 0x199, 0x100)
16
/usr/local/go/src/encoding/json/encode.go:761+0x2ab
17
encoding/json.arrayEncoder.encode(0xc0001cdaa®, Oxc00122a200, Oxf566a0, Oxc00045a858, 0x97, 0xb60100)
18
/usr/local/go/src/encoding/json/encode.go:915+0xd6
19
encoding/json.sliceEncoder-encode(0xc0003bccf0,0xc00122a200,Oxf566a0,0xc00045a858,0x97,0x100)
20
21
/usr/local/go/src/encoding/json/encode.go:888+0xfe
encoding/json.typeEncoder.func1(0xc00122a200,0xf566a0,0xc00045a858,0x97,0x100)
22
/usr/local/go/src/encoding/json/encode.go:397+0x79
23
encoding/json.structEncoder.encode(0xc00038a900,0xa,0x10,0xc0002f2030,0xc00122a200,0x10b43e0,0xc000452850,0x99,0x10b0100)
24
/usr/local/go/src/encoding/json/encode.go:761+0x2ab
25
encoding/json. (*encodeState). reflectValue(0xc00122a200, 0x10b43e0, Oxc00045a850, 0x99, 0x000650100)
26
/usr/local/go/src/encoding/json/encode.go:360+0x82
27
encoding/json. (*encodeState) .marshal(0xc00122a200, 0x10b43e0, Oxc00045a850, 0x100, 0x0, 0x0)
28
/usr/local/go/src/encoding/json/encode.go:332+0xf9
29
encoding/json.Marshal(0x10b43e0, Oxc00045a850, 0x10b43e0, Oxc00045a850, 0x0, 0x0, 0xc0003360c0)
30
/usr/local/go/src/encoding/json/encode.go:161+0x52
31
github.com/nacos-group/nacos-sdk-go/v2/clients/cache.WriteServicesToFile(0x2710, Oxc0015da880, Ox1a, 0x1c, 0x0, 0x0, 0x1814d062de3, 0x0, 0x0, 0xc000334520,
...)
32
/opt/devel/vendor/github.com/nacos-group/nacos-sdk-go/v2/clients/cache/disk_cache.go:39+0xa8
33
34
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_cache. (#ServiceInfoHolder).ProcessService(0xc00011ad20,0xc0007h0888)
/opt/devel/vendor/github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_cache/service_info_holder.go:97+0x7a5
35
36
github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc. (*NamingPushRequestHandler)•RequestReply(0xc000011698,0x1357038,0xc0007b0880,0xc00050aa00,0xc0007be
37
/opt/devel/vendor/github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc/server_request_handler.go:93+0x57
github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.(#GrpcClient).handleServerRequest(0xc0000115f8,0xc000a66e10,0xc00031edb0)
38
/opt/devel/vendor/github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc/grpc_client.go:246+0x1aa
39
github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc. (#GrpcClient).bindBiRequestStream.func1(0x135da40,0xc000147780,0xc0000115f8,0xc00031edb0)
40
/.opt/devel/vendor/github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc/grpc_client.go:193+0x4d9
41
created by github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc. (*GrpcClient).bindBiRequestStream
42
/opt/devel/vendor/github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc/grpc_client.go:168+0x5d
43

**Comment by Sivyer9303** [comment]
方便发下你报错的service的信息吗？

**Comment by chuckie-cheng** [comment]
service key: TEST-CHENG-LEIGOTES
"cacheMillis": 10000
"hosts": I
G-LEI was updated to:
"instanceld":..
"1p": "10.113.87.60",
"port": 1000000
"weight": 1,
"healthy": true,
"enabled" : true,
"ephemeral": true,
"clusterName": "DEFAULT"
"serviceName": "TEST-CHENG-LEIG@TEST-CHENG-LEI"
"metadata": 0,
"instancelleartBeatInterval":5001
"1pDeleteTimeout": 30000,
"instanceHeartBeatT1meOut": 15000
J.
E
"instanceld":
"1p": "10.113.87.60",
"port": 0,
"weight": 1,
"healthy": true,
"enabled": trad
"ephemeral": true,
"clusterName" : "DEFAULT",
"serviceName":
"TEST-CHENG-LEIC@TEST-CHENG-LEI,
"metadata": (
"name":
"chuckie",
"value": "test-
-1111"
J.
"instanceHeartBeatInterval":5000,
"ipDeleteTimeout": 30000,
"instanceHeartBeatTime0ut": 15000
5.
1,
"checksum":
"lastRefTime": 1655172700425,
"clusters": ''",
"name": "TEST-CHENG-LEI",
"groupName" : "TEST-CHENG
"valid": true,
"allIpg"; false,
"reachProtectionThreshold" : false
}

**Comment by chuckie-cheng** [comment]
> 可以提供下info日志，相关内容：service key:%s was updated to:%s


service key: TEST-CHENG-LEIGOTES
"cacheMillis": 10000
"hosts": I
G-LEI was updated to:
"instanceld":..
"1p": "10.113.87.60",
"port": 1000000
"weight": 1,
"healthy": true,
"enabled" : true,
"ephemeral": true,
"clusterName": "DEFAULT"
"serviceName": "TEST-CHENG-LEIG@TEST-CHENG-LEI"
"metadata": 0,
"instancelleartBeatInterval":5001
"1pDeleteTimeout": 30000,
"instanceHeartBeatT1meOut": 15000
J.
E
"instanceld":
"1p": "10.113.87.60",
"port": 0,
"weight": 1,
"healthy": true,
"enabled": trad
"ephemeral": true,
"clusterName" : "DEFAULT",
"serviceName":
"TEST-CHENG-LEIC@TEST-CHENG-LEI,
"metadata": (
"name":
"chuckie",
"value": "test-
-1111"
J.
"instanceHeartBeatInterval":5000,
"ipDeleteTimeout": 30000,
"instanceHeartBeatTime0ut": 15000
5.
1,
"checksum":
"lastRefTime": 1655172700425,
"clusters": ''",
"name": "TEST-CHENG-LEI",
"groupName" : "TEST-CHENG
"valid": true,
"allIpg"; false,
"reachProtectionThreshold" : false
}

**Comment by sanxun0325** [comment]
你这个日志乱序了吧？

**Comment by chuckie-cheng** [comment]
> 你这个日志乱序了吧？

内网开发，日志无法外发，通过拍照识别的，部分字段会有误差，这个不影响吧

**Comment by sanxun0325** [comment]
目前无法确定是哪个字段的数据有问题，导致jsonMarshal失败了

**Comment by chuckie-cheng** [comment]
> 因为日志是乱的，无法判断具体是哪个字段数据有问题 导致jsonMarshal失败了。2.0.3指的是服务端么，客户端现在还没有2.0.3版本，你按照issue模版提供下具体信息吧


 之前是在tag 2.0.3上验证出的问题，是个偶现问题，目前在客户端2.0.2也有这个问题
通过DATA TRACE 
发现
https://github.com/chuckie-cheng/nacos-sdk-go/blame/v2.0.2/clients/naming_client/naming_cache/service_info_holder.go
包中的
ProcessService方法会同时被 https://github.com/chuckie-cheng/nacos-sdk-go/blob/v2.0.2/common/remote/rpc/server_request_handler.go 中的 RequestReply方法和
https://github.com/chuckie-cheng/nacos-sdk-go/blob/v2.0.2/clients/naming_client/service_info_updater.go
中的updateServiceNow方法调用

ProcessService方法中的 变量 service 会出现读写并发，s.ServiceInfoMap 偶现现value 覆盖,内存无效，有概率导致 
下面两行代码
logger.Infof("service key:%s was updated to:%s", cacheKey, util.ToJsonString(service))
cache.WriteServicesToFile(*service, s.cacheDir)
内部封装的js, _ := json.Marshal(object)方法panic异常   panic: reflect: call of reflect. Value. Type on zero Value (recovered]

具体的写覆盖以及在 ProcessService方法中调用的 checkInstanceChanged内部方法
sortInstance(oldInstance)这一步操作，导致ServiceInfoMap中的value被修改。导致其他的 json.Marshal(object)中的panic异常   panic: reflect: call of reflect. Value. Type on zero Value (recovered]



func (s *ServiceInfoHolder) ProcessService(service *model.Service) {
	if service == nil {
		return
	}
	if !s.updateCacheWhenEmpty {
		//if instance list is empty,not to update cache
		if service.Hosts == nil || len(service.Hosts) == 0 {
			logger.Warnf("instance list is empty, updateCacheWhenEmpty is set to false, callback is not triggered. service name:%s", service.Name)
			return
		}
	}

	cacheKey := util.GetServiceCacheKey(util.GetGroupName(service.Name, service.GroupName), service.Clusters)
	oldDomain, ok := s.ServiceInfoMap.Get(cacheKey)
	if ok && oldDomain.(model.Service).LastRefTime >= service.LastRefTime {
		logger.Warnf("out of date data received, old-t: %d, new-t: %d", oldDomain.(model.Service).LastRefTime, service.LastRefTime)
		return
	}

	s.UpdateTimeMap.Set(cacheKey, uint64(util.CurrentMillis()))
	s.ServiceInfoMap.Set(cacheKey, *service)
	if !ok || checkInstanceChanged(oldDomain, service) {
		logger.Infof("service key:%s was updated to:%s", cacheKey, util.ToJsonString(service))
		cache.WriteServicesToFile(*service, s.cacheDir)
		s.subCallback.ServiceChanged(cacheKey, service)
	}
	monitor.GetServiceInfoMapSizeMonitor().Set(float64(s.ServiceInfoMap.Count()))
}

**Comment by chuckie-cheng** [comment]
> 

补充：tag2.0.0以下的版本没有这个问题
