### ISSUE TITLE
没有配置时，尝试获取配置，打印error级别日志

### ISSUE THREAD

**Issue by tonglin96** [nacos-group/nacos-sdk-go#486]
### What version of nacos-sdk-go are you using?
2.0.3
### What version of nacos-sever are you using?
2.0.3
### What version of Go are you using (`go version`)?
1.17
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
期望不要打印error级别日志
### What did you see instead?
`ERROR cache/disk_cache.go:84 failed to delete config file,cache:/tmp/nacos/cache/1657098560927365816/aaa@@bbb@@develop ,value: ,err:remove /tmp/nacos/cache/1657098560927365816/aaa@@bbb@@develop: no such file or directory`

**Comment by sanxun0325** [comment]
This is an error, the error level should be printed, and the client version you provided is not correct
