### ISSUE TITLE
nacos configClient使用监听方法监听无效

### ISSUE THREAD

**Issue by pahxgh** [nacos-group/nacos-sdk-go#49]
我使用的方法如下
`err = configClient.ListenConfig(vo.ConfigParam{
	DataId:  dataId,
	Group:   group,
	Content: content,
	OnChange: func(namespace, group, dataId, data string) {
		fmt.Println("group:" + group + ", dataId:" + dataId + ", data:" + data)
	},
})`
这个方法中的各项配置都是正确的，且可以使用getConfig下载，然后我使用
var wg sync.WaitGroup
wg.Add(1)
wg.Wait()
来保证该程序不会退出，最后看日志中的内容如下：
`2020/04/16 17:43:25 [client.ListenConfig] request url: http://xxxxx/nacos/v1/cs/configs/listener  ;params: map[Listening-Configs:yarDEV1088958d4d6bcf1947632b196ef07a54f3004c58-3522-4e65-8a0a-5043721a51a6]  ;header: map[Content-Type:[application/x-www-form-urlencoded] Long-Pulling-Timeout:[30000]]
2020/04/16 17:43:25 [client.ListenConfig] no change`
而实际上我的配置已经通过web控制台进行了修改。
本人是在windows环境下进行的测试，不知道环境是否对该问题有影响

**Comment by lzp0412** [comment]
这个是请求服务超时了，先确定下你的开发环境是否能请求控制台接口

**Comment by pahxgh** [comment]
可以请求啊，我的getConfig是可以正常下载配置文件的，监听端口不应该这么快就失效的吧？

**Comment by lzp0412** [comment]
23191211  加下这个群，或者手机号发我邮箱641785844@qq.com，详细帮你看下

**Comment by lzp0412** [comment]
23191211 加下这个钉钉群，或者手机号发我邮箱641785844@qq.com，详细帮你看下
