### ISSUE TITLE
Can not download with go mod

### ISSUE THREAD

**Issue by keepchen** [nacos-group/nacos-sdk-go#499]
#### OS  

Darwin chenjinpingdeMBP 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64  

#### GO VERSION  
go version go1.17.5 darwin/amd64

#### QUESTION  
```go  
import (
    ...
    "github.com/nacos-group/nacos-sdk-go/v2"
    ...
)
```  

```shell
go mod tidy
```  
 When i download nacos-go-sdk by using go mod,some error occurred:
```text
go: downloading github.com/nacos-group/nacos-sdk-go/v2 v2.0.0
go: finding module for package github.com/nacos-group/nacos-sdk-go/v2
go: downloading github.com/nacos-group/nacos-sdk-go/v2 v2.0.2
ecosystem/pkg/app/beat/config imports
        github.com/nacos-group/nacos-sdk-go/v2: github.com/nacos-group/nacos-sdk-go/v2@v2.0.2: verifying module: checksum mismatch
        downloaded: h1:FHd9IZk95mNLK2OfVSWKGQOeMaR5QSfDUlgwmuC9mqA=
        sum.golang.org: h1:ajCkBB1xcANKL/7XwRiWiUv9ufqoGdDDhPZzDuerz6A=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by NicoleRobin** [comment]
I had the same problem
``` shell
$ go get github.com/nacos-group/nacos-sdk-go/v2@v2.0.2
go: downloading github.com/nacos-group/nacos-sdk-go/v2 v2.0.2
go: github.com/nacos-group/nacos-sdk-go/v2@v2.0.2: verifying module: checksum mismatch
	downloaded: h1:FHd9IZk95mNLK2OfVSWKGQOeMaR5QSfDUlgwmuC9mqA=
	sum.golang.org: h1:ajCkBB1xcANKL/7XwRiWiUv9ufqoGdDDhPZzDuerz6A=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by NicoleRobin** [comment]
has fixed this problem by thses steps：
```
go clean -modcache
go mod tidy
```

The reason may be because the tag was create twice resulting in inconsistency between the sum in the cache and the latest sum.

**Comment by keepchen** [comment]
> has fixed this problem by thses steps：
> 
> ```
> go clean -modcache
> go mod tidy
> ```
> 
> The reason may be because the tag was create twice resulting in inconsistency between the sum in the cache and the latest sum.

I have tried it, but it doesn’t work.

**Comment by NicoleRobin** [comment]
Are you set up GOPROXY it, if set up, you can switch the proxy or just stop using GOPROXY
For me, i switch proxy from goproxy.io to goproxy.cn, and execute the above command and it's worked.

**Comment by NicoleRobin** [comment]
> > has fixed this problem by thses steps：
> > ```
> > go clean -modcache
> > go mod tidy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The reason may be because the tag was create twice resulting in inconsistency between the sum in the cache and the latest sum.
> 
> I have tried it, but it doesn’t work.

Are you set up GOPROXY it, if set up, you can switch the proxy or just stop using GOPROXY
For me, i switch proxy from goproxy.io to goproxy.cn, and execute the above command and it's worked.

**Comment by keepchen** [comment]
> > > has fixed this problem by thses steps：
> > > ```
> > > go clean -modcache
> > > go mod tidy
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The reason may be because the tag was create twice resulting in inconsistency between the sum in the cache and the latest sum.
> > 
> > 
> > I have tried it, but it doesn’t work.
> 
> Are you set up GOPROXY it, if set up, you can switch the proxy or just stop using GOPROXY For me, i switch proxy from goproxy.io to goproxy.cn, and execute the above command and it's worked.

When I run this command:  
```shell
export GOPROXY=https://goproxy.cn,direct && go get -u github.com/nacos-group/nacos-sdk-go/v2
```  
It works.Thanks a lot! 😄 ❤️
