### ISSUE TITLE
V2 GetConfig specified namespace ID is invalid

### ISSUE THREAD

**Issue by ZhengKe996** [nacos-group/nacos-sdk-go#503]
使用v2版本 namespace 无效 改用v1正常
<img width="598" alt="3" src="https://user-images.githubusercontent.com/82481893/184613507-dccfe73c-0660-45e5-98b4-3cc107bf1970.png">
<img width="614" alt="2" src="https://user-images.githubusercontent.com/82481893/184613517-7c60dff9-11e7-42d1-8ae0-fe6a6d1aa165.png">
<img width="719" alt="1" src="https://user-images.githubusercontent.com/82481893/184613518-2b7658d2-0163-4a36-b922-38d7683fe4cd.png">

**Comment by binbin0325** [comment]
可以贴一下log日志

**Comment by ZhengKe996** [comment]
<img width="720" alt="1" src="https://user-images.githubusercontent.com/82481893/184632221-22fa83b5-d8f0-470a-8a5d-0e203074a482.png">

**Comment by binbin0325** [comment]
nacos server 9848端口没开，可以检查下nacos server的配置文件是否改过端口，特别需要注意如果是docker环境 需要将9848映射出来。

**Comment by ZhengKe996** [comment]
已解决，第一个问题的原因：ip地址填的127.0.0.1 改成192.168.xxx.xxx 第二个问题，防火墙未开 9848访问失败 感谢老哥指点🤗
