### ISSUE TITLE
traceid跟踪

### ISSUE THREAD

**Issue by shenningting** [nacos-group/nacos-sdk-go#510]
client如何传入traceid，进行全链路跟踪（客户端请求->服务->nacos操作）

**Comment by binbin0325** [comment]
你说的接入trace，具体想要关注什么信息呢？nacos的客户端只是一个sdk，和nacos server的交互很多都是异步的，

**Comment by shenningting** [comment]
想要记录一次请求 对nacos的操作，从nacos获取配置信息或者增加配置信息等

**Comment by binbin0325** [comment]
那不需要在sdk中做这件事，在业务代码调用sdk时记录trace就好了。
