### ISSUE TITLE
当服务销毁之后，nacos上实例一直存在

### ISSUE THREAD

**Issue by flutePeak** [nacos-group/nacos-sdk-go#513]
sdk版本v1.0.3。目前的现象是  我的服务已经挂掉了，但是在nacos上的服务列表还在，并且是活跃状态。必须手动下线，否则部分请求会转发到已经消亡的服务上。

**Comment by binbin0325** [comment]
实例标记为不健康到下线的过程，服务端是会经过一定的心跳周期处理的，并不是同步的。

**Comment by flutePeak** [comment]
> 实例标记为不健康到下线的过程，服务端是会经过一定的心跳周期处理的，并不是同步的。

您好，问题是我的实例销毁一个月，nacos上还是存在那个服务，并且是健康状态，导致我必须手动设置为下线，不然流量就会往那边导入

**Comment by flutePeak** [comment]
> 实例标记为不健康到下线的过程，服务端是会经过一定的心跳周期处理的，并不是同步的。

同一个nacos，我其他的java服务，一旦销毁了，达到心跳周期，就自动在服务列表消失了。。。

**Comment by binbin0325** [comment]
可以提供复现这个的问题的信息

**Comment by renky1025** [comment]
你需要在服务下线前（等待中断信号 优雅地关闭服务器），手动 nacosClient.Deregister 取消注册

**Comment by binbin0325** [comment]
SDK 可以升级到1.1.3 再试试

**Comment by littlePoBoy** [comment]
我的是1.1.16版本，手动namingClient.DeregisterInstance ，服务端注册表还在，过一会才会消失，感觉像是根据心跳做的健康检测，手动注销并没有用。不知该怎么解决
