### ISSUE TITLE
如何配置Endpoint使用节点的更新处理

### ISSUE THREAD

**Issue by zhu121** [nacos-group/nacos-sdk-go#514]
版本：v2.1.0
问题1：
* constant.NewClientConfig()时用constant.WithEndpoint()传入了某个nacos节点的IP:PORT
* clients.NewNamingClient()过程中会调用到NacosServer的refreshServerSrvIfNeed()
* 但是函数内的http请求"http://" + server.endpoint + "/nacos/serverlist"结果是为空
* 配置的IP:PORT用 "http://IP:PORT/nacos/index.html" ，是可以正常访问后台页面的
* 在 "https://nacos.io/zh-cn/docs/open-api.html" 看到类似的url格式是/nacos/v1/ns/operator/servers

问题2：
* refreshServerSrvIfNeed()这个功能是否应该启用，会间隔1s发送http请求，且这个时间是用户不能自行配置的

**Comment by binbin0325** [comment]
endpoint是需要你提供/nacos/serverlist接口的ip和port,  nacos 通过定期访问这个接口拿到nacos server的列表。

**Comment by zhu121** [comment]
> endpoint是需要你提供/nacos/serverlist接口的ip和port, nacos 通过定期访问这个接口拿到nacos server的列表。
请问下，
是要自己实现一个服务，以及"/nacos/serverlist"这个API功能，给nacos-sdk-go使用，这理解吗？

**Comment by binbin0325** [comment]
> > endpoint是需要你提供/nacos/serverlist接口的ip和port, nacos 通过定期访问这个接口拿到nacos server的列表。
> > 请问下，
> > 是要自己实现一个服务，以及"/nacos/serverlist"这个API功能，给nacos-sdk-go使用，这理解吗？

是的
