### ISSUE TITLE
客户端调用，Subscribe不会更新本地缓存么，SelectInstances函数返回的为什么永远是第一次的结果？

### ISSUE THREAD

**Issue by youguys** [nacos-group/nacos-sdk-go#524]
用的最新版本的sdk

//用下面的代码获取实例ok
param1 := vo.SelectInstancesParam{
        ServiceName: "authentication",
        GroupName:   "nacostest",
        Clusters:    []string{"DEFAULT"},
        HealthyOnly: true,
}
nacosInstance, err = client.SelectInstances(param1)
if err != nil {
    panic("SelectInstances failed!")
}       
fmt.Printf("SelectInstances,param:%+v, result:%+v \n\n", param1, nacosInstance)

//订阅调用也成功
param := &vo.SubscribeParam{
     ServiceName: "authentication",
     GroupName:   "nacostest",
     SubscribeCallback: func(services []model.Instance, err error) {
         fmt.Printf("callback return services:%s \n\n", util.ToJsonString(services))
     },
 }   
 ExampleServiceClient_Subscribe(client, param)

我的问题是：
           如果我手动删除了一个实例之后，subscribe函数调用了callback之后，再调用SelectInstances为什么拿到的还是全量的实例，subscribe不会自动更新缓存么。
          还是说我要用一个全局变量把获取到的instance存起来，然后后续直接拿全局变量

**Comment by binbin0325** [comment]
@youguys 怎么删除的实例？正常情况下subscribe的callback执行后会更新本地缓存，执行SelectInstances会从本地缓存中获取删除实例后的数据。 可以重点关注下，删除实例后 callback执行了几次。

**Comment by youguys** [comment]
> @youguys 怎么删除的实例？正常情况下subscribe的callback执行后会更新本地缓存，执行SelectInstances会从本地缓存中获取删除实例后的数据。 可以重点关注下，删除实例后 callback执行了几次。

     用两个客户端像服务端注册，然后其中一个客户端退出，失去心跳下线。 下线后，callback执行了一次。

     SelectAllInstance,param:{Clusters:[DEFAULT] ServiceName:authentication GroupName:nacostest}, result:[{InstanceId: Ip:10.0.3.83 Port:8004 Weight:10 Healthy:true Enable:true Ephemeral:true ClusterName:DEFAULT ServiceName:nacostest@@authentication Metadata:map[idc:shanghai] InstanceHeartBeatInterval:5000 IpDeleteTimeout:30000 InstanceHeartBeatTimeOut:15000} {InstanceId: Ip:10.0.3.45 Port:8004 Weight:10 Healthy:true Enable:true Ephemeral:true ClusterName:DEFAULT ServiceName:nacostest@@authentication Metadata:map[idc:shanghai] InstanceHeartBeatInterval:5000 IpDeleteTimeout:30000 InstanceHeartBeatTimeOut:15000}] 

callback return services:[{"instanceId":"","ip":"10.0.3.45","port":8004,"weight":10,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"nacostest@@authentication","metadata":{"idc":"shanghai"},"instanceHeartBeatInterval":5000,"ipDeleteTimeout":30000,"instanceHeartBeatTimeOut":15000}] 

SelectAllInstance,param:{Clusters:[DEFAULT] ServiceName:authentication GroupName:nacostest}, result:[{InstanceId: Ip:10.0.3.83 Port:8004 Weight:10 Healthy:true Enable:true Ephemeral:true ClusterName:DEFAULT ServiceName:nacostest@@authentication Metadata:map[idc:shanghai] InstanceHeartBeatInterval:5000 IpDeleteTimeout:30000 InstanceHeartBeatTimeOut:15000} {InstanceId: Ip:10.0.3.45 Port:8004 Weight:10 Healthy:true Enable:true Ephemeral:true ClusterName:DEFAULT ServiceName:nacostest@@authentication Metadata:map[idc:shanghai] InstanceHeartBeatInterval:5000 IpDeleteTimeout:30000 InstanceHeartBeatTimeOut:15000}] 

SelectAllInstance,param:{Clusters:[DEFAULT] ServiceName:authentication GroupName:nacostest}, result:[{InstanceId: Ip:10.0.3.83 Port:8004 Weight:10 Healthy:true Enable:true Ephemeral:true ClusterName:DEFAULT ServiceName:nacostest@@authentication Metadata:map[idc:shanghai] InstanceHeartBeatInterval:5000 IpDeleteTimeout:30000 InstanceHeartBeatTimeOut:15000} {InstanceId: Ip:10.0.3.45 Port:8004 Weight:10 Healthy:true Enable:true Ephemeral:true ClusterName:DEFAULT ServiceName:nacostest@@authentication Metadata:map[idc:shanghai] InstanceHeartBeatInterval:5000 IpDeleteTimeout:30000 InstanceHeartBeatTimeOut:15000}]

**Comment by youguys** [comment]
感觉是subscribe的call back里面的更新缓存的key， 和SelectInstancesParam从缓存获取的key不一样导致的， 我做了两种尝试
尝试一:
       SelectInstancesParam这个参数初始化的时候，不添加Clusters: []string{"DEFAULT"}参数
       SubscribeParam 这个函数调用也不添加Clusters参数
       这样删除实例之后，call back也正常， 重新获取实例也正常
尝试二:
       SelectInstancesParam这个参数初始化的时候，添加Clusters: []string{"nacosa"}参数
       SubscribeParam 这个函数调用的时候， 添加Clusters: []string{"nacosa"}参数
       这样删除实例会后，call back不调用了

**Comment by 89trillion-liulu** [comment]
我也遇到同样的问题：单机配置了cluster参数，调用不了call back。我断点发现是缓存获取的key不一致导致。
