### ISSUE TITLE
服务注册到nacos，ip地址能否自动发现

### ISSUE THREAD

**Issue by gxxiong** [nacos-group/nacos-sdk-go#526]
namingClient.RegisterInstance(vo.RegisterInstanceParam{
		Ip:          localIp,
		Port:        uint64(ServiceConf.Port),
		ServiceName: NacosConfig.Application.Name,
		Weight:      1,
		Enable:      true,
		Healthy:     true,
		Ephemeral:   true,
		ClusterName: "DEFAULT",       // 默认值DEFAULT
		GroupName:   "DEFAULT_GROUP", // 默认值DEFAULT_GROUP
	}
服务向nacos注册的时候，ip地址除了从配置读取。可以自动发现吗，要是k8s或者dokcer部署可能ip都是变动的

**Comment by binbin0325** [comment]
不可以自动发现，也有代理注册的场景，nacos server 无法获取真实ip。
