### ISSUE TITLE
Golang  client.GetConfig 获取不了Nacos里的配置

### ISSUE THREAD

**Issue by DreamBizideal** [nacos-group/nacos-sdk-go#530]
client.GetConfig 获取不了Nacos里的配置

`content, err := client.GetConfig(vo.ConfigParam{
		DataId: "user-web.yaml",
		Group:  "dev",
	})`

但是client.SearchConfig 可以获取.

`searchPage, _ := client.SearchConfig(vo.SearchConfigParm{
		Search:   "blur",
		DataId:   "user-web.yaml",
		Group:    "dev",
	})`

**Comment by binbin0325** [comment]
sdk 版本是什么？GetConfig时看一下日志

**Comment by jayla25349** [comment]
我也一样，版本v2.1.1

**Comment by binbin0325** [comment]
> 

这是和服务端链接建立失败了，可以看一下服务端是否开启了9848端口

**Comment by hienha** [comment]
**问题**：` read config from both server and cache fail `

确实是9848端口没有启，容器部署的只开放了一个8848端口，SDK日志文件里有明确的报错提示，太过于专注控制台了😅
