### ISSUE TITLE
2.1.2版本是否兼容1.1.1?

### ISSUE THREAD

**Issue by nervending** [nacos-group/nacos-sdk-go#536]
在config_client.go文件 encrypt函数中两个版本存在以下不同
v1.1.1
request.KeyId = "alias/acs/acm" 
v2.1.2
request.KeyId = "alias/acs/mse"

请问我是否可以直接把1.1.1版本升级到2.1.2？升级后有什么注意事项么？

**Comment by binbin0325** [comment]
2.x版本的sdk 对应nacos server 2.x版本

**Comment by pixystone** [comment]
这是配置加密相关的key，没有使用阿里云商业版相关功能不影响
