### ISSUE TITLE
goroutine panic

### ISSUE THREAD

**Issue by youdw** [nacos-group/nacos-sdk-go#540]
v1.1.2

这个是什么原因导致的

goroutine 116 [select]:
net/http.(*persistConn).roundTrip(0xc0005f9560, 0xc000896b80, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:2610 +0x765
net/http.(*Transport).roundTrip(0x212c260, 0xc000c58c00, 0x1569ba0, 0x201, 0xc000c58c00)
        /usr/local/go/src/net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0x212c260, 0xc000c58c00, 0x212c260, 0xc0d5793dc2f77aa7, 0x1d42d8909773)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000c58b00, 0x176f9e0, 0x212c260, 0xc0d5793dc2f77aa7, 0x1d42d8909773, 0x213f180, 0xc000156110, 0xc0d5793dc2f77aa7, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0006553b0, 0xc000c58b00, 0xc0d5793dc2f77aa7, 0x1d42d8909773, 0x213f180, 0xc000156110, 0x0, 0x1, 0xc000655410)
        /usr/local/go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0006553b0, 0xc000c58b00, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:585
github.com/nacos-group/nacos-sdk-go/common/http_agent.post(0xc00069c600, 0x3c, 0xc000655380, 0x80e8, 0xc000655230, 0x91118c3d45a93b, 0xc000586c00, 0x500000000000000)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/common/http_agent/post.go:37 +0x15d
github.com/nacos-group/nacos-sdk-go/common/http_agent.(*HttpAgent).Post(...)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/common/http_agent/http_agent.go:95
github.com/nacos-group/nacos-sdk-go/common/http_agent.(*HttpAgent).Request(0x216f080, 0x15d3da0, 0x4, 0xc00069c600, 0x3c, 0xc000655380, 0x80e8, 0xc000655230, 0x3c, 0xc000597538, ...)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/common/http_agent/http_agent.go:79 +0x445
github.com/nacos-group/nacos-sdk-go/common/nacos_server.(*NacosServer).callConfigServer(0xc0002a0400, 0x15e97f1, 0x17, 0xc000655230, 0xc000655260, 0x15d3da0, 0x4, 0xc0001b4d50, 0x17, 0xc00004a6c0, ...)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/common/nacos_server/nacos_server.go:116 +0xaa7
github.com/nacos-group/nacos-sdk-go/common/nacos_server.(*NacosServer).ReqConfigApi(0xc0002a0400, 0x15e97f1, 0x17, 0xc000655230, 0xc000655260, 0x15d3da0, 0x4, 0x80e8, 0xd0000000150f8a0, 0x1, ...)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/common/nacos_server/nacos_server.go:190 +0x205
github.com/nacos-group/nacos-sdk-go/clients/config_client.(*ConfigProxy).ListenConfig(0xc000128ed8, 0xc000655230, 0x15e2600, 0xc000046690, 0x24, 0xc0000428c0, 0x3c, 0xc000040360, 0x5c, 0x0, ...)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/clients/config_client/config_proxy.go:184 +0x2aa
github.com/nacos-group/nacos-sdk-go/clients/config_client.(*ConfigClient).longPulling.func1(0xc0003d1440, 0x0)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/clients/config_client/config_client.go:417 +0x551
github.com/nacos-group/nacos-sdk-go/clients/config_client.(*ConfigClient).delayScheduler(0xc000128ea0, 0xc000159270, 0x989680, 0x15fac64, 0x1, 0xc00000ed08)
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/clients/config_client/config_client.go:353 +0x47
created by github.com/nacos-group/nacos-sdk-go/clients/config_client.(*ConfigClient).listenConfigExecutor.func1
        /go/pkg/mod/github.com/nacos-group/nacos-sdk-go@v1.1.2/clients/config_client/config_client.go:369 +0x1d8

**Comment by binbin0325** [comment]
panic的错误消息提供一下

**Comment by binbin0325** [comment]
太久没有回复，暂时关闭
