### ISSUE TITLE
配置热更新失败

### ISSUE THREAD

**Issue by brzyangg** [nacos-group/nacos-sdk-go#547]
### What version of nacos-sdk-go are you using?
v2.1.2
### What version of nacos-sever are you using?
2.1.0.2
### What version of Go are you using (`go version`)?
go 1.17
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
If possible, provide a recipe for reproducing the error.
在nacos配置页面更新配置后，客户端是否可以更新缓存读到最新配置
现在的现象是cache没有更新
### What did you expect to see?
期望页面更新后，client端可以更新缓存
### What did you see instead?
缓存未更新，并且有错误日志
```
2022-12-08T17:52:01.914+0800    ERROR   rpc/rpc_client.go:517   Send request fail, request=ConfigQueryRequest, body={"requestId":"","group":"qdata","dataId":"vehicle_plan","tenant":"a53d293b-8d4b-4bb5-8320-8c5c52302f4e","module":"config","tag":""}, retryTimes=0, error=client not connected, current status:UNHEALTHY

```

**Comment by binbin0325** [comment]
客户端创建监听了吗？参考：https://github.com/nacos-group/nacos-sdk-go/blob/master/README_CN.md?plain=1#L335

**Comment by brzyangg** [comment]
我解决了这个问题，我之前用的一个全局变量来使用configClient，结果第一次 GetConfig 的时候是好的，第二次会报如上错误，并使用 cache，最后我每次 GetConfig 之前都 NewClient ，以此解决了这个问题

**Comment by binbin0325** [comment]
> 我解决了这个问题，我之前用的一个全局变量来使用configClient，结果第一次 GetConfig 的时候是好的，第二次会报如上错误，并使用 cache，最后我每次 GetConfig 之前都 NewClient ，以此解决了这个问题

这样做肯定不对的，configClient只需要初始化一次。 错误日志中的提示是说明客户端和服务端未创建连接，每次GetConfig后没有主动Close吧

**Comment by brzyangg** [comment]
> > 我解决了这个问题，我之前用的一个全局变量来使用configClient，结果第一次 GetConfig 的时候是好的，第二次会报如上错误，并使用 cache，最后我每次 GetConfig 之前都 NewClient ，以此解决了这个问题
> 
> 这样做肯定不对的，configClient只需要初始化一次。 错误日志中的提示是说明客户端和服务端未创建连接，每次GetConfig后没有主动Close吧

没有主动close

**Comment by binbin0325** [comment]
可以关注下日志，看一下链接是如何中断的

**Comment by binbin0325** [comment]
没有反馈，时间过长，暂时关闭
