### ISSUE TITLE
Is there any possible that don't print the log?

### ISSUE THREAD

**Issue by banishee** [nacos-group/nacos-sdk-go#55]
有什么办法不输出log吗

**Comment by lzp0412** [comment]
你的意思是不输出日志到文件？可以考虑将日志文件输出到/dev/null?

**Comment by banishee** [comment]
> 你的意思是不输出日志到文件？可以考虑将日志文件输出到/dev/null?

是的，谢谢

**Comment by Jekinnnnnn** [comment]
试了一下不行，提示 write error: error getting log file info: stat /dev/null//nacos-sdk.log: not a directory
