### ISSUE TITLE
当一个group有3000个配置时……

### ISSUE THREAD

**Issue by 137-rick** [nacos-group/nacos-sdk-go#562]
### What version of nacos-sdk-go are you using?
v1.0.9

### What version of nacos-sever are you using?
v2.x

### What version of Go are you using (`go version`)?
1.18

### What operating system (Linux, Windows, …) and version?
linux

### What did you do?
If possible, provide a recipe for reproducing the error.

config, err := this.client.SearchConfig(vo.SearchConfigParam{
		Search:   "blur",
		PageNo:   pageNo,
		PageSize: pageSize,
	})
	if err != nil {
		logs.Error(logCtx, "nacos_getpage_error", zap.Error(err))
		return nil, err
	}
遍历一个group有3000个配置的时候使用这个代码，会因为循环请求服务端偶尔连接失败（nacos服务端有并发以及限流）
导致全量刷新流程失败，程序会从头再请求重新刷新

### What did you expect to see?
期望底层能有失败重试请求功能，重试请求可以自定义间隔

**Comment by binbin0325** [comment]
在SearchConfig中你可以通过设置pageNo以及pageSize 来实现分页查询，从而避免限流。

**Comment by 137-rick** [comment]
> 在SearchConfig中你可以通过设置pageNo以及pageSize 来实现分页查询，从而避免限流。

单次数据量一次256条，做了分页请求，但是循环过程中底层请求因为阿里云限速，每次都会失败在第15页左右，导致后续业务无法进行。

这里我可以自己实现重试功能比如search失败 等待1秒后 重新search当前页
或者驱动底层对限速或不稳定网络做兼容，失败延迟重试

但是我觉得这里有些不太合理，有其他解决方式吗

**Comment by binbin0325** [comment]
你可以考虑这样使用的场景是否正确， 为什么要读取这么多配置？

**Comment by 137-rick** [comment]
这是因为原先的架构使用了一个agent将全部项目配置落地磁盘，方便其他项目直接使用
好处是每个项目不用自己集成，缺点就是全量刷效果不好

**Comment by binbin0325** [comment]
> 

看起来是历史原因导致使用的不太合理，关于限流的问题只能你在使用方面去处理了。
