### ISSUE TITLE
nacos v2.1.3 NotLoadCacheAtStart = false的时候订阅会失效,所有客户端会挂掉

### ISSUE THREAD

**Issue by txbao** [nacos-group/nacos-sdk-go#568]
最近项目突然重新构建后，客户端会挂掉，查了很久问了不少大佬，发现NotLoadCacheAtStart = false的时候订阅会失效，从而导致客户端挂掉。测试项目基于go-zero , https://github.com/zeromicro/zero-contrib/tree/main/zrpc/registry/nacos。希望官方提供修复这个问题方案。谢谢！

**Comment by binbin0325** [comment]
没有复现出来，客户端全挂掉是进程停了的意思吗？

**Comment by txbao** [comment]
是客户端链接不了服务端，报“rpc error: code = DeadlineExceeded desc = context deadline exceeded”

**Comment by txbao** [comment]
> 没有复现出来，客户端全挂掉是进程停了的意思吗？

是客户端链接不了服务端，报“rpc error: code = DeadlineExceeded desc = context deadline exceeded”

**Comment by binbin0325** [comment]
> 

这是超时错误，可以检查下是否出现过服务端重启/宕机，客户端日志中应该会有请求失败/重新建立连接等日志
