### ISSUE TITLE
创建nacos client时，如果endpoint地址或accesskey鉴权失败，建议返回错误；

### ISSUE THREAD

**Issue by skyterra** [nacos-group/nacos-sdk-go#571]
当前，mongo，redis驱动采用DialXXX()的方式，创建client，创建client过程中，会尝试连接server，如果连接失败，会报错；建议nacos sdk采用这种方式，如果创建的client时，传入的addr, ak, sk非法，直接报错，避免程序后期GetConfig()时再报错

**Comment by binbin0325** [comment]
设计思路不一样，当nacos sdk创建失败也是可以读取本地缓存继续运行，防止由于nacos server挂掉而影响服务不可用。
