### ISSUE TITLE
如何感知实例下线？

### ISSUE THREAD

**Issue by tuhao1020** [nacos-group/nacos-sdk-go#572]
通过Subscribe订阅某个服务后，貌似只能在实例上线和变更时进入回调，实例下线不会触发，这是bug还是设计本来如此？
```
namingClient.Subscribe(&vo.SubscribeParam{
		ServiceName: "service-provider",
		Clusters:    []string{"DEFAULT"},
		GroupName:   "DEFAULT_GROUP",
		SubscribeCallback: func(services []model.Instance, err error) {
			......
		},
	})
```

**Comment by binbin0325** [comment]
有两种情况：
1。如果只有一个实例的话，需要关注创建客户端的参数‘UpdateCacheWhenEmpty’，当UpdateCacheWhenEmpty=false，实例列表为空时不会进行回调。 
2. 无论UpdateCacheWhenEmpty=false/true,只要实例列里不为空，有实例下线就会回调的（如果没有回调请提供日志）。

**Comment by brczo** [comment]
这个sdk的设计疑惑在于：客户端是用拉的方式获取实例状态，默认1秒轮询。意味着，如果服务异常下线，最少要1秒才能知道。

**Comment by binbin0325** [comment]
> 这个sdk的设计疑惑在于：客户端是用拉的方式获取实例状态，默认1秒轮询。意味着，如果服务异常下线，最少要1秒才能知道。

服务端也有主动推送的

**Comment by rogerBridge** [comment]
> > 这个sdk的设计疑惑在于：客户端是用拉的方式获取实例状态，默认1秒轮询。意味着，如果服务异常下线，最少要1秒才能知道。
> 
> 服务端也有主动推送的

服务端的主动推送, 客户端通过什么方式感知呢?
