### ISSUE TITLE
2.1版本nacos临时实例目前不支持同分组下创建多端口？

### ISSUE THREAD

**Issue by vikiea** [nacos-group/nacos-sdk-go#579]
开启临时实例后，默认走grpc代理，但是如果我一个服务下创建多个端口的实例，比如分别创建8080和9090的端口，由于应用名和分组相同，第二次创建的会把前一端口实例覆盖掉，导致实际只能创建一个实例。请问这是有意为之还是有什么特殊的考虑。可以做到支持多个端口吗

**Comment by binbin0325** [comment]
由于2.0以后客户端和服务端通过grpc建立连接，在服务端会通过连接的id来绑定服务，所以当同一个链接多次注册实例会覆盖。
在下一个版本客户端会支持批量注册，即可支持多个端口。目前代码已经合并可以参考：https://github.com/nacos-group/nacos-sdk-go/blob/master/example/service/main.go#L85
