### ISSUE TITLE
nacos-sdk-go问题收集

### ISSUE THREAD

**Issue by lzp0412** [nacos-group/nacos-sdk-go#58]
**此issue的目的**

- 收集用户使用nacos-sdk-go过程遇到的问题
- 收集用户对nacos-sdk-go的建议，包括功能、代码架构等

我们将根据您反馈，规划nacos-sdk-go的开发计划，一起解决目前存在的问题，完善nacos-sdk-go。

再次感谢您的参与！！！

**Comment by lidaoyang** [comment]
naco-sdk-go v0.3.2版本，nacos_server.go中引用的 github.com/satori/go.uuid包，再使用dep ensure 时会下载v1.2.0的包到vendor中，导致nacos_server.go中 uid, err := uuid.NewV4()报错，看了一下github.com/satori/go.uuid中没有v1.2.1的tag所以就下载了v1.2.0的包，建议直接指定到master上或者最新的commit_id上

**Comment by pahxgh** [comment]
nacos-sdk-go v0.3.1版本，同时监听3个命名空间下25个dataid时，会导致cpu飙升到20~25%

**Comment by cnlisea** [comment]
问题：开始监听随机(随机0-999 + 54951)udp端口，当端口已被占用，重试生成的端口，会因为每次都根据当前时间戳因子生成随机数相同，而重试失效
![image](https://user-images.githubusercontent.com/20754102/84609618-46b3f300-aeea-11ea-88ae-6a2145498b31.png)
版本：v0.3.1

**Comment by michiel-yang** [comment]
配置监听时不能自己指定gourp？
[client.PublishConfig] publish config failed:[500] caused: invalid group

**Comment by lzp0412** [comment]
@michiel-yang 可以的，是group字符有非法字符吧？

**Comment by michiel-yang** [comment]
> @michiel-yang 可以的，是group字符有非法字符吧？

确实是有非法字符，改正后就好了

**Comment by michiel-yang** [comment]
能开发一个获取namespace下所有服务名称列表的接口吗

**Comment by lzp0412** [comment]
@michiel-yang 可以先提个issue，我们社区再讨论评估下
