### ISSUE TITLE
[配置中心] 模块 在连接断开重连后没有自动恢复订阅

### ISSUE THREAD

**Issue by wangdongyun** [nacos-group/nacos-sdk-go#580]
#### 复现流程
执行listen 操作client.ListenConfig, 关键代码
`
sc := []constant.ServerConfig{
   *constant.NewServerConfig("nacos-server-ip", 8848),
}

client.ListenConfig(vo.ConfigParam{
   DataId: "xx.yaml",
   Group:  "xxgroup",
   OnChange: func(namespace, group, dataId, data string) {
      fmt.Println("收到内容变更推送事件", data)
   },
})
`

![image](https://user-images.githubusercontent.com/6995309/221740632-79902070-9e6f-4fee-a936-8ab2928b52be.png)

重启服务端 nacos
![image](https://user-images.githubusercontent.com/6995309/221740811-60e5cca3-d47e-4889-874b-e014d0ee0e4c.png)
3. 等待<5分钟，会发现重新订阅上（轮询机制）这里是5分钟的轮询机制生效的，客户端间隔5分钟会做一次全量的batch listen。
预期是立刻可以订阅上

![image](https://user-images.githubusercontent.com/6995309/221740907-e09d194b-0ed0-4b6a-910c-2dd7640fa968.png)

**Comment by binbin0325** [comment]
https://github.com/nacos-group/nacos-sdk-go/pull/596
