### ISSUE TITLE
[rpcclient]  死锁问题导致断开重连失败，一直是unhealthy 阶段

### ISSUE THREAD

**Issue by wangdongyun** [nacos-group/nacos-sdk-go#581]
### 复现流程
1. 执行下面命令，代表创建2000个connection【对应2000个rpcclient/namingclient】，每一个namingclient执行的逻辑
   1.1 注册一个服务，并且订阅自身
   1.2下面的脚本会注册2000个服务，服务名 10benchmark[0-1999]
        nohup ./nacos_bench --port 9090  --serviceName 10benchmark --linkNums 2000 &
2. 使用3台机器，上面的命令执行3次，执行过后，nacos 服务实例数量是 6k
3. Nacos 3台机器，机器配置 2core 4g
4. 中间执行若干次重启nacos 节点，最终看到 nacos 服务实例数量<6k, 问题复现，说明有些客户端没有重连上，如果没有复现，多执行几次重启，或者增加新的客户端创建更多的连接，亲测可行性。

### 故障时候=>客户端故障时表现
connection的状态为 UNHEALTHY，后台线程没有进行重连

> nacos-sdk.log:2023-02-23T19:30:28.199Z  ERROR   naming_client/service_info_updater.go:72        QueryList return error!serviceName:206benchmark910 cluster: err:client not connected, current status:UNHEALTHY
nacos-sdk.log:2023-02-23T19:30:28.898Z  ERROR   rpc/rpc_client.go:550   Send request fail, request=ServiceQueryRequest, body={"requestId":"","namespace":"public","serviceName":"206benchmark910","groupName":"DEFAULT_GROUP","module":"naming","clusters":"","healthyOnly":false,"udpPort":0}, retryTimes=0, error=client not connected, current status:UNHEALTHY
nacos-sdk.log:2023-02-23T19:30:28.999Z  ERROR   rpc/rpc_client.go:550   Send request fail, request=ServiceQueryRequest, body={"requestId":"","namespace":"public","serviceName":"206benchmark910","groupName":"DEFAULT_GROUP","module":"naming","clusters":"","healthyOnly":false,"udpPort":0}, retryTimes=1, error=client not connected, current status:UNHEALTHY
nacos-sdk.log:2023-02-23T19:30:29.099Z  ERROR   rpc/rpc_client.go:550   Send request fail, request=ServiceQueryRequest, body={"requestId":"","namespace":"public","serviceName":"206benchmark910","groupName":"DEFAULT_GROUP","module":"naming","clusters":"","healthyOnly":false,"udpPort":0}, retryTimes=2, error=client not connected, current status:UNHEALTHY

### 这个问题还是十分严重
影响面： 假定服务端nacos 故障，导致连接不能重新建立上，注册与订阅全部有问题，包括配置模块

**Comment by wangdongyun** [comment]
问题原因
![image](https://user-images.githubusercontent.com/6995309/221741810-b88b4dee-2d3b-420b-9b9c-991d1f7f3aaf.png)

**Comment by wangdongyun** [comment]
如何验证修复了？
1. 使用两个版本的客户端端
2. 根据上面的流程 进行复现
3. 最终发现 老客户端大量的连接没有重新建立上， 新客户端连接全部修复

**Comment by tonglin96** [comment]
遇到相同的问题, 偶现现象
```
2023-03-03T12:49:23.130+0800    ERROR   naming_client/service_info_updater.go:72        QueryList return error!serviceName:aa cluster: err:client not connected, current status:UNHEALTHY
github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.(*RpcClient).Request
        /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/common/remote/rpc/rpc_client.go:474
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_grpc.(*NamingGrpcProxy).requestToServer
        /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_grpc/naming_grpc_proxy.go:87
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_grpc.(*NamingGrpcProxy).QueryInstancesOfService
        /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_grpc/naming_grpc_proxy.go:148
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*NamingProxyDelegate).QueryInstancesOfService
        /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_proxy_delegate.go:89
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*ServiceInfoUpdater).updateServiceNow
        /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/service_info_updater.go:69
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*ServiceInfoUpdater).asyncUpdateService.func1.1
        /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/service_info_updater.go:59
```

**Comment by wangdongyun** [comment]
这个在服务端极端故障下，还是很严重的！

**Comment by wangdongyun** [comment]
> 遇到相同的问题, 偶现现象
> 
> ```
> 2023-03-03T12:49:23.130+0800    ERROR   naming_client/service_info_updater.go:72        QueryList return error!serviceName:aa cluster: err:client not connected, current status:UNHEALTHY
> github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.(*RpcClient).Request
>         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/common/remote/rpc/rpc_client.go:474
> github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_grpc.(*NamingGrpcProxy).requestToServer
>         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_grpc/naming_grpc_proxy.go:87
> github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_grpc.(*NamingGrpcProxy).QueryInstancesOfService
>         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_grpc/naming_grpc_proxy.go:148
> github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*NamingProxyDelegate).QueryInstancesOfService
>         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_proxy_delegate.go:89
> github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*ServiceInfoUpdater).updateServiceNow
>         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/service_info_updater.go:69
> github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*ServiceInfoUpdater).asyncUpdateService.func1.1
>         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/service_info_updater.go:59
> ```

偶发报这个错误没有问题，关键是不能 自己恢复

**Comment by tonglin96** [comment]
> > 遇到相同的问题, 偶现现象
> > ```
> > 2023-03-03T12:49:23.130+0800    ERROR   naming_client/service_info_updater.go:72        QueryList return error!serviceName:aa cluster: err:client not connected, current status:UNHEALTHY
> > github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.(*RpcClient).Request
> >         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/common/remote/rpc/rpc_client.go:474
> > github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_grpc.(*NamingGrpcProxy).requestToServer
> >         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_grpc/naming_grpc_proxy.go:87
> > github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_grpc.(*NamingGrpcProxy).QueryInstancesOfService
> >         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_grpc/naming_grpc_proxy.go:148
> > github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*NamingProxyDelegate).QueryInstancesOfService
> >         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/naming_proxy_delegate.go:89
> > github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*ServiceInfoUpdater).updateServiceNow
> >         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/service_info_updater.go:69
> > github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.(*ServiceInfoUpdater).asyncUpdateService.func1.1
> >         /var/lib/jenkins/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.1.0/clients/naming_client/service_info_updater.go:59
> > ```
> 
> 偶发报这个错误没有问题，关键是不能 自己恢复

是的，这个问题很严重，其实tcp连接已经建立，但是代码未将连接状态修正。目前我在上层做了client的重新建立，尝试解决这个问题。

**Comment by binbin0325** [comment]
https://github.com/nacos-group/nacos-sdk-go/pull/596
