### ISSUE TITLE
clusters问题导致本地缓存的service没有更新

### ISSUE THREAD

**Issue by brczo** [nacos-group/nacos-sdk-go#584]
### What version of nacos-sdk-go are you using?
2.1.3
### What version of nacos-sever are you using?
2.0.1
### What version of Go are you using (`go version`)?
1.16
### What operating system (Linux, Windows, …) and version?
all
#### 源码里存在这样的注释：
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/48399641/223627419-9b07647c-cb46-4d68-b33b-ba1f5d9fee6a.png">

#### 于是设置了clusters的值
<img width="524" alt="image" src="https://user-images.githubusercontent.com/48399641/223627977-4e38ac75-fddb-41ec-aeac-1712cdcbc209.png">

#### 在初次获取service时，会缓存sercice
<img width="954" alt="image" src="https://user-images.githubusercontent.com/48399641/223628179-cb4df80a-6503-47f4-b648-d57e35f0140d.png">

**此时的cacheKey是带Default的，长这样：SERVICE@@CUS.grpc@@DEFAULT**

#### 下面的方法会隔1秒轮询获取service，并缓存
```
asyncUpdateService()
```
抓包发现，返回的clusters为空
<img width="877" alt="image" src="https://user-images.githubusercontent.com/48399641/223629022-f793bc31-e443-45f4-ab20-3cf9c22a5c6c.png">
**于是把service缓存在不带DEFAULT的key里面**，长这样：SERVICE@@CUS.grpc

### 这样会存在如下问题：

**上游容器化的服务重启更新，IP发生了变化，下游服务通过缓存拿到的却还是旧的IP，因为key为SERVICE@@CUS.grpc@@DEFAULT的service值并没有更新，service值被更新到了这个key：SERVICE@@CUS.grpc上。下游服务调不通上游服务。**

**Comment by binbin0325** [comment]
已修复，pr: https://github.com/nacos-group/nacos-sdk-go/pull/578/files

**Comment by brczo** [comment]
什么时候更新tag，我赶紧更新下公司线上服务
