### ISSUE TITLE
[naming 模块] connection 恢复后，注册的实例没有恢复

### ISSUE THREAD

**Issue by wangdongyun** [nacos-group/nacos-sdk-go#587]
###  如何复现
参考这个复现流程 https://github.com/nacos-group/nacos-sdk-go/issues/581

我们启动一个进程，注册2000个实例，服务端nacos 反复注入故障，最终，nacos 上注册实例数量<2000

### 描述
1. 所有的链接已经恢复了
![image](https://user-images.githubusercontent.com/6995309/224698689-46eb6709-81ac-491d-a1c6-59e279b4ee29.png)
2. 关键日志

> nacos-sdk-2023-02-27T12-37-57.295.log:2023-02-27T12:36:51.627Z  WARN    naming_grpc/connection_event_listener.go:105    e163e752-06ca-48e5-a501-623c00f7ec34 redo register service:237benchmark_fix649 groupName:DEFAULT_GROUP faild:client not connected, current status:UNHEALTHY

![image](https://user-images.githubusercontent.com/6995309/224699556-70bd0e38-44e0-48c8-9493-2035645fd5d3.png)

我们临时增加了日志的埋点

下面的方法来在于 rpcclient.go#Request 方法

![image](https://user-images.githubusercontent.com/6995309/224701972-452e093d-96cf-4e95-8eed-9d161635539b.png)

在出现问题时候，出现下面的日志
> nacos-sdk-2023-02-27T12-37-57.295.log:2023-02-27T12:36:50.377Z  INFO    rpc/rpc_client.go:555   e163e752-06ca-48e5-a501-623c00f7ec34 line 540 status to be %!s(rpc.RpcClientStatus=2)

从时间上来看，在执行redoregister之前，状态已经是unhealty了

这里的逻辑: 假如某个request 报错，会短暂置为 unhealty，后面假如health check 成功，就重新恢复到 healthy 状态

到底是执行哪个request报错呢？下面的代码，执行 redosubscribe 请求报错, 然后将connection 状态置为unhealty
![image](https://user-images.githubusercontent.com/6995309/224774346-a6214005-917d-4408-b187-a05926eebf18.png)

+++++这里连接没有真正断开，真正断开，会重新触发redo 操作>>>>>>

综合描述:
触发条件：连接频繁断开与重连过程，redo register 失败没有做补偿
### 版本
在2.1.4的基础上

**Comment by binbin0325** [comment]
客户端用的版本是多少？
