### ISSUE TITLE
Is it necessary to make a channel with a such large buffer size?

### ISSUE THREAD

**Issue by cro4k** [nacos-group/nacos-sdk-go#593]
https://github.com/nacos-group/nacos-sdk-go/blob/73c4f3632d50fcbd80258430566c1b84fd0fea68/common/remote/rpc/grpc_client.go#L54

导致很多没必要的内存分配

**Comment by binbin0325** [comment]
Yes, it's not necessary here, I'll optimize it later

**Comment by zepen** [comment]
我也遇到这个问题，导致在4gb的机器上无法启动，出现内存溢出问题

**Comment by binbin0325** [comment]
> 我也遇到这个问题，导致在4gb的机器上无法启动，出现内存溢出问题

你这个问题和当前issue没关系，可以用pprof看下内存溢出的根因

**Comment by wangdongyun** [comment]
> https://github.com/nacos-group/nacos-sdk-go/blob/73c4f3632d50fcbd80258430566c1b84fd0fea68/common/remote/rpc/grpc_client.go#L54
> 
> 导致很多没必要的内存分配

为啥我自己模拟没有问题，make(ch, math.maxInt) 到底会不会真实申请这么大的内存
