### ISSUE TITLE
Nacos如何监听Group下所有dataId的变化？基于dataId的监听粒度在数据量很大的时候会导致长链接的客户端很多，影响性能

### ISSUE THREAD

**Issue by selfSpallation** [nacos-group/nacos-sdk-go#607]

**Comment by binbin0325** [comment]
不会的，无论是1.x还是2.x 都是一个长链接中会监听多个dataId

**Comment by selfSpallation** [comment]
> 不会的，无论是1.x还是2.x 都是一个长链接中会监听多个dataId

一个长链接监听多个dataId是否也会影响性能？

**Comment by selfSpallation** [comment]
> 

一个长链接监听多个dataId这个是在ListenConfig里面怎么配置呢？

**Comment by selfSpallation** [comment]
> 不会的，无论是1.x还是2.x 都是一个长链接中会监听多个dataId

一个长链接监听多个dataId这个是在ListenConfig里面怎么配置呢？

**Comment by binbin0325** [comment]
> 一个长链接监听多个dataId这个是在ListenConfig里面怎么配置呢？

不需要配置，可以看一下监听配置的相关代码
