### ISSUE TITLE
关于RPC端口的默认值问题

### ISSUE THREAD

**Issue by ppzz** [nacos-group/nacos-sdk-go#610]
nacos非深度使用用户，对其中的一些机制还不太明确。

我在测试这个库的时候发现RPC端口是默认http端口+1000得到的

比如：我默认使用 8848，内部使用了9848作为rpc连接的端口

当我某次在无意下改了 nacos 服务的 rpc 端口，但是我并不明确的知道 [nacos-sdk-go](https://github.com/nacos-group/nacos-sdk-go) 会使用 9848 作为rpc的端口，导致程序无法建立正确的rpc连接。

请问在nacos的世界里，rpc 端口 = http端口+1000  这条规则 是通行的默认设计吗？是否还有其他这样的默认设计？或者，我们可以将rpc端口号显示的传入 [nacos-sdk-go](https://github.com/nacos-group/nacos-sdk-go) 库中？

**Comment by binbin0325** [comment]
1. grpc端口号+1000 是默认规则，可以参考官网：https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-compatibility.html
2. 也可以显示的指定grpc端口号，参考：https://github.com/nacos-group/nacos-sdk-go/blob/master/common/constant/config.go#L26

**Comment by ppzz** [comment]
很棒，是我没有认真读文档。
good job

-----

我还是有一点疑问，为何会同时需要两个端口： http / grpc 
只使用一种协议通信不行吗？

**Comment by xiaoxfan** [comment]
nacos只使用http端口不行吗
