### ISSUE TITLE
client not connected, current status:STARTING

### ISSUE THREAD

**Issue by xiaobin** [nacos-group/nacos-sdk-go#623]
### What version of nacos-sdk-go are you using?
v2.2.2
### What version of nacos-sever are you using?
2.2.2
### What version of Go are you using (`go version`)?
1.20.4

### What operating system (Linux, Windows, …) and version?
MAC

### What did you do?
If possible, provide a recipe for reproducing the error.
注册服务时：success, err := client.RegisterInstance(param)
返回失败：client not connected, current status:STARTING

并且success = false

**Comment by binbin0325** [comment]
检查nacos server端的9848端口是否打开

**Comment by xiaobin** [comment]
> 

感谢。已oK.
