### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by tonglin96** [nacos-group/nacos-sdk-go#627]
### What version of nacos-sdk-go are you using?
2.1.3
### What version of nacos-sever are you using?
2.0.4
### What version of Go are you using (`go version`)?
1.19
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
`panic: interface conversion: rpc_response.IResponse is *rpc_response.ErrorResponse, not *rpc_response.SubscribeServiceResponse`

**Comment by binbin0325** [comment]
fixed: https://github.com/nacos-group/nacos-sdk-go/issues/576
