### ISSUE TITLE
read config from both server and cache fail when I call GetConfig

### ISSUE THREAD

**Issue by betwins** [nacos-group/nacos-sdk-go#648]
### What version of nacos-sdk-go are you using?
v2.2.3
### What version of nacos-sever are you using?
v2.1.2
### What version of Go are you using (`go version`)?
v1.19
### What operating system (Linux, Windows, …) and version?
win10
### What did you do?
the reproduce code: 
`
       sc := []constant.ServerConfig{
		*constant.NewServerConfig("127.0.0.1", 
                8782, 
                constant.WithContextPath("/nacos"), 
                constant.WithScheme("http")),
	}`

	//create ClientConfig
	cc := constant.ClientConfig{
		TimeoutMs:           5000,
		NotLoadCacheAtStart: true,
		LogDir:              "/tmp/nacos/log",
		CacheDir:            "/tmp/nacos/cache",
		LogLevel:            "debug",
	}

	// create config client
	configClient, err := clients.NewConfigClient(
		vo.NacosClientParam{
			ClientConfig:  &cc,
			ServerConfigs: sc,
		},
	)

	if err != nil {
		panic(err.Error())
	}

	content, err := configClient.GetConfig(vo.ConfigParam{
		DataId: "gme-test",
		Group:  "DEFAULT_GROUP",
	})

	if err != nil {
		panic(err.Error())
	}`	       
configClient.GetConfig return err and 
the err desc is read config from both server and cache fail, err=failed to read config cache file:/tmp/nacos/cache\c

the dataId is configured on nacos
![image](https://github.com/nacos-group/nacos-sdk-go/assets/79825922/749a8822-697c-4a64-bd71-5b9a4e7be7b6)

### What did you expect to see?
configClient.GetConfig call success

**Comment by binbin0325** [comment]
Check the logs in the LogDir directory

**Comment by betwins** [comment]
我开启了鉴权，并在防火墙开放了我nacos使用的端口号58848 59848， 可以用nacos/nacos登录到管理台。但是我的代码在更早的地方出现的nacos错误日志，代码如下：
`	sc := []constant.ServerConfig{
		*constant.NewServerConfig("127.0.0.1", 59848, constant.WithContextPath("/nacos")),
	}

	//create ClientConfig
	cc := constant.ClientConfig{
		TimeoutMs:           5000,
		NotLoadCacheAtStart: true,
		Username:            "nacos",
		Password:            "nacos",
		LogDir:              "/tmp/nacos/log",
		CacheDir:            "/tmp/nacos/cache",
		LogLevel:            "debug",
	}

	// create config client
	configClient, err := clients.NewConfigClient(
		vo.NacosClientParam{
			ClientConfig:  &cc,
			ServerConfigs: sc,
		},
	)

	if err != nil {
		log.Fatalln("连接配置中心失败 err: {}", err.Error())
		return
	}

	content, err := configClient.GetConfig(vo.ConfigParam{
		DataId: "gme-test",
		Group:  "DEFAULT_GROUP",
	})

	if err != nil {
		log.Fatalln("读取配置中心配置失败, err: ", err.Error())
		return
	}`

当断点执行完clients.NewConfigClient，其err返回值为nil, 但我发现nacos-sdk.log里产生了一条错误日志
`2023-08-23T15:56:17.435+0800	ERROR	nacos_server/nacos_server.go:89	login in err:Post "http://59.56.77.17:59848/nacos/v1/auth/users/login": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0f\x00\x01\x00\x00E\a\x00\x00\x00\x00\x00\x7f\xff\xff\xff\x00\x00\x00\x01Unexpected"
`

我有几个疑问：
1. 我使用的是nacos-go-sdk 2.2.3版本, 不是应该使用http2协议吗？为什么上面日志显示的是HTTP/1.x
2. 另外，看API的路径也是v1版本，我的代码有什么错误吗？

**Comment by binbin0325** [comment]
NewServerConfig 时设置http端口就可以，默认会自动加1000做为grpc端口
