### ISSUE TITLE
why sleep 100MS?

### ISSUE THREAD

**Issue by xvpenghao** [nacos-group/nacos-sdk-go#651]
https://github.com/nacos-group/nacos-sdk-go/blob/b51d87d10b8770faa8fa15737efa14dcd18d35d2/common/remote/rpc/grpc_client.go#L166C29-L166C29

**Comment by binbin0325** [comment]
The connection is established asynchronously. Ensure that the server can complete the connection establishment

**Comment by xvpenghao** [comment]
> The connection is established asynchronously. Ensure that the server can complete the connection establishment

Sleep 100MS Can it be optimized later. because it affected service restart speed .

**Comment by binbin0325** [comment]
you consider initializing the client after the service starts,  welcome to join dingding group communication:23191211
