### ISSUE TITLE
是不是不能通过一个grpc链接去注册多个服务，貌似同一个链接注册，会直接覆盖掉第一个服务

### ISSUE THREAD

**Issue by dimon-cmd** [nacos-group/nacos-sdk-go#658]

**Comment by binbin0325** [comment]
可以使用批量注册 client.BatchRegisterInstance

**Comment by li-jin-gou** [comment]
@binbin0325  我们支持 hertz 服务发现，在写单测的过程中，发现使用了同一个 client 并且是 grpc 的话服务会被覆盖，这是 feature 嘛
