### ISSUE TITLE
Some unsupported parameters appear in the README.md

### ISSUE THREAD

**Issue by palp1tate** [nacos-group/nacos-sdk-go#660]
The latest nacos-sdk-go：
![image](https://github.com/nacos-group/nacos-sdk-go/assets/120303802/2735ad0d-3110-4360-80a7-baa7fcb0bbd1)
It no longer supports the RotateTime and MaxAge parameter.
The README.md  blow:
![image](https://github.com/nacos-group/nacos-sdk-go/assets/120303802/ee8abd00-5ff8-481f-bc9a-42fb8a0e56b8)

**Comment by binbin0325** [comment]
Can you submit a pr to modify the readme

**Comment by palp1tate** [comment]
It's my pleasure.I'll do it soon.

**Comment by palp1tate** [comment]
> Can you submit a pr to modify the readme

It's my pleasure.I'll do it soon.

**Comment by palp1tate** [comment]
> Can you submit a pr to modify the readme

I have done it.Hope your merging.
