### ISSUE TITLE
使用v2版本导致无法读取到nacos服务端的配置信息

### ISSUE THREAD

**Issue by thewisecirno** [nacos-group/nacos-sdk-go#664]
``` go
package main

import (
	"fmt"
	"github.com/nacos-group/nacos-sdk-go/clients"
	"github.com/nacos-group/nacos-sdk-go/common/constant"
	"github.com/nacos-group/nacos-sdk-go/vo"
)

func main() {
	// 至少一个ServerConfig
	serverConfigs := []constant.ServerConfig{
		{
			IpAddr: "192.168.1.109",
			Port:   8848,
		},
	}

	clientConfig := constant.ClientConfig{
		NamespaceId:         "0484a732-86ac-4e39-a6c0-f478b7a76549", // 如果需要支持多namespace，我们可以创建多个client,它们有不同的NamespaceId。当namespace是public时，此处填空字符串。
		TimeoutMs:           5000,
		NotLoadCacheAtStart: true,
		LogDir:              "tmp/nacos/log",
		CacheDir:            "tmp/nacos/cache",
	}

	// 创建动态配置客户端
	client, err := clients.CreateConfigClient(map[string]interface{}{
		"serverConfigs": serverConfigs,
		"clientConfig":  clientConfig,
	})
	if err != nil {
		panic(err)
	}
	config, err := client.GetConfig(vo.ConfigParam{
		DataId: "test-nacos.yaml",
		Group:  "test",
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(config)
}
``` 

如果使用v2版本会报错：
![image](https://github.com/nacos-group/nacos-sdk-go/assets/113567699/990b4ee3-d73f-4631-8d36-f7c7616a8ef9)

但是使用v1版本可以成功读取配置信息：
![image](https://github.com/nacos-group/nacos-sdk-go/assets/113567699/09e4101f-55a4-4fdb-ba91-9cda572a449d)

**Comment by binbin0325** [comment]
报错信息看一下，配置的log和cache 路径 tmp前面缺少“/”

**Comment by palp1tate** [comment]
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"github.com/nacos-group/nacos-sdk-go/clients"
> 	"github.com/nacos-group/nacos-sdk-go/common/constant"
> 	"github.com/nacos-group/nacos-sdk-go/vo"
> )
> 
> func main() {
> 	// 至少一个ServerConfig
> 	serverConfigs := []constant.ServerConfig{
> 		{
> 			IpAddr: "192.168.1.109",
> 			Port:   8848,
> 		},
> 	}
> 
> 	clientConfig := constant.ClientConfig{
> 		NamespaceId:         "0484a732-86ac-4e39-a6c0-f478b7a76549", // 如果需要支持多namespace，我们可以创建多个client,它们有不同的NamespaceId。当namespace是public时，此处填空字符串。
> 		TimeoutMs:           5000,
> 		NotLoadCacheAtStart: true,
> 		LogDir:              "tmp/nacos/log",
> 		CacheDir:            "tmp/nacos/cache",
> 	}
> 
> 	// 创建动态配置客户端
> 	client, err := clients.CreateConfigClient(map[string]interface{}{
> 		"serverConfigs": serverConfigs,
> 		"clientConfig":  clientConfig,
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> 	config, err := client.GetConfig(vo.ConfigParam{
> 		DataId: "test-nacos.yaml",
> 		Group:  "test",
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> 	fmt.Println(config)
> }
> ```
> 
> 如果使用v2版本会报错： ![image](https://user-images.githubusercontent.com/113567699/273372601-990b4ee3-d73f-4631-8d36-f7c7616a8ef9.png)
> 
> 但是使用v1版本可以成功读取配置信息： ![image](https://user-images.githubusercontent.com/113567699/273372639-09e4101f-55a4-4fdb-ba91-9cda572a449d.png)

It seems that you are doing an e-commerce system project which use nacos,coincidentally, the project I am currently replicating happens to be the same as yours，I use v2 vell and dont't meet bugs about nacos.The relevant code is as follows,I hope it helps:
```go
package initialize

import (
	"encoding/json"

	"github.com/nacos-group/nacos-sdk-go/v2/clients"
	"github.com/nacos-group/nacos-sdk-go/v2/common/constant"
	"github.com/nacos-group/nacos-sdk-go/v2/vo"
	"github.com/spf13/viper"
	"go.uber.org/zap"

	"cloudshop-api/user/global"
)

func GetEnvInfo(env string) bool {
	viper.AutomaticEnv()
	return viper.GetBool(env)
}

func InitConfig() {
	global.Debug = GetEnvInfo("CloudShop_debug")
	configFileName := "user/config-pro.yaml"
	loglevel := "warn"
	if global.Debug {
		configFileName = "user/config-dev.yaml"
		loglevel = "debug"
	}

	v := viper.New()
	v.SetConfigFile(configFileName)
	if err := v.ReadInConfig(); err != nil {
		zap.S().Panic(err.Error())
	}
	if err := v.Unmarshal(&global.NacosConfig); err != nil {
		zap.S().Panic(err.Error())
	}

	sc := []constant.ServerConfig{
		{
			IpAddr: global.NacosConfig.Host,
			Port:   uint64(global.NacosConfig.Port),
		},
	}

	cc := constant.ClientConfig{
		NamespaceId:         global.NacosConfig.Namespace,
		TimeoutMs:           5000,
		NotLoadCacheAtStart: true,
		LogDir:              "tmp/nacos/log",
		CacheDir:            "tmp/nacos/cache",
		LogLevel:            loglevel,
	}

	configClient, err := clients.CreateConfigClient(map[string]interface{}{
		"serverConfigs": sc,
		"clientConfig":  cc,
	})
	if err != nil {
		zap.S().Panic("创建nacos客户端失败：", err.Error())
	}
	content, err := configClient.GetConfig(vo.ConfigParam{
		DataId: global.NacosConfig.DataId,
		Group:  global.NacosConfig.Group,
	})
	if err != nil {
		zap.S().Panic("获取nacos配置失败：", err.Error())
	}
	err = json.Unmarshal([]byte(content), &global.ServerConfig)
	if err != nil {
		zap.S().Fatalf("获取nacos配置失败： %s", err.Error())
	}
}
```

**Comment by 458220661** [comment]
+1 我也遇到同样的问题
v1版本一切正常，v2 search查得到 但get时会出现前边相同的报错 或者 返回值err为nil config内容也为空串的情况

**Comment by ve-weiyi** [comment]
+1

**Comment by binbin0325** [comment]
配置的log和cache 路径 tmp前面缺少“/”

**Comment by vicabert091** [comment]
怎么解决的，是不是有bug , 见鬼了
