### ISSUE TITLE
希望可以将服务端的健康检查接口暴露到namingclient中

### ISSUE THREAD

**Issue by lixiangwuxian** [nacos-group/nacos-sdk-go#676]
### Use case(s) - what problem will this feature solve?

客户端启动时，可以通过调用ServerHealthy()无副作用地获取对应nacos server的连通状况，决定继续服务还是暂停获取信息。

### Proposed Solution

目前浏览sdk代码时发现 `naming_client.NamingClient` 类中的私有成员 `serviceProxy` 的接口拥有ServerHealthy()方法，但无法从项目中直接调用。

希望可以将 `ServerHealthy()` 方法暴露到 `naming_client.INamingClient` 接口中，可以通过创建的naming client直接调用。

### Alternatives Considered

-

### Additional Context

-

**Comment by binbin0325** [comment]
可以的，如果感兴趣欢迎提交pr

**Comment by lixiangwuxian** [comment]
https://github.com/nacos-group/nacos-sdk-go/pull/677
