### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by magicdvd** [nacos-group/nacos-sdk-go#68]
1. 代码不太符合标准go的代码格式，好多感觉是java的风格, 少用interface{}断言。
2. 很多地方，go都习惯于用*Object, 而不是直接使用实体。
3. 配置创建使用 NewObject(...options ClientOption) 这种模式更通用 
   https://github.com/grpc/grpc-go/blob/master/server.go  请参考 NewServer部分

然后grpc的支持是否直接集成进来，我要跨语言支持，java那部分grpc<https://github.com/nacos-group/grpc-java-registry-nacos>我看已经有实现了。我希望这一部分，官方能协调，保证服务定义路径啥的一致，这样便于跨语言服务的gRPC使用。感谢。

以上这些，有需要，我可以协助修改。

**Comment by lzp0412** [comment]
嗯，建议非常好，非常欢迎一起参与共建，可以加一下钉钉群23191211吗？我们详聊
