### ISSUE TITLE
[BUG] SubscribeServiceRequest  请求参数 clusters 失效

### ISSUE THREAD

**Issue by Cczzzz** [nacos-group/nacos-sdk-go#684]
如图所示：
GO
![image](https://github.com/nacos-group/nacos-sdk-go/assets/32947555/5242c0af-8d47-4d0d-8ee4-d8d53e2f153e)

Java
![image](https://github.com/nacos-group/nacos-sdk-go/assets/32947555/53ec5621-5366-44e2-98d3-f47149e7102e)

**Comment by binbin0325** [comment]
升级到新版本
