### ISSUE TITLE
v2.2.4版本初始话init时，存在很多无效的logger.Info()很影响应用程序输出，且无法通过参数控制取消，倒逼修改源码去掉了。望官方修复！

### ISSUE THREAD

**Issue by Isaacedvr1003** [nacos-group/nacos-sdk-go#687]
### What version of nacos-sdk-go are you using?
v2.2.4
### What version of nacos-sever are you using?
2.1.1
### What version of Go are you using (`go version`)?
1.21.4
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
If possible, provide a recipe for reproducing the error.
![微信图片_20231130083929](https://github.com/nacos-group/nacos-sdk-go/assets/152384462/7828077e-c8af-4563-9169-2a154685d5b1)

### What did you expect to see?
encryption/handler.go:66
encryption/handler.go:135
encryption/kms_plugins.go:29
encryption/kms_plugins.go:34
encryption/kms_plugins.go:39
filter/config_filter.go:59 
 filter/config_encryption_filter.go:45
filter/config_filter.go:51 
以上代码对应的行数均有logger.Info()，初始化就有日志输出，无法通过参数控制日志输出级别。对于应用程序的输出是无效。目前虽然可通过修改源码去掉，可继续使用。
但是希望官方给予修复。

**Comment by yeqiaojun** [comment]
同望官方修复！

**Comment by Isaacedvr1003** [comment]
master分支下载来后，改为debug输出，还是一样的问题，init时还有无效的debug日志输出。不知道如何关掉此debug输出？
![Uploading 微信图片_20231201124310.png…]()

@binbin0325 @robynron

**Comment by robynron** [comment]
为什么一定要去掉？这个就是日志信息。
不想看到这些日志信息，就设定`INFO`级别以上的日志就好。

**Comment by Isaacedvr1003** [comment]
初始化init的时候，无法设置INFO级别以上，初始化完再设置就晚了。

**Comment by Isaacedvr1003** [comment]
而且这么修改给集成组件的开发人员，很容易造成误导和不便。上次v2.2.3版本也是有类似问题，官方给修复了。

**Comment by Isaacedvr1003** [comment]
输出到log文件里也可以，输出到终端上太影响业务日志输出。
@binbin0325 @robynron

**Comment by robynron** [comment]
> 这改发是不是有点不合理，既然设置了log落地文件，按直觉nacos的所有日志就该到log文件里面。更好的做法应该是Config里日志文件设置完了，再输出到日志文件。

日志可以配置。`AppendToStdout`关掉，就不会输出到控制台。

**Comment by robynron** [comment]
> 输出到log文件里也可以，输出到终端上太影响业务日志输出。 @binbin0325 @robynron

日志可以配置。AppendToStdout关掉，就不会输出到控制台。

**Comment by Isaacedvr1003** [comment]
@binbin0325 @robynron 导入包的时候就已经产生了debug日志了。AppendToStdout关不掉。直接上代码哈。
package nacosmodule

import (
	"bytes"
	"github.com/nacos-group/nacos-sdk-go/v2/clients"
	"github.com/nacos-group/nacos-sdk-go/v2/common/constant"
	"github.com/nacos-group/nacos-sdk-go/v2/vo"
	"github.com/spf13/viper"
	"goPrograms/goutil/yaml/yamlmodule"
)

func GetConfig(dataid string, group string) (map[string]interface{}, error) {
	allSettings := yamlmodule.ReadYamlConfig("./conf", "configure")
	if !allSettings["nacos"].(map[string]interface{})["switch"].(bool) {
		return allSettings, nil
	}
	//create ServerConfig
	sc := []constant.ServerConfig{
		*constant.NewServerConfig(allSettings["nacos"].(map[string]interface{})["req_host"].(string), uint64(allSettings["nacos"].(map[string]interface{})["req_port"].(int)), constant.WithContextPath("/nacos")),
	}
	//create ClientConfig
	cc := *constant.NewClientConfig(
		constant.WithNamespaceId(""),
		constant.WithTimeoutMs(5000),
		constant.WithNotLoadCacheAtStart(true),
		constant.WithLogDir(allSettings["nacos"].(map[string]interface{})["log_dir"].(string)),
		constant.WithCacheDir(allSettings["nacos"].(map[string]interface{})["log_dir"].(string)),
		constant.WithLogLevel("error"),
	)
	cc.AppendToStdout = false
	// create config client
	client, err := clients.NewConfigClient(
		vo.NacosClientParam{
			ClientConfig:  &cc,
			ServerConfigs: sc,
		},
	)
	if err != nil {
		return make(map[string]interface{}), err
	}
	content, err := client.GetConfig(vo.ConfigParam{
		DataId: dataid,
		Group:  group,
	})
	if err != nil {
		return make(map[string]interface{}), err
	}
	viper.SetConfigType("yaml")
	viper.ReadConfig(bytes.NewBuffer([]byte(content)))
	return viper.AllSettings(), err
}

**Comment by Isaacedvr1003** [comment]
感谢，pr版本我本地试了可以啦，望尽快合并到master里。

**Comment by Isaacedvr1003** [comment]
@robynron 您好，pr版本啥时候会合并到master分支？有计划吗？
