### ISSUE TITLE
手动取消监听配置功能

### ISSUE THREAD

**Issue by sanxun0325** [nacos-group/nacos-sdk-go#69]
目前配置建立监听后，未找到取消监听的函数。需要这个功能。

**Comment by lzp0412** [comment]
已经排在开发计划了，预计这个月能发出来

**Comment by sanxun0325** [comment]
@lzp0412 是可以针对于每一个配置文件的监听进行独立取消么。  本来我想提个pr  看来不需要了。

**Comment by lzp0412** [comment]
是的，根据dataid+group+namespaceid去取消监听。可以搜索钉钉群：23191211，有问题可以详聊

**Comment by sanxun0325** [comment]
@lzp0412 https://github.com/nacos-group/nacos-sdk-go/pull/70
