### ISSUE TITLE
运行出错 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sonwa** [nacos-group/nacos-sdk-go#702]
运行SDK的官方例子 nacos-sdk-go/example/service

success, err := client.RegisterInstance(vo.RegisterInstanceParam{
		Ip:          "10.10.10.10",
		Port:        8848,
		ServiceName: "ibm_server",
		Weight:      10,
		Enable:      true,
		Healthy:     true,
		Ephemeral:   true,
		//Metadata:    map[string]string{"idc": "shanghai"},
		ClusterName: "DEFAULT",          // 默认值DEFAULT
		GroupName:   "IBM_GROUP", // 默认值DEFAULT_GROUP
	})

不管是整合进项目还是直接运行例子，都出错在success, err := client.RegisterInstance(param) 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1027064c4]

goroutine 1 [running]:
main.registerServiceInstance({0x10297f800?, 0x140000b4fc0?}, {{0x10270dc83, 0xb}, 0x97c0, 0x4024000000000000, 0x1, 0x1, 0x14000380cf0, {0x10270cb15, ...}, ...})

配置信息都没问题的，SDK使用v2.2.4 ，NACOS使用 2.2.3

请问是什么问题做成的？

**Comment by shcw** [comment]
你试试Ephemeral改为false 


如果可以的话 那可能是 grpc的请求写的有问题

**Comment by sonwa** [comment]
Ephemeral改成false，出错提示变成了 
panic: RegisterServiceInstance failed!retry 3 times request failed!: request return error code 403

**Comment by binbin0325** [comment]
go版本是多少？nacos-sdk-go/example/service的例子 没问题

**Comment by sonwa** [comment]
go version go1.20.2 darwin/arm64
系统使用 macOS 14.2.1

试了很多种方法都不行，默认官方例子，修改过的例子都是提示这个错误。同事使用JAVA的正常使用着，服务器配置应该是没问题的。

**Comment by sonwa** [comment]
<img width="1050" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/1425134/754119ef-cb4a-4278-8311-7eb1934797b3">

go版本升到最新了，刚又删了之前的，下最新的例子，只改了一个 nacos 的连接地址和端口，其它啥都没改过，运行就出错。
