### ISSUE TITLE
启动项目出现log日志

### ISSUE THREAD

**Issue by Kseng** [nacos-group/nacos-sdk-go#713]
请问有办法移除这部分日志吗？
我的项目引入了nacos-sdk-go, 再启动项目的时候会出现以下日志

<img width="1087" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/16551343/06b29954-1639-4a94-bf42-50a3c84ac872">

**Comment by binbin0325** [comment]
已经修复了，后面发新版本会去掉，或者可以用最新的master分支代码
