### ISSUE TITLE
Is there a way to manage Nacos Service via sdk?

### ISSUE THREAD

**Issue by hansedong** [nacos-group/nacos-sdk-go#714]
Nacos's Open API provides many API interfaces to operate Nacos. I expect to use nacos-sdk-go to fully operate Nacos. 

However, I found that this SDK does not seem to provide a complete set of methods. For example, there is no separate method for creating a service (corresponding to the `/nacos/v2/ns/service` of the Open API).

The `INamingClient` just provides the following methods:

```go
type INamingClient interface {

	//RegisterInstance use to register instance
	//Ip  require
	//Port  require
	//Tenant optional
	//Weight  require,it must be lager than 0
	//Enable  require,the instance can be access or not
	//Healthy  require,the instance is health or not
	//Metadata  optional
	//ClusterName  optional,default:DEFAULT
	//ServiceName require
	//GroupName optional,default:DEFAULT_GROUP
	//Ephemeral optional
	RegisterInstance(param vo.RegisterInstanceParam) (bool, error)

	//DeregisterInstance use to deregister instance
	//Ip required
	//Port required
	//Tenant optional
	//Cluster optional,default:DEFAULT
	//ServiceName  require
	//GroupName  optional,default:DEFAULT_GROUP
	//Ephemeral optional
	DeregisterInstance(param vo.DeregisterInstanceParam) (bool, error)

	// UpdateInstance use to modify instance
	// Ip required
	// Port required
	// Tenant optional
	// Cluster optional,default:DEFAULT
	// ServiceName  require
	// GroupName  optional,default:DEFAULT_GROUP
	// Ephemeral optional
	// Weight  require,it must be lager than 0
	// Enable  require,the instance can be access or not
	// Metadata  optional
	UpdateInstance(param vo.UpdateInstanceParam) (bool, error)

	//GetService use to get service
	//ServiceName require
	//Clusters optional,default:DEFAULT
	//GroupName optional,default:DEFAULT_GROUP
	GetService(param vo.GetServiceParam) (model.Service, error)

	//SelectAllInstance return all instances,include healthy=false,enable=false,weight<=0
	//ServiceName require
	//Clusters optional,default:DEFAULT
	//GroupName optional,default:DEFAULT_GROUP
	SelectAllInstances(param vo.SelectAllInstancesParam) ([]model.Instance, error)

	//SelectInstances only return the instances of healthy=${HealthyOnly},enable=true and weight>0
	//ServiceName require
	//Clusters optional,default:DEFAULT
	//GroupName optional,default:DEFAULT_GROUP
	//HealthyOnly optional
	SelectInstances(param vo.SelectInstancesParam) ([]model.Instance, error)

	//SelectInstances return one instance by WRR strategy for load balance
	//And the instance should be health=true,enable=true and weight>0
	//ServiceName require
	//Clusters optional,default:DEFAULT
	//GroupName optional,default:DEFAULT_GROUP
	SelectOneHealthyInstance(param vo.SelectOneHealthInstanceParam) (*model.Instance, error)

	//Subscribe use to subscribe service change event
	//ServiceName require
	//Clusters optional,default:DEFAULT
	//GroupName optional,default:DEFAULT_GROUP
	//SubscribeCallback require
	Subscribe(param *vo.SubscribeParam) error

	//Unsubscribe use to unsubscribe service change event
	//ServiceName require
	//Clusters optional,default:DEFAULT
	//GroupName optional,default:DEFAULT_GROUP
	//SubscribeCallback require
	Unsubscribe(param *vo.SubscribeParam) error

	//GetAllServicesInfo use to get all service info by page
	GetAllServicesInfo(param vo.GetAllServiceInfoParam) (model.ServiceList, error)
}
```

I'd like to know 2 questions:

1. How can I achieve my goal (manage Service resources)?
2. In particular, I hope to configure the associated CLUSTER (Eg: disable aliveness detection) when creating the Instance, how can I do it?

Looking forward to hearing back, thanks a lot

**Comment by binbin0325** [comment]
Check out README.md for the answers you're looking for

**Comment by hansedong** [comment]
@binbin0325 Sorry, I don't think you fully understood what my question was

**Comment by hansedong** [comment]
I've checked the README.md before and there weren't the methods addressed, if not, will these be likely to be added in the future?

**Comment by binbin0325** [comment]
> @binbin0325 Sorry, I don't think you fully understood what my question was

There is code in both readme and example to solve your problem.  
Second question, you can register a persistence service (if you think it's necessary).

**Comment by binbin0325** [comment]
The openapi provided by nacos server is an administrative operation, and the sdk is not necessary and does not need to be consistent with it

**Comment by hansedong** [comment]
@binbin0325 

> There is code in both readme and example to solve your problem. （register an instance naturally creates a service, regardless of the version） Second question, you can register a persistence service (if you think it's necessary).

I don't think the example in REAME.md solves my problems. Using SDK, we can register Instance to Nacos. However, from Nacos's perspective, when it registers Instance, the current SDK (at least my understanding through the code and REAME.md) cannot modify some information of Service, especially the CLUSTER information of Instance. 

You mentioned that we can register Persistent Instance. However, according to my current understanding, registering Persistent Instance also cannot control CLUSTER information (for example, disable Cluster's liveness detection).

> The openapi provided by nacos server is an administrative operation, and the sdk is not necessary and does not need to be consistent with it

If I understand correctly, nacos-sdk-go wants to solve the scene problem of the user application side.

If I want to synchronize data from other service discovery centers (such as Consul, K8s, etc.) to Nacos, and have more complete control over some attributes of Nacos Instance. I would like to know if this scenario is considered in the design of nacos-sdk-go?

**Comment by binbin0325** [comment]
You can use UpdateInstance modifies it.  and if you just want to synchronize instances, you should use https://github.com/nacos-group/nacos-sync

'disable Cluster's liveness detection' ，you don't want a heartbeat check? 

join dingding group：23191211
