### ISSUE TITLE
Bugs for getConfig

### ISSUE THREAD

**Issue by kelvin-yuang** [nacos-group/nacos-sdk-go#724]
获取 Nacos 配置失败: read config from both server and cache fail, err=read cache file Config Encrypted Data Key failed. cause file doesn't exist, file path: /tmp/nacos/cache\config\test-data@@testgroup@@f82b2dbf-af7b-4ffb-af84-b117c2aca9ad.: file not exist，dataId=test-data, group=testgroup, namespaceId=f82b2dbf-af7b-4ffb-af84-b117c2aca9ad

/tmp/nacos/cache\config\test-data@@testgroup@@f82b2dbf-af7b-4ffb-af84-b117c2aca9ad.: file not exist，

\ 是windows 的 ，开发组用点心, 不想做就不要做了。

**Comment by kelvin-yuang** [comment]
参数 命名不规范不统一

**Comment by binbin0325** [comment]
路径填写错误，自己用错还怪开源项目。
