### ISSUE TITLE
注册服务时无法连接nacos

### ISSUE THREAD

**Issue by skillhome** [nacos-group/nacos-sdk-go#726]
> nacos部署的是2.2.3版本
go1.21.6
nacos-sdk-go版本是 2.2.5
都是按照nacos-sdk-go官方示例写的
通过nacos api
curl -X POST 'http://:8848/nacos/v1/ns/instance?serviceName=user&ip=127.0.0.1&port=8080'
是可以成功注册服务的

```
import (
	"github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client"
)
var (
	NacosClient  naming_client.INamingClient
)
```

```
import (
	"github.com/nacos-group/nacos-sdk-go/v2/clients"
	"github.com/nacos-group/nacos-sdk-go/v2/common/constant"
	"github.com/nacos-group/nacos-sdk-go/v2/vo"
	"go.uber.org/zap"
	"shop_study/user_grpc/global"
)
func InitNacos() {
	// 创建配置文件 clientConfig
	clientConfig := constant.ClientConfig{
		NamespaceId:         global.ServerConfig.NacosInfo.NamespaceId, // 命名空间，没有则填空字符串
		TimeoutMs:           5000,
		NotLoadCacheAtStart: true,
		LogDir:              "/tmp/nacos/log",
		CacheDir:            "/tmp/nacos/cache",
		LogLevel:            "debug",
		Username:            global.ServerConfig.NacosInfo.Username,
		Password:            global.ServerConfig.NacosInfo.Password,
	}
	// 至少配置一个ServerConfig
	serverConfigs := []constant.ServerConfig{
		{
			IpAddr:      global.ServerConfig.NacosInfo.Host,
			ContextPath: "/nacos",
			Port:        global.ServerConfig.NacosInfo.Port,
			Scheme:      "http",
		},
	}

	// 创建客户端
	var clientErr error
	global.NacosClient, clientErr = clients.NewNamingClient(
		vo.NacosClientParam{
			ClientConfig:  &clientConfig,
			ServerConfigs: serverConfigs,
		},
	)
	if clientErr != nil {
		zap.S().Errorf("创建nacos客户端失败: %s", clientErr.Error())
		panic(clientErr)
	}
	// 检查客户端是否连接成功
	if connected := global.NacosClient.ServerHealthy(); connected {
		zap.S().Info("[Nacos]客户端连接成功")
	} else {
		zap.S().Error("[Nacos]客户端连接失败")
	}

}
```

```
// RegisterInstance 注册nacos服务
func RegisterInstance(serverName string, port int) (ok bool, err error) {
	// 检查客户端是否连接成功
	if connected := global.NacosClient.ServerHealthy(); !connected {
		zap.S().Error("[Nacos]注册服务失败,客户端未连接")
		return false, nil
	}
	return global.NacosClient.RegisterInstance(vo.RegisterInstanceParam{
		Ip:          utils.GetLocalIP(),
		Port:        uint64(port),
		ServiceName: serverName,
		Weight:      10,
		Enable:      true,
		Healthy:     true,
		Ephemeral:   true,
		Metadata:    map[string]string{"version": "1.0"},
		//ClusterName: global.ServerConfig.NacosInfo.ClusterName, // 默认为DEFAULT
		//GroupName:   global.ServerConfig.NacosInfo.GroupName,   // 默认为DEFAULT_GROUP
	})
}

// DeregisterInstance 注销nacos服务
func DeregisterInstance(serverName string, port int) {
	ok, err := global.NacosClient.DeregisterInstance(vo.DeregisterInstanceParam{
		Ip:          utils.GetLocalIP(),
		Port:        uint64(port),
		ServiceName: serverName,
		Ephemeral:   true,
		//Cluster:     global.ServerConfig.NacosInfo.ClusterName,
		//GroupName:   global.ServerConfig.NacosInfo.GroupName,
	})
	if err != nil {
		zap.S().Errorf("[nacos]注销本服务发生错误: %s", err.Error())
		panic("[nacos]注销本服务发生错误")
	}
	if !ok {
		zap.S().Errorf("[nacos]注销本服务失败: %s", err.Error())
		panic("[nacos]注销本服务失败")
	}
}

func GetAllInstances(serverName string) {
	instances, err := global.NacosClient.SelectAllInstances(vo.SelectAllInstancesParam{
		GroupName: serverName,
	})
	if err != nil {
		zap.S().Errorf("[nacos]获取所有实例发生错误: %s", err.Error())
		panic("[nacos]获取所有实例发生错误")
	}
	for _, instance := range instances {
		zap.S().Infof("[nacos]实例信息: %v", instance)
	}
}
```

```
func main() {
	
	// 初始化nacos
	initialize.InitNacos()
	//服务注册
	ok, err := nacos.RegisterInstance(global.ServerConfig.Name, *PORT)
	if err != nil {
		zap.S().Errorf("[nacos]注册实例失败: %s", err.Error())
		panic(err)
	}
	if !ok {
		zap.S().Errorf("[nacos]注册本服务失败: %s", err.Error())
		panic("[nacos]注册本服务失败")
	} else {
		zap.S().Infof("[nacos]服务注册成功, 端口： %d", *PORT)
	}
}
```

```
nacos:
  host: 'xx.xx.xx.xxx'
  port: 8848
  username: nacos
  password: nacos
  ClusterName: 'DEFAULT'
  groupName: 'DEFAULT_GROUP'
  namespaceId: '9cabdce3-df27-42de-9c77-388207ced2fb'
```
调用注册服务时报错
 [nacos]获取所有实例发生错误: client not connected, current status:STARTING
不知道哪里出问题了

**Comment by skillhome** [comment]
已经解决，原因: 未开放grpc端口 9848

**Comment by skillhome** [comment]
> > nacos部署的是2.2.3版本
> > go1.21.6
> > nacos-sdk-go版本是 2.2.5
> > 都是按照nacos-sdk-go官方示例写的
> > 通过nacos api
> > curl -X POST 'http://:8848/nacos/v1/ns/instance?serviceName=user&ip=127.0.0.1&port=8080'
> > 是可以成功注册服务的
> 
> ```
> import (
> 	"github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client"
> )
> var (
> 	NacosClient  naming_client.INamingClient
> )
> ```
> 
> ```
> import (
> 	"github.com/nacos-group/nacos-sdk-go/v2/clients"
> 	"github.com/nacos-group/nacos-sdk-go/v2/common/constant"
> 	"github.com/nacos-group/nacos-sdk-go/v2/vo"
> 	"go.uber.org/zap"
> 	"shop_study/user_grpc/global"
> )
> func InitNacos() {
> 	// 创建配置文件 clientConfig
> 	clientConfig := constant.ClientConfig{
> 		NamespaceId:         global.ServerConfig.NacosInfo.NamespaceId, // 命名空间，没有则填空字符串
> 		TimeoutMs:           5000,
> 		NotLoadCacheAtStart: true,
> 		LogDir:              "/tmp/nacos/log",
> 		CacheDir:            "/tmp/nacos/cache",
> 		LogLevel:            "debug",
> 		Username:            global.ServerConfig.NacosInfo.Username,
> 		Password:            global.ServerConfig.NacosInfo.Password,
> 	}
> 	// 至少配置一个ServerConfig
> 	serverConfigs := []constant.ServerConfig{
> 		{
> 			IpAddr:      global.ServerConfig.NacosInfo.Host,
> 			ContextPath: "/nacos",
> 			Port:        global.ServerConfig.NacosInfo.Port,
> 			Scheme:      "http",
> 		},
> 	}
> 
> 	// 创建客户端
> 	var clientErr error
> 	global.NacosClient, clientErr = clients.NewNamingClient(
> 		vo.NacosClientParam{
> 			ClientConfig:  &clientConfig,
> 			ServerConfigs: serverConfigs,
> 		},
> 	)
> 	if clientErr != nil {
> 		zap.S().Errorf("创建nacos客户端失败: %s", clientErr.Error())
> 		panic(clientErr)
> 	}
> 	// 检查客户端是否连接成功
> 	if connected := global.NacosClient.ServerHealthy(); connected {
> 		zap.S().Info("[Nacos]客户端连接成功")
> 	} else {
> 		zap.S().Error("[Nacos]客户端连接失败")
> 	}
> 
> }
> ```
> 
> ```
> // RegisterInstance 注册nacos服务
> func RegisterInstance(serverName string, port int) (ok bool, err error) {
> 	// 检查客户端是否连接成功
> 	if connected := global.NacosClient.ServerHealthy(); !connected {
> 		zap.S().Error("[Nacos]注册服务失败,客户端未连接")
> 		return false, nil
> 	}
> 	return global.NacosClient.RegisterInstance(vo.RegisterInstanceParam{
> 		Ip:          utils.GetLocalIP(),
> 		Port:        uint64(port),
> 		ServiceName: serverName,
> 		Weight:      10,
> 		Enable:      true,
> 		Healthy:     true,
> 		Ephemeral:   true,
> 		Metadata:    map[string]string{"version": "1.0"},
> 		//ClusterName: global.ServerConfig.NacosInfo.ClusterName, // 默认为DEFAULT
> 		//GroupName:   global.ServerConfig.NacosInfo.GroupName,   // 默认为DEFAULT_GROUP
> 	})
> }
> 
> // DeregisterInstance 注销nacos服务
> func DeregisterInstance(serverName string, port int) {
> 	ok, err := global.NacosClient.DeregisterInstance(vo.DeregisterInstanceParam{
> 		Ip:          utils.GetLocalIP(),
> 		Port:        uint64(port),
> 		ServiceName: serverName,
> 		Ephemeral:   true,
> 		//Cluster:     global.ServerConfig.NacosInfo.ClusterName,
> 		//GroupName:   global.ServerConfig.NacosInfo.GroupName,
> 	})
> 	if err != nil {
> 		zap.S().Errorf("[nacos]注销本服务发生错误: %s", err.Error())
> 		panic("[nacos]注销本服务发生错误")
> 	}
> 	if !ok {
> 		zap.S().Errorf("[nacos]注销本服务失败: %s", err.Error())
> 		panic("[nacos]注销本服务失败")
> 	}
> }
> 
> func GetAllInstances(serverName string) {
> 	instances, err := global.NacosClient.SelectAllInstances(vo.SelectAllInstancesParam{
> 		GroupName: serverName,
> 	})
> 	if err != nil {
> 		zap.S().Errorf("[nacos]获取所有实例发生错误: %s", err.Error())
> 		panic("[nacos]获取所有实例发生错误")
> 	}
> 	for _, instance := range instances {
> 		zap.S().Infof("[nacos]实例信息: %v", instance)
> 	}
> }
> ```
> 
> ```
> func main() {
> 	
> 	// 初始化nacos
> 	initialize.InitNacos()
> 	//服务注册
> 	ok, err := nacos.RegisterInstance(global.ServerConfig.Name, *PORT)
> 	if err != nil {
> 		zap.S().Errorf("[nacos]注册实例失败: %s", err.Error())
> 		panic(err)
> 	}
> 	if !ok {
> 		zap.S().Errorf("[nacos]注册本服务失败: %s", err.Error())
> 		panic("[nacos]注册本服务失败")
> 	} else {
> 		zap.S().Infof("[nacos]服务注册成功, 端口： %d", *PORT)
> 	}
> }
> ```
> 
> ```
> nacos:
>   host: 'xx.xx.xx.xxx'
>   port: 8848
>   username: nacos
>   password: nacos
>   ClusterName: 'DEFAULT'
>   groupName: 'DEFAULT_GROUP'
>   namespaceId: '9cabdce3-df27-42de-9c77-388207ced2fb'
> ```
> 
> 调用注册服务时报错 [nacos]获取所有实例发生错误: client not connected, current status:STARTING 不知道哪里出问题了

**Comment by xiaoxfan** [comment]
@skillhome 我遇到同样的问题，这个库必须要nacos开启grpc端口才能用吗
