### ISSUE TITLE
服务元数据(不是实例元数据)的注册与更新

### ISSUE THREAD

**Issue by zhiyunliu** [nacos-group/nacos-sdk-go#756]
### Use case(s) - what problem will this feature solve?
1. 当服务注册时候，希望可以增加服务的元数据写入。

### Proposed Solution
当前通过管理后台接口可以创建接口元数据和查询接口元数据
```text
创建数据：
POST /nacos/v1/ns/service 
serviceName=aaa&groupName=DEFAULT_GROUP&protectThreshold=0&metadata=%7B%22aaa%22%3A1%7D&namespaceId=
查询数据：
GET /nacos/v1/ns/service?serviceName=aaa&groupName=DEFAULT_GROUP&namespaceId=
```
希望这个服务元数据在注册实例服务的时候可以写入，或者开放/nacos/v1/ns/service接口的调用方法。

**Comment by binbin0325** [comment]
一直有这个能力，参考：https://github.com/nacos-group/nacos-sdk-go/blob/master/example/service/main.go#L69

**Comment by binbin0325** [comment]
这属于运维管控的操作，不在sdk的管理范围呢。 建议直接调用nacos server openapi。
