### ISSUE TITLE
配置不管用

### ISSUE THREAD

**Issue by scpzc** [nacos-group/nacos-sdk-go#760]
### What version of nacos-sdk-go are you using?
github.com/nacos-group/nacos-sdk-go/v2 v2.2.6
### What version of nacos-sever are you using?
2.3.2
### What version of Go are you using (`go version`)?
1.22
### What operating system (Linux, Windows, …) and version?
linux
配置不管用 
![image](https://github.com/nacos-group/nacos-sdk-go/assets/22276159/b439fb0d-5400-4a81-bf43-016c7c87da06)

![image](https://github.com/nacos-group/nacos-sdk-go/assets/22276159/0e5dd6f1-8c91-4218-b216-9c31d398e208)
nacos-sdk-go/v2 换成v2.2.5，就管用了，2.2.6有BUG，希望能核实并修复

**Comment by yesAnd92** [comment]
我看了下这个问题 ，#759 已经解决了？

**Comment by binbin0325** [comment]
pr:https://github.com/nacos-group/nacos-sdk-go/pull/759
