### ISSUE TITLE
日志配置不能写入到文件里

### ISSUE THREAD

**Issue by ximengyi** [nacos-group/nacos-sdk-go#763]
### What version of nacos-sdk-go are you using?
github.com/nacos-group/nacos-sdk-go/v2 v2.2.6
### What version of nacos-sever are you using?
2.0.1
### What version of Go are you using (`go version`)?
1.19
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
// 客户端配置
	clientConfig := constant.ClientConfig{
		Username:            "test",     // 用户名
		Password:            "test",     // 密码
		NamespaceId:         "test-dev", // 如果使用命名空间
		TimeoutMs:           5000,
		NotLoadCacheAtStart: true,
		OpenKMS:             false,
		LogDir:              "/data/log/nacos/log",
		CacheDir:            "/data/log/nacos/cache",
		LogLevel:            "error",
		AppendToStdout:      false,
		BeatInterval:        500000,
		ListenInterval:      700000,
	}

我配置的客户端的日志目录是有权限的，但是日志不会写到日志文件里，而是输出到了命令行，标准stdout里
### What did you expect to see?
希望日志路径配置可以写到日志文件里

**Comment by binbin0325** [comment]
升级下最新版本
