### ISSUE TITLE
constant.ClientConfig LogLevel 无效

### ISSUE THREAD

**Issue by cy-6359** [nacos-group/nacos-sdk-go#764]
<img width="419" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/75932412/18616fc4-130a-4f7d-bf2c-73054da019b6">

<img width="293" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/75932412/f805e663-3a58-445c-a88b-def5d3d5f537">

**Comment by cy-6359** [comment]
我想知道这是个bug还是我自己有问题...怎么取消掉这个日志输出
<img width="390" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/75932412/84e366ec-7d5e-46d0-a7b9-7b5bb84b167e">

**Comment by cy-6359** [comment]
<img width="890" alt="image" src="https://github.com/nacos-group/nacos-sdk-go/assets/75932412/0c104a29-3a11-4c12-bd83-56dd1b4f7f7a">

**Comment by refear99** [comment]
同样问题，希望官方重视起来，提供这些参数但是并不生效
另外日志很混乱，有些无关紧要的东西也报ERROR，比如找不到配置文件缓存，对日志报警影响很大

```
2024-06-22T16:00:32.515+0800	ERROR	cache/disk_cache.go:193	read Config Content failed. cause file doesn't exist, file path: /var/folders/9w/g96l11zn0z56_y658m8nq1180000gn/T/go-build1253861140/b001/exe/cache/config/database@@c.......r.
```

希望能提供一个全局关闭日志的，或者修复这些参数问题
可能我脑子不行不会用吧

**Comment by Abeautifulsnow** [comment]
+1, 日志过滤设置无效。

**Comment by only21tender** [comment]
同样问题，设置全局日志级别info，日志一直在debug grpc request nacos server success ... HealthCheckRequest , nacos-go-sdk版本："github.com/nacos-group/nacos-sdk-go/v2/clients"

**Comment by luluxiu** [comment]
common/logger/logger.go  InitLogger 有问题, 里面判断如果 logger != nil, 则直接返回. 所以配置的log level 无效, 因为 init() 初始化了一个 debug 级别的logger

**Comment by yiboGit** [comment]
+1 日志级别参数无效 ，
还有cache的报错，真的对生产使用影响很大

**Comment by MrHongping** [comment]
我还以为是个例，排查半天 LOL..

**Comment by MrHongping** [comment]
> +1 日志级别参数无效 ，
> 
> 还有cache的报错，真的对生产使用影响很大

不要用最新版本的 用上一个版本就没有这个问题

**Comment by Succeedwer** [comment]
![image](https://github.com/nacos-group/nacos-sdk-go/assets/15903084/edc03be1-d5cb-4167-87df-5e02b38b8d69)
如图所示，v2.2.6版本，这设置不上level，logger本在init中初始化了，这判空是不是多此一举~
master已经修改了，还望尽快提个版本出来。
还望合代码时候严谨一点吧~

**Comment by MarchGe** [comment]
+1 ,刚升2.2.6，发现同样问题

**Comment by binbin0325** [comment]
这周发布新版本，修复下日志问题。大家可以先降低一个版本，使用2.2.5版本。

**Comment by xiak** [comment]
2.3.4又出现这个问题了
