### ISSUE TITLE
Listen mutiple config in a connection

### ISSUE THREAD

**Issue by lzp0412** [nacos-group/nacos-sdk-go#77]
**What would you like to be added:**
When we call ListenConfig(param vo.ConfigParam), put the listen task to cache, and other gorutine to get the tasks for listening change.
**Why is this needed:**
Now we only listen one config in a connect. This will cause waste of client resources and increase the nacos server load.

**Comment by sanxun0325** [comment]
I want to try this out.

**Comment by sanxun0325** [comment]
目前java-sdk中主要分为两部分。1：添加监听，2:监听调度任务
下面是大概流程：

添加监听：
addTenantListeners{
	1:addCacheDataIfAbsent func{
		1:从cacheMap 中获取，看cachemap是否存在当前要监听的配置，
		acheMap 的key是GroupKey.getKeyTenant(dataId, group, tenant)= dataId+group+tenant 例如： gray_plan+gateway
		2：如果cachemap取到， 直接返回
		3：未取到 锁住cachemap, chachemap是原子引用类型包装的map。
		4：再次从cachemap中获取，如果取到了将cache.setInitializing(true); ？？
		5：如果未取到，构建cacheData,cacheData对象中 包含dataId,group,tenant,listeners CopyOnWriteArrayList<ManagerListenerWrap>,
		content loadCacheContentFromDiskLocal（）是从本地读取data目录下的内容，如果没有读取本地Snapshot下的内容
		设置MD5=md5(content)

	}
	2:添加listeners 到cacheData中的listeners
}

监听调度任务：

启动一个LongPollingRunnable调度线程，初始化延迟1毫秒执行，本次执行后下次延迟10毫秒开始执行。
当需要监听的文件数量 大于3000 会再run 一个线程。

run(){
	checkConfigInfo(){
		1：遍历cacheMap 将所有cacheData取到，放入到cacheDatasList中。
		2：检查本地配置， 读取本地data目录 ，但是本地一直没有data目录，只有snapshot ，不知道data目录 怎么来的，难道是可以自己手动创建？
		3：checkUpdateDataIds（）{	//向服务端发起监听长轮询
				1：循环cacheDatasList 构建请求参数，拼接监听数据报文 dataId^2Group^2contentMD5^2tenant^1
				2：如果某一个cacheData是首次准备监听 那么它的isInitializing=true
				3:如果有首次监听的cacheData，那么需要在请求中 增加
					            headers.add("Long-Pulling-Timeout-No-Hangup");
								headers.add("true");
				否则header中 只有Long-Pulling-Timeout 和 timeout即可  timeout 默认30000，可配置
				headers.add("Long-Pulling-Timeout");
				headers.add("" + timeout);
				4 请求服务端，获取变化的配置列表changedGroupKeys
				
		}
		4：循环changedGroupKeys，得到dataId,group,tenant 去服务端请求，获取最新的配置。
		5：根据dataId,group,tenant获取cacheMap中对应的cacheData
		6:设置cacheData中的content为最新的content,并且设置cacheData的MD5 为最新的content MD5后的结果。
		7：再次遍历cacheDatasList，进行对比MD5
		  对比条件：cacheData中的MD5 和 cacheData 监听器中的lastCallMd5进行对比
			如果不相同，则执行监听器中的钩子函数，receiveConfigInfo，并将监听器中的lastCallMd5 设置为cacheData中的MD5
			如果相同 什么都不做。
	}
}

**Comment by sanxun0325** [comment]
对比和nacos-go-sdk 目前的区别。我认为目前区别比较大的几点：
1：java 使用了cacheMap 概念，将所有要监听的配置对象，都放入到map中。
2：利用chacheMap java 可以在一次长轮询请求中，将所有待监听的配置 发送到nacos服务中。
3：java 使用本地文件 存储了content
4:  javasdk中使用的线程是延迟调度线程。

**Comment by lzp0412** [comment]
我看了下java的没问题，可以参考java来实现就好了
