### ISSUE TITLE
高并发使用时，部分结果返回空

### ISSUE THREAD

**Issue by zxy822** [nacos-group/nacos-sdk-go#770]
### What version of nacos-sdk-go are you using?
2.2.7
### What version of nacos-sever are you using?
2.4.0
### What version of Go are you using (`go version`)?
1.22.5
### What operating system (Linux, Windows, …) and version?
linux+windows
### What did you do?
当多个接口调用nacos配置文件的时候，会偶发获取到的结果为空的情况，不仅限于获取同一个配置文件和获取不同的文件内容

**Comment by binbin0325** [comment]
提供能复现的demo

**Comment by carl-leopard** [comment]
已经找到返回为空的原因，被限流了。
文件路径：github.com/nacos-group/nacos-sdk-go/v2/clients/config_client/limiter.go
不太清楚为啥要限制5次，还是使用方式有问题？

`// IsLimited return true when request is limited
func IsLimited(checkKey string) bool {
	checker.mux.Lock()
	defer checker.mux.Unlock()
	var limiter *rate.Limiter
	lm, exist := checker.rateLimiterCache.Get(checkKey)
	if !exist {
		// define a new limiter,allow 5 times per second,and reserve stock is 5.
		limiter = rate.NewLimiter(rate.Limit(5), 5)
		checker.rateLimiterCache.Set(checkKey, limiter)
	} else {
		limiter = lm.(*rate.Limiter)
	}
	add := time.Now().Add(time.Second)
	return !limiter.AllowN(add, 1)
}`

**Comment by binbin0325** [comment]
这是请求nacos server 查询配置，限流是为了避免大规模请求对server造成压力。 建议使用监听配置，这样就不用一直查询了
