### ISSUE TITLE
引入context

### ISSUE THREAD

**Issue by 985492783** [nacos-group/nacos-sdk-go#774]
类似register deregister，listen这种，在go里是否将context引进来更合适，而不是手动调用函数

**Comment by binbin0325** [comment]
调用函数和引进context的关系是什么？没太理解

**Comment by 985492783** [comment]
> 调用函数和引进context的关系是什么？没太理解

用原生的context控制超时，结束啊，register在我ctxclose的时候自动deregister，getconfig我可以透传ctx控制超时时间，是不是更好点

**Comment by binbin0325** [comment]
> > 调用函数和引进context的关系是什么？没太理解
> 
> 用原生的context控制超时，结束啊，register在我ctxclose的时候自动deregister，getconfig我可以透传ctx控制超时时间，是不是更好点

这你再用sdk 时 自己包装下就可以了，和sdk内部没关系
