### ISSUE TITLE
caused: PreparedStatementCallback;bad SQL grammar[     SELECT id,     quota,     `usage`,     `max_size`,     max_aggr_count,     max_aggr_size,     tenant_id FROM tenant_capacity WHERE tenant_id=? ];nested exception is java.sql.SQLSyntaxErrorException: Lexical error at line 1, column 17.Encountered: &quot;`&quot; (96), after : &quot;&quot;.;caused: Lexical error at line 1, column 17.  Encountered: &quot;`&quot;(96), after: &quot;&quot;.;caused: Lexical error at line 1, column 17.Encountered: &quot;`&quot; (96), after : &quot;&quot;.;

### ISSUE THREAD

**Issue by mengqing20101212** [nacos-group/nacos-sdk-go#775]
http://127.0.0.1:8848/nacos/v1/console/namespaces?&namespaceId=
新建命名空间失败，而且返回SQL错误  版本是 Nacos 2.4.2  
caused: PreparedStatementCallback;bad SQL grammar[
    SELECT id,
    quota,
    `usage`,
    `max_size`,
    max_aggr_count,
    max_aggr_size,
    tenant_id FROM tenant_capacity WHERE tenant_id=?
];nested exception is java.sql.SQLSyntaxErrorException: Lexical error at line 1,
column 17.Encountered: &quot;`&quot; (96), after : &quot;&quot;.;caused: Lexical error at line 1, column 17.  Encountered: &quot;`&quot;(96),
after: &quot;&quot;.;caused: Lexical error at line 1,
column 17.Encountered: &quot;`&quot; (96), after : &quot;&quot;.;

**Comment by binbin0325** [comment]
这个错误和sdk没关系
