### ISSUE TITLE
go sdk 获取配置失败

### ISSUE THREAD

**Issue by mengqing20101212** [nacos-group/nacos-sdk-go#776]
nacos 2.4.2 ;  go sdk github.com/nacos-group/nacos-sdk-go/v2 v2.2.7 
我设置constant.WithNamespaceId("public"), 的时候  通过sdk 取不到 config 的配置，
//create ClientConfig
	cc := *constant.NewClientConfig(
		//constant.WithNamespaceId("public"),
		constant.WithNamespaceId("public"),
		constant.WithTimeoutMs(5000),
		constant.WithNotLoadCacheAtStart(true),
		constant.WithLogDir("../../nacos/log"),
		constant.WithCacheDir("../../nacos/cache"),
		constant.WithLogLevel("debug"),
	)

cfg, err := (*ConfigClient).GetConfig(vo.ConfigParam{
		DataId: "gameConfig",
		Group:  "DEFAULT_GROUP",
	})

返回  config data not exist
但是我通过浏览器  HTTP 请求 能请求到该数据http://127.0.0.1:8848/nacos/v2/cs/config?dataId=gameConfig&group=DEFAULT_GROUP&namespaceId=public 
当我把constant.WithNamespaceId("public"), 这个注掉的时候 sdk 就能获取到配置了

**Comment by binbin0325** [comment]
sdk中要传递命名空间的id, public的命名空间id默认为空。
