### ISSUE TITLE
为什么服务下线了却还能调用SelectOneHealthyInstance成功（缓存一直没有同步）

### ISSUE THREAD

**Issue by jzlover** [nacos-group/nacos-sdk-go#781]
本人使用的nacos版本是：v2.2.7，这边有两个服务，一个A服务，另外一个B服务，A服务通过INamingClient.SelectOneHealthyInstance方式获取一个健康的实例，当第一B正常上线后，是没问题，但是当把B杀死后，在nacos控制台里已经看不到了（这是因为设置了Ephemeral=true），但是A服务再调用SelectOneHealthyInstance还是一直能获取到当前B的健康实例，通过源码因为本地有缓存，好像一直是从缓存走了，缓存好像就没有被同步，不知道哪里问题。
另外如果我把服务注册的Ephemeral改成false，所有的接口一切正常。

**Comment by hmldd** [comment]
相同问题，缓存一直不更新，10s后B也还能从缓存获取到

**Comment by hmldd** [comment]
@jzlover 看下ClientConfig里的UpdateCacheWhenEmpty参数，改成true可以了，不改成true只有一个B并且停掉之后会一直从缓存拿

**Comment by jzlover** [comment]
@hmldd 非常感谢，我试了可以
