### ISSUE TITLE
create only one  gorutine for beat  on the same service

### ISSUE THREAD

**Issue by lzp0412** [nacos-group/nacos-sdk-go#80]
What would you like to be added:
create only one  gorutine for beat  on the same service
![image](https://user-images.githubusercontent.com/10192658/87134900-e12a0b00-c2cb-11ea-8fcb-0144c63be701.png)

Why is this needed:

**Comment by chuntaojun** [comment]
I think reactor mode can be easy，one gorutine deal need to send beat service，and other gorutine to send beatinfo

**Comment by sanxun0325** [comment]
@i will solve it@
