### ISSUE TITLE
readme文档中的错误

### ISSUE THREAD

**Issue by jimbirthday** [nacos-group/nacos-sdk-go#86]
1.注册服务实例：RegisterInstance 中缺失MetaData导致 nacos服务中空指针异常，
异常为：Can not get hosts from nacos server. serviceId: **

![image](https://user-images.githubusercontent.com/38313933/87261503-02b40e00-c4e9-11ea-9079-16100d01777c.png)

![image](https://user-images.githubusercontent.com/38313933/87261522-13fd1a80-c4e9-11ea-81e8-943089b2fbbb.png)

在用例代码中应该加入MetaData属性

2.注销服务实例：DeregisterInstance 传入的参数错误，应该为DeregisterInstanceParam
![image](https://user-images.githubusercontent.com/38313933/87261542-3000bc00-c4e9-11ea-84f8-bc097afb8c61.png)

**Comment by sanxun0325** [comment]
@jimbirthday Thank you for your warning.
